"""
Applet: Chemical Elements
Summary: Chemical Element Details
Description: Displays chemical element details.
Author: Robert Ison
"""

load("math.star", "math")
load("random.star", "random")
load("render.star", "render")
load("schema.star", "schema")
load("time.star", "time")

DEFAULT_TIMEZONE = "America/New_York"

elements = [
    {
        "AtomicNumber": 1,
        "Symbol": "H",
        "Group": "1",
        "Period": 1,
        "Name": "Hydrogen",
        "Mass": 1.008,
        "MeltingPoint": -259.1,
        "BoilingPoint": -252.9,
        "StateRoomTemp": "Gas",
        "Type": "Nonmetal",
        "Color": "aec6cf",
    },
    {
        "AtomicNumber": 2,
        "Symbol": "He",
        "Group": "18",
        "Period": 1,
        "Name": "Helium",
        "Mass": 4.003,
        "MeltingPoint": -272.2,
        "BoilingPoint": -268.9,
        "StateRoomTemp": "Gas",
        "Type": "Noble Gas",
        "Color": "bf00ff",
    },
    {
        "AtomicNumber": 3,
        "Symbol": "Li",
        "Group": "1",
        "Period": 2,
        "Name": "Lithium",
        "Mass": 6.968,
        "MeltingPoint": 180.5,
        "BoilingPoint": 1342,
        "StateRoomTemp": "Solid",
        "Type": "Alkali Metal",
        "Color": "ff0000",
    },
    {
        "AtomicNumber": 4,
        "Symbol": "Be",
        "Group": "2",
        "Period": 2,
        "Name": "Beryllium",
        "Mass": 9.012,
        "MeltingPoint": 1278,
        "BoilingPoint": 2970,
        "StateRoomTemp": "Solid",
        "Type": "Alkaline Earth",
        "Color": "ffa500",
    },
    {
        "AtomicNumber": 5,
        "Symbol": "B",
        "Group": "13",
        "Period": 2,
        "Name": "Boron",
        "Mass": 10.81,
        "MeltingPoint": 2079,
        "BoilingPoint": 2550,
        "StateRoomTemp": "Solid",
        "Type": "Metalloid",
        "Color": "006f86",
    },
    {
        "AtomicNumber": 6,
        "Symbol": "C",
        "Group": "14",
        "Period": 2,
        "Name": "Carbon",
        "Mass": 12.01,
        "MeltingPoint": 3367,
        "BoilingPoint": 4827,
        "StateRoomTemp": "Solid",
        "Type": "Nonmetal",
        "Color": "aec6cf",
    },
    {
        "AtomicNumber": 7,
        "Symbol": "N",
        "Group": "15",
        "Period": 2,
        "Name": "Nitrogen",
        "Mass": 14.01,
        "MeltingPoint": -209.9,
        "BoilingPoint": -195.8,
        "StateRoomTemp": "Gas",
        "Type": "Nonmetal",
        "Color": "aec6cf",
    },
    {
        "AtomicNumber": 8,
        "Symbol": "O",
        "Group": "16",
        "Period": 2,
        "Name": "Oxygen",
        "Mass": 16,
        "MeltingPoint": -218.4,
        "BoilingPoint": -183,
        "StateRoomTemp": "Gas",
        "Type": "Nonmetal",
        "Color": "aec6cf",
    },
    {
        "AtomicNumber": 9,
        "Symbol": "F",
        "Group": "17",
        "Period": 2,
        "Name": "Fluorine",
        "Mass": 19,
        "MeltingPoint": -219.8,
        "BoilingPoint": -188.1,
        "StateRoomTemp": "Gas",
        "Type": "Halogen",
        "Color": "800080",
    },
    {
        "AtomicNumber": 10,
        "Symbol": "Ne",
        "Group": "18",
        "Period": 2,
        "Name": "Neon",
        "Mass": 20.18,
        "MeltingPoint": -248,
        "BoilingPoint": -248.7,
        "StateRoomTemp": "Gas",
        "Type": "Noble Gas",
        "Color": "bf00ff",
    },
    {
        "AtomicNumber": 11,
        "Symbol": "Na",
        "Group": "1",
        "Period": 3,
        "Name": "Sodium",
        "Mass": 22.99,
        "MeltingPoint": 97.8,
        "BoilingPoint": 883,
        "StateRoomTemp": "Solid",
        "Type": "Alkali Metal",
        "Color": "ff0000",
    },
    {
        "AtomicNumber": 12,
        "Symbol": "Mg",
        "Group": "2",
        "Period": 3,
        "Name": "Magnesium",
        "Mass": 24.31,
        "MeltingPoint": 649,
        "BoilingPoint": 1090,
        "StateRoomTemp": "Solid",
        "Type": "Alkaline Earth",
        "Color": "ffa500",
    },
    {
        "AtomicNumber": 13,
        "Symbol": "Al",
        "Group": "13",
        "Period": 3,
        "Name": "Aluminum",
        "Mass": 26.98,
        "MeltingPoint": 660,
        "BoilingPoint": 2467,
        "StateRoomTemp": "Solid",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 14,
        "Symbol": "Si",
        "Group": "14",
        "Period": 3,
        "Name": "Silicon",
        "Mass": 28.09,
        "MeltingPoint": 1410,
        "BoilingPoint": 2355,
        "StateRoomTemp": "Solid",
        "Type": "Metalloid",
        "Color": "006f86",
    },
    {
        "AtomicNumber": 15,
        "Symbol": "P",
        "Group": "15",
        "Period": 3,
        "Name": "Phosphorus",
        "Mass": 30.97,
        "MeltingPoint": 44.1,
        "BoilingPoint": 280,
        "StateRoomTemp": "Solid",
        "Type": "Nonmetal",
        "Color": "aec6cf",
    },
    {
        "AtomicNumber": 16,
        "Symbol": "S",
        "Group": "16",
        "Period": 3,
        "Name": "Sulfur",
        "Mass": 32.07,
        "MeltingPoint": 112.8,
        "BoilingPoint": 444.7,
        "StateRoomTemp": "Solid",
        "Type": "Nonmetal",
        "Color": "aec6cf",
    },
    {
        "AtomicNumber": 17,
        "Symbol": "Cl",
        "Group": "17",
        "Period": 3,
        "Name": "Chlorine",
        "Mass": 35.45,
        "MeltingPoint": -101,
        "BoilingPoint": -34.6,
        "StateRoomTemp": "Gas",
        "Type": "Halogen",
        "Color": "800080",
    },
    {
        "AtomicNumber": 18,
        "Symbol": "Ar",
        "Group": "18",
        "Period": 3,
        "Name": "Argon",
        "Mass": 39.95,
        "MeltingPoint": -189.2,
        "BoilingPoint": -185.7,
        "StateRoomTemp": "Gas",
        "Type": "Noble Gas",
        "Color": "bf00ff",
    },
    {
        "AtomicNumber": 19,
        "Symbol": "K",
        "Group": "1",
        "Period": 4,
        "Name": "Potassium",
        "Mass": 39.1,
        "MeltingPoint": 63.25,
        "BoilingPoint": 760,
        "StateRoomTemp": "Solid",
        "Type": "Alkali Metal",
        "Color": "ff0000",
    },
    {
        "AtomicNumber": 20,
        "Symbol": "Ca",
        "Group": "2",
        "Period": 4,
        "Name": "Calcium",
        "Mass": 40.08,
        "MeltingPoint": 839,
        "BoilingPoint": 1484,
        "StateRoomTemp": "Solid",
        "Type": "Alkaline Earth",
        "Color": "ffa500",
    },
    {
        "AtomicNumber": 21,
        "Symbol": "Sc",
        "Group": "3",
        "Period": 4,
        "Name": "Scandium",
        "Mass": 44.96,
        "MeltingPoint": 1541,
        "BoilingPoint": 2832,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 22,
        "Symbol": "Ti",
        "Group": "4",
        "Period": 4,
        "Name": "Titanium",
        "Mass": 47.87,
        "MeltingPoint": 1660,
        "BoilingPoint": 3287,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 23,
        "Symbol": "V",
        "Group": "5",
        "Period": 4,
        "Name": "Vanadium",
        "Mass": 50.94,
        "MeltingPoint": 1890,
        "BoilingPoint": 3380,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 24,
        "Symbol": "Cr",
        "Group": "6",
        "Period": 4,
        "Name": "Chromium",
        "Mass": 52,
        "MeltingPoint": 1857,
        "BoilingPoint": 2672,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 25,
        "Symbol": "Mn",
        "Group": "7",
        "Period": 4,
        "Name": "Manganese",
        "Mass": 54.94,
        "MeltingPoint": 1244,
        "BoilingPoint": 1962,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 26,
        "Symbol": "Fe",
        "Group": "8",
        "Period": 4,
        "Name": "Iron",
        "Mass": 55.85,
        "MeltingPoint": 1535,
        "BoilingPoint": 2750,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 27,
        "Symbol": "Co",
        "Group": "9",
        "Period": 4,
        "Name": "Cobalt",
        "Mass": 58.93,
        "MeltingPoint": 1495,
        "BoilingPoint": 2870,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 28,
        "Symbol": "Ni",
        "Group": "10",
        "Period": 4,
        "Name": "Nickel",
        "Mass": 58.69,
        "MeltingPoint": 1453,
        "BoilingPoint": 2730,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 29,
        "Symbol": "Cu",
        "Group": "11",
        "Period": 4,
        "Name": "Copper",
        "Mass": 63.55,
        "MeltingPoint": 1083,
        "BoilingPoint": 2567,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 30,
        "Symbol": "Zn",
        "Group": "12",
        "Period": 4,
        "Name": "Zinc",
        "Mass": 65.38,
        "MeltingPoint": 419.6,
        "BoilingPoint": 906,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 31,
        "Symbol": "Ga",
        "Group": "13",
        "Period": 4,
        "Name": "Gallium",
        "Mass": 69.72,
        "MeltingPoint": 29.8,
        "BoilingPoint": 2403,
        "StateRoomTemp": "Solid",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 32,
        "Symbol": "Ge",
        "Group": "14",
        "Period": 4,
        "Name": "Germanium",
        "Mass": 72.63,
        "MeltingPoint": 947.4,
        "BoilingPoint": 2830,
        "StateRoomTemp": "Solid",
        "Type": "Metalloid",
        "Color": "006f86",
    },
    {
        "AtomicNumber": 33,
        "Symbol": "As",
        "Group": "15",
        "Period": 4,
        "Name": "Arsenic",
        "Mass": 74.92,
        "MeltingPoint": 817,
        "BoilingPoint": 617,
        "StateRoomTemp": "Solid",
        "Type": "Metalloid",
        "Color": "006f86",
    },
    {
        "AtomicNumber": 34,
        "Symbol": "Se",
        "Group": "16",
        "Period": 4,
        "Name": "Selenium",
        "Mass": 78.97,
        "MeltingPoint": 217,
        "BoilingPoint": 685,
        "StateRoomTemp": "Solid",
        "Type": "Nonmetal",
        "Color": "aec6cf",
    },
    {
        "AtomicNumber": 35,
        "Symbol": "Br",
        "Group": "17",
        "Period": 4,
        "Name": "Bromine",
        "Mass": 79.9,
        "MeltingPoint": -7.2,
        "BoilingPoint": 58.8,
        "StateRoomTemp": "Liquid",
        "Type": "Halogen",
        "Color": "800080",
    },
    {
        "AtomicNumber": 36,
        "Symbol": "Kr",
        "Group": "18",
        "Period": 4,
        "Name": "Krypton",
        "Mass": 83.8,
        "MeltingPoint": -157,
        "BoilingPoint": -152,
        "StateRoomTemp": "Gas",
        "Type": "Noble Gas",
        "Color": "bf00ff",
    },
    {
        "AtomicNumber": 37,
        "Symbol": "Rb",
        "Group": "1",
        "Period": 5,
        "Name": "Rubidium",
        "Mass": 85.47,
        "MeltingPoint": 38.9,
        "BoilingPoint": 686,
        "StateRoomTemp": "Solid",
        "Type": "Alkali Metal",
        "Color": "ff0000",
    },
    {
        "AtomicNumber": 38,
        "Symbol": "Sr",
        "Group": "2",
        "Period": 5,
        "Name": "Strontium",
        "Mass": 87.62,
        "MeltingPoint": 769,
        "BoilingPoint": 1384,
        "StateRoomTemp": "Solid",
        "Type": "Alkaline Earth",
        "Color": "ffa500",
    },
    {
        "AtomicNumber": 39,
        "Symbol": "Y",
        "Group": "3",
        "Period": 5,
        "Name": "Yttrium",
        "Mass": 88.91,
        "MeltingPoint": 1523,
        "BoilingPoint": 3337,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 40,
        "Symbol": "Zr",
        "Group": "4",
        "Period": 5,
        "Name": "Zirconium",
        "Mass": 91.22,
        "MeltingPoint": 1852,
        "BoilingPoint": 4377,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 41,
        "Symbol": "Nb",
        "Group": "5",
        "Period": 5,
        "Name": "Niobium",
        "Mass": 92.91,
        "MeltingPoint": 2468,
        "BoilingPoint": 4742,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 42,
        "Symbol": "Mo",
        "Group": "6",
        "Period": 5,
        "Name": "Molybdenum",
        "Mass": 95.95,
        "MeltingPoint": 2617,
        "BoilingPoint": 4612,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 43,
        "Symbol": "Tc",
        "Group": "7",
        "Period": 5,
        "Name": "Technetium",
        "Mass": 98,
        "MeltingPoint": 2172,
        "BoilingPoint": 4877,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 44,
        "Symbol": "Ru",
        "Group": "8",
        "Period": 5,
        "Name": "Ruthenium",
        "Mass": 101.1,
        "MeltingPoint": 2310,
        "BoilingPoint": 3900,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 45,
        "Symbol": "Rh",
        "Group": "9",
        "Period": 5,
        "Name": "Rhodium",
        "Mass": 102.9,
        "MeltingPoint": 1966,
        "BoilingPoint": 3727,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 46,
        "Symbol": "Pd",
        "Group": "10",
        "Period": 5,
        "Name": "Palladium",
        "Mass": 106.4,
        "MeltingPoint": 1554,
        "BoilingPoint": 3140,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 47,
        "Symbol": "Ag",
        "Group": "11",
        "Period": 5,
        "Name": "Silver",
        "Mass": 107.9,
        "MeltingPoint": 962,
        "BoilingPoint": 2212,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 48,
        "Symbol": "Cd",
        "Group": "12",
        "Period": 5,
        "Name": "Cadmium",
        "Mass": 112.4,
        "MeltingPoint": 320.9,
        "BoilingPoint": 765,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 49,
        "Symbol": "In",
        "Group": "13",
        "Period": 5,
        "Name": "Indium",
        "Mass": 114.8,
        "MeltingPoint": 156.6,
        "BoilingPoint": 2080,
        "StateRoomTemp": "Solid",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 50,
        "Symbol": "Sn",
        "Group": "14",
        "Period": 5,
        "Name": "Tin",
        "Mass": 118.7,
        "MeltingPoint": 232,
        "BoilingPoint": 2270,
        "StateRoomTemp": "Solid",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 51,
        "Symbol": "Sb",
        "Group": "15",
        "Period": 5,
        "Name": "Antimony",
        "Mass": 121.8,
        "MeltingPoint": 631,
        "BoilingPoint": 1950,
        "StateRoomTemp": "Solid",
        "Type": "Metalloid",
        "Color": "006f86",
    },
    {
        "AtomicNumber": 52,
        "Symbol": "Te",
        "Group": "16",
        "Period": 5,
        "Name": "Tellurium",
        "Mass": 127.6,
        "MeltingPoint": 449.5,
        "BoilingPoint": 989.8,
        "StateRoomTemp": "Solid",
        "Type": "Metalloid",
        "Color": "006f86",
    },
    {
        "AtomicNumber": 53,
        "Symbol": "I",
        "Group": "17",
        "Period": 5,
        "Name": "Iodine",
        "Mass": 126.9,
        "MeltingPoint": 113.5,
        "BoilingPoint": 184,
        "StateRoomTemp": "Solid",
        "Type": "Halogen",
        "Color": "800080",
    },
    {
        "AtomicNumber": 54,
        "Symbol": "Xe",
        "Group": "18",
        "Period": 5,
        "Name": "Xenon",
        "Mass": 131.3,
        "MeltingPoint": -111.8,
        "BoilingPoint": -107.1,
        "StateRoomTemp": "Gas",
        "Type": "Noble Gas",
        "Color": "bf00ff",
    },
    {
        "AtomicNumber": 55,
        "Symbol": "Cs",
        "Group": "1",
        "Period": 6,
        "Name": "Cesium",
        "Mass": 132.9,
        "MeltingPoint": 28.4,
        "BoilingPoint": 669,
        "StateRoomTemp": "Solid",
        "Type": "Alkali Metal",
        "Color": "ff0000",
    },
    {
        "AtomicNumber": 56,
        "Symbol": "Ba",
        "Group": "2",
        "Period": 6,
        "Name": "Barium",
        "Mass": 137.3,
        "MeltingPoint": 725,
        "BoilingPoint": 1640,
        "StateRoomTemp": "Solid",
        "Type": "Alkaline Earth",
        "Color": "ffa500",
    },
    {
        "AtomicNumber": 57,
        "Symbol": "La",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Lanthanum",
        "Mass": 138.9,
        "MeltingPoint": 920,
        "BoilingPoint": 3454,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 58,
        "Symbol": "Ce",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Cerium",
        "Mass": 140.1,
        "MeltingPoint": 798,
        "BoilingPoint": 3257,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 59,
        "Symbol": "Pr",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Praseodymium",
        "Mass": 140.9,
        "MeltingPoint": 931,
        "BoilingPoint": 3017,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 60,
        "Symbol": "Nd",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Neodymium",
        "Mass": 144.2,
        "MeltingPoint": 1016,
        "BoilingPoint": 3127,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 61,
        "Symbol": "Pm",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Promethium",
        "Mass": 145,
        "MeltingPoint": 1042,
        "BoilingPoint": 3000,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 62,
        "Symbol": "Sm",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Samarium",
        "Mass": 150.4,
        "MeltingPoint": 1074,
        "BoilingPoint": 1794,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 63,
        "Symbol": "Eu",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Europium",
        "Mass": 152,
        "MeltingPoint": 822,
        "BoilingPoint": 1529,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 64,
        "Symbol": "Gd",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Gadolinium",
        "Mass": 157.3,
        "MeltingPoint": 1313,
        "BoilingPoint": 3273,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 65,
        "Symbol": "Tb",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Terbium",
        "Mass": 158.9,
        "MeltingPoint": 1365,
        "BoilingPoint": 3230,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 66,
        "Symbol": "Dy",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Dysprosium",
        "Mass": 162.5,
        "MeltingPoint": 1412,
        "BoilingPoint": 2567,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 67,
        "Symbol": "Ho",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Holmium",
        "Mass": 164.9,
        "MeltingPoint": 1474,
        "BoilingPoint": 2700,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 68,
        "Symbol": "Er",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Erbium",
        "Mass": 167.3,
        "MeltingPoint": 1529,
        "BoilingPoint": 2868,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 69,
        "Symbol": "Tm",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Thulium",
        "Mass": 168.9,
        "MeltingPoint": 1545,
        "BoilingPoint": 1950,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 70,
        "Symbol": "Yb",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Ytterbium",
        "Mass": 173.1,
        "MeltingPoint": 819,
        "BoilingPoint": 1196,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 71,
        "Symbol": "Lu",
        "Group": "Lanthanoid",
        "Period": 6,
        "Name": "Lutetium",
        "Mass": 175,
        "MeltingPoint": 1663,
        "BoilingPoint": 3402,
        "StateRoomTemp": "Solid",
        "Type": "Lanthanoid",
        "Color": "22b14c",
    },
    {
        "AtomicNumber": 72,
        "Symbol": "Hf",
        "Group": "4",
        "Period": 6,
        "Name": "Hafnium",
        "Mass": 178.5,
        "MeltingPoint": 2227,
        "BoilingPoint": 4600,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 73,
        "Symbol": "Ta",
        "Group": "5",
        "Period": 6,
        "Name": "Tantalum",
        "Mass": 180.9,
        "MeltingPoint": 2996,
        "BoilingPoint": 5425,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 74,
        "Symbol": "W",
        "Group": "6",
        "Period": 6,
        "Name": "Tungsten",
        "Mass": 183.8,
        "MeltingPoint": 3410,
        "BoilingPoint": 5660,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 75,
        "Symbol": "Re",
        "Group": "7",
        "Period": 6,
        "Name": "Rhenium",
        "Mass": 186.2,
        "MeltingPoint": 3180,
        "BoilingPoint": 5600,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 76,
        "Symbol": "Os",
        "Group": "8",
        "Period": 6,
        "Name": "Osmium",
        "Mass": 190.2,
        "MeltingPoint": 3045,
        "BoilingPoint": 5030,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 77,
        "Symbol": "Ir",
        "Group": "9",
        "Period": 6,
        "Name": "Iridium",
        "Mass": 192.2,
        "MeltingPoint": 2410,
        "BoilingPoint": 4130,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 78,
        "Symbol": "Pt",
        "Group": "10",
        "Period": 6,
        "Name": "Platinum",
        "Mass": 195.1,
        "MeltingPoint": 1772,
        "BoilingPoint": 3827,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 79,
        "Symbol": "Au",
        "Group": "11",
        "Period": 6,
        "Name": "Gold",
        "Mass": 197,
        "MeltingPoint": 1064,
        "BoilingPoint": 3080,
        "StateRoomTemp": "Solid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 80,
        "Symbol": "Hg",
        "Group": "12",
        "Period": 6,
        "Name": "Mercury",
        "Mass": 200.6,
        "MeltingPoint": -38.9,
        "BoilingPoint": 357,
        "StateRoomTemp": "Liquid",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 81,
        "Symbol": "Tl",
        "Group": "13",
        "Period": 6,
        "Name": "Thallium",
        "Mass": 204.4,
        "MeltingPoint": 303,
        "BoilingPoint": 1457,
        "StateRoomTemp": "Solid",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 82,
        "Symbol": "Pb",
        "Group": "14",
        "Period": 6,
        "Name": "Lead",
        "Mass": 207.2,
        "MeltingPoint": 327.5,
        "BoilingPoint": 1740,
        "StateRoomTemp": "Solid",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 83,
        "Symbol": "Bi",
        "Group": "15",
        "Period": 6,
        "Name": "Bismuth",
        "Mass": 209,
        "MeltingPoint": 271,
        "BoilingPoint": 1560,
        "StateRoomTemp": "Solid",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 84,
        "Symbol": "Po",
        "Group": "16",
        "Period": 6,
        "Name": "Polonium",
        "Mass": 209,
        "MeltingPoint": 254,
        "BoilingPoint": 962,
        "StateRoomTemp": "Solid",
        "Type": "Metalloid",
        "Color": "006f86",
    },
    {
        "AtomicNumber": 85,
        "Symbol": "At",
        "Group": "17",
        "Period": 6,
        "Name": "Astatine",
        "Mass": 210,
        "MeltingPoint": 302,
        "BoilingPoint": 337,
        "StateRoomTemp": "Solid",
        "Type": "Halogen",
        "Color": "800080",
    },
    {
        "AtomicNumber": 86,
        "Symbol": "Rn",
        "Group": "18",
        "Period": 6,
        "Name": "Radon",
        "Mass": 222,
        "MeltingPoint": -71,
        "BoilingPoint": -61.8,
        "StateRoomTemp": "Gas",
        "Type": "Noble Gas",
        "Color": "bf00ff",
    },
    {
        "AtomicNumber": 87,
        "Symbol": "Fr",
        "Group": "1",
        "Period": 7,
        "Name": "Francium",
        "Mass": 223,
        "MeltingPoint": 27,
        "BoilingPoint": 677,
        "StateRoomTemp": "Solid",
        "Type": "Alkali Metal",
        "Color": "ff0000",
    },
    {
        "AtomicNumber": 88,
        "Symbol": "Ra",
        "Group": "2",
        "Period": 7,
        "Name": "Radium",
        "Mass": 226,
        "MeltingPoint": 700,
        "BoilingPoint": 1140,
        "StateRoomTemp": "Solid",
        "Type": "Alkaline Earth",
        "Color": "ffa500",
    },
    {
        "AtomicNumber": 89,
        "Symbol": "Ac",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Actinium",
        "Mass": 227,
        "MeltingPoint": 1050,
        "BoilingPoint": 3200,
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 90,
        "Symbol": "Th",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Thorium",
        "Mass": 232,
        "MeltingPoint": 1750,
        "BoilingPoint": 4790,
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 91,
        "Symbol": "Pa",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Protactinium",
        "Mass": 231,
        "MeltingPoint": 1570,
        "BoilingPoint": 4000,
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 92,
        "Symbol": "U",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Uranium",
        "Mass": 238,
        "MeltingPoint": 1132,
        "BoilingPoint": 3818,
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 93,
        "Symbol": "Np",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Neptunium",
        "Mass": 237,
        "MeltingPoint": 640,
        "BoilingPoint": 3900,
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 94,
        "Symbol": "Pu",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Plutonium",
        "Mass": 244,
        "MeltingPoint": 641,
        "BoilingPoint": 3232,
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 95,
        "Symbol": "Am",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Americium",
        "Mass": 243,
        "MeltingPoint": 994,
        "BoilingPoint": 2607,
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 96,
        "Symbol": "Cm",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Curium",
        "Mass": 247,
        "MeltingPoint": 1340,
        "BoilingPoint": "",
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 97,
        "Symbol": "Bk",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Berkelium",
        "Mass": 247,
        "MeltingPoint": 986,
        "BoilingPoint": "",
        "StateRoomTemp": "Solid",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 98,
        "Symbol": "Cf",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Californium",
        "Mass": 251,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 99,
        "Symbol": "Es",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Einsteinium",
        "Mass": 252,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 100,
        "Symbol": "Fm",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Fermium",
        "Mass": 257,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 101,
        "Symbol": "Md",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Mendelevium",
        "Mass": 258,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 102,
        "Symbol": "No",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Nobelium",
        "Mass": 259,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 103,
        "Symbol": "Lr",
        "Group": "Actinoids",
        "Period": 7,
        "Name": "Lawrencium",
        "Mass": 262,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Actinoid",
        "Color": "013220",
    },
    {
        "AtomicNumber": 104,
        "Symbol": "Rf",
        "Group": "4",
        "Period": 7,
        "Name": "Rutherfordium",
        "Mass": 267,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 105,
        "Symbol": "Db",
        "Group": "5",
        "Period": 7,
        "Name": "Dubnium",
        "Mass": 268,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 106,
        "Symbol": "Sg",
        "Group": "6",
        "Period": 7,
        "Name": "Seaborgium",
        "Mass": 271,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 107,
        "Symbol": "Bh",
        "Group": "7",
        "Period": 7,
        "Name": "Bohrium",
        "Mass": 272,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 108,
        "Symbol": "Hs",
        "Group": "8",
        "Period": 7,
        "Name": "Hassium",
        "Mass": 270,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 109,
        "Symbol": "Mt",
        "Group": "9",
        "Period": 7,
        "Name": "Meitnerium",
        "Mass": 276,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 110,
        "Symbol": "Ds",
        "Group": "10",
        "Period": 7,
        "Name": "Darmstadtium",
        "Mass": 281,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 111,
        "Symbol": "Rg",
        "Group": "11",
        "Period": 7,
        "Name": "Roentgentium",
        "Mass": 280,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 112,
        "Symbol": "Cn",
        "Group": "12",
        "Period": 7,
        "Name": "Copernicum",
        "Mass": 285,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Transition Metal",
        "Color": "ffffbf",
    },
    {
        "AtomicNumber": 113,
        "Symbol": "Nh",
        "Group": "13",
        "Period": 7,
        "Name": "Nihonium",
        "Mass": 284,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 114,
        "Symbol": "Fl",
        "Group": "14",
        "Period": 7,
        "Name": "Flerovium",
        "Mass": 289,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 115,
        "Symbol": "Mc",
        "Group": "15",
        "Period": 7,
        "Name": "Moscovium",
        "Mass": 288,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 116,
        "Symbol": "Lv",
        "Group": "16",
        "Period": 7,
        "Name": "Livermorium",
        "Mass": 293,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Basic Metal",
        "Color": "008000",
    },
    {
        "AtomicNumber": 117,
        "Symbol": "Ts",
        "Group": "17",
        "Period": 7,
        "Name": "Tennessine",
        "Mass": 292,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Halogen",
        "Color": "800080",
    },
    {
        "AtomicNumber": 118,
        "Symbol": "Og",
        "Group": "18",
        "Period": 7,
        "Name": "Oganesson",
        "Mass": 294,
        "MeltingPoint": "",
        "BoilingPoint": "",
        "StateRoomTemp": "",
        "Type": "Noble Gas",
        "Color": "bf00ff",
    },
]

def getMainCommentary(element):
    """ getMainCommentary

    Args:
        element: the element we need data from

    Returns:
        The display text for the first commentary line.
    """
    return "Atomic Number %s with symbol %s is in group %s and period %s" % (element["AtomicNumber"], element["Symbol"], element["Group"].lower(), element["Period"])

def getSecondaryCommentary(element):
    """ getSecondaryCommentary

    Args:
        element: the element we need data from

    Returns:
        The display text for the second commentary line.
    """
    return "This %s has an atomic weight of %su" % (element["Type"].lower(), element["Mass"])

def getTertiaryCommentary(element):
    """ getTertiaryCommentary

    Args:
        element: the element we need data from

    Returns:
        The display text for the third commentary line.
    """
    returnValue = ""
    if (len(str(element["StateRoomTemp"])) > 0):
        returnValue += "A %s at room temperature " % ((element["StateRoomTemp"]).lower())
    if (len(str(element["MeltingPoint"])) > 0):
        returnValue += "with a melting point of %s%sC " % (element["MeltingPoint"], chr(176))
    if (len(str(element["BoilingPoint"])) > 0):
        returnValue += "and a boiling point of %s%sC " % (element["BoilingPoint"], chr(176))
    return returnValue

def day_of_year(date, timezone):
    """ day_of_year

    Args:
        date: the current time
        timezone: the current timezone

    Returns:
        The day of the year, and integer between 1 and 366
    """

    firstdayofyear = time.time(year = date.year, month = 1, day = 1, hour = 0, minute = 0, second = 0, location = timezone)
    day_of_year = math.ceil(time.parse_duration(date - firstdayofyear).seconds / 86400)
    return (day_of_year)

def main(config):
    """ Main

    Args:
        config: Configuration Items to control how the app is displayed
    Returns:
        The display inforamtion for the Tidbyt
    """

    #instead can choose one element per day based on day of year..
    #it'll cycle through a new element each day and restart on the 119th day
    if (config.get("display", "OncePerDay") == "OncePerDay"):
        now = config.get("time")
        now = (time.parse_time(now) if now else time.now())
        current_element = elements[day_of_year(now, DEFAULT_TIMEZONE) % len(elements)]
    else:
        #default is random element
        current_element = elements[random.number(0, len(elements) - 1)]
        
    row1 = current_element["Name"]
    row2 = getMainCommentary(current_element)
    row3 = getSecondaryCommentary(current_element)
    row4 = getTertiaryCommentary(current_element)

    return render.Root(
        render.Column(
            children = [
                render.Row(
                    children = [
                        render.Column(
                            children = [
                                render.Box(width = 1, height = 32, color = current_element["Color"]),
                            ],
                        ),
                        render.Column(
                            children = [
                                render.Box(width = 32, height = 1, color = current_element["Color"]),
                                render.Box(width = 32, height = 1, color = "#000000"),
                                render.Text(" %s" % (current_element["AtomicNumber"]), color = "fff", font = "CG-pixel-3x5-mono"),
                                render.Box(width = 32, height = 1, color = "#000000"),
                                render.Text(" %s" % current_element["Symbol"], color = "fff", font = "5x8"),
                                render.Text(" %s" % (current_element["Name"][:5]), color = "fff", font = "5x8"),
                                render.Box(width = 32, height = 1, color = "#000000"),
                                render.Text(" %s" % current_element["Mass"], color = "fff", font = "CG-pixel-3x5-mono"),
                                render.Box(width = 32, height = 1, color = "#000000"),
                                render.Box(width = 32, height = 1, color = current_element["Color"]),
                            ],
                        ),
                        render.Column(
                            children = [
                                render.Box(width = 1, height = 32, color = current_element["Color"]),
                            ],
                        ),
                        render.Column(
                            children = [
                                render.Box(width = 1, height = 32, color = "#000000"),
                            ],
                        ),
                        render.Column(
                            children = [
                                render.Marquee(
                                    width = 32,
                                    child = render.Text(row1, color = "#ffd700", font = "5x8"),
                                ),
                                render.Marquee(
                                    width = 32,
                                    offset_start = len(row1) * 5,
                                    child = render.Text(row2, color = "#ffd700", font = "5x8"),
                                ),
                                render.Marquee(
                                    width = 32,
                                    offset_start = len(row1 + row2) * 5,
                                    child = render.Text(row3, color = "#ffd700", font = "5x8"),
                                ),
                                render.Marquee(
                                    width = 32,
                                    offset_start = len(row1 + row2 + row3) * 5,
                                    child = render.Text(row4, color = "#ffd700", font = "5x8"),
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
        show_full_animation = True,
        delay = int(config.get("scroll", 45)),
    )

scroll_speed_options = [
    schema.Option(
        display = "Slow Scroll",
        value = "60",
    ),
    schema.Option(
        display = "Medium Scroll",
        value = "45",
    ),
    schema.Option(
        display = "Fast Scroll",
        value = "30",
    ),
]

element_display_options = [
    schema.Option(
        display = "One Element Per Day",
        value = "OncePerDay",
    ),
    schema.Option(
        display = "Random Element Each Time",
        value = "Random",
    ),
]

def get_schema():
    return schema.Schema(
        version = "1",
        fields = [
            schema.Dropdown(
                id = "scroll",
                name = "Scroll",
                desc = "Scroll Speed",
                icon = "stopwatch",
                options = scroll_speed_options,
                default = scroll_speed_options[0].value,
            ),
            schema.Dropdown(
                id = "display",
                name = "Display",
                desc = "Display Choice",
                icon = "display",
                options = element_display_options,
                default = element_display_options[0].value,
            ),
        ],
    )
