"""
Applet: NES Clock
Summary: NES Game Themed Clock
Description: Short animations of various Nintendo characters with a clock in the background.
Author: hx009
"""

load("encoding/base64.star", "base64")
load("encoding/json.star", "json")
load("math.star", "math")
load("random.star", "random")
load("render.star", "render")
load("schema.star", "schema")
load("time.star", "time")

FRAME_HEIGHT = 32
FRAME_WIDTH = 64
DEFAULT_HAS_LEADING_ZERO = False
DEFAULT_IS_24_HOUR_FORMAT = False
DEFAULT_LOCATION = {
    "lat": 41.505550,
    "lng": -81.691498,
    "locality": "Cleveland, OH",
}
DEFAULT_GAME = "0"
DEFAULT_SPEED = "30"
DEFAULT_TIMEZONE = "US/Eastern"
MAX_SPEED = 10
MIN_SPEED = 50
SECONDS_TO_RENDER = 15
SPEED_LIST = {
    "Snail": "50",
    "Slow": "40",
    "Medium": "30",
    "Fast": "20",
    "Turbo": "10",
    "Random": "-1",
}

GAME_LIST = {
    "Random": "0",
    "Bionic Commando": "11",
    "Contra": "5",
    "Bubble Bobble": "9",
    "Castlevania": "14",
    "Chip 'n Dale: Rescue Rangers": "10",
    "Double Dragon": "15",
    "DuckTales": "8",
    "Excitebike": "6",
    "Final Fantasy": "13",
    "Kid Icarus": "12",
    "Kirby's Adventure": "3",
    "Little Nemo": "7",
    "Mega Man": "2",
    "Ninja Gaiden": "16",
    "Super Mario Bros. 3": "1",
    "The Legend of Zelda": "4",
}

GAME_CONFIGS = [
    {"SPRITE_WIDTH": 0, "DIST_BETWEEN_SPRITES": 0, "SPRITE_MIN_X": 0, "SPRITE_Y_POS": 0, "SPRITE_MOVE_SPEED": 0, "SPRITE_FRAMES_PER_FRAME": 0},
    # 1 - Super Mario Bros. 3
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAAXNSR0IArs4c6QAAAVJJREFUaEPtmVEKwjAMhjvZLbyFIEzPMnwTfNhx9rBn8SwqyLyGlygqGaRkte0yQaRp97JuK9n+L3+zjBV1q19K2Hbc3tSjb1iqihQALPe9F4Y4AJB93MAFIP55v6jFajPawxw4JwYAFU4BwDgpB4Bg2wWhYiDGAbZILgSxAGwnwLHrzZAUANdSSALA7rw22u1iKRYACKXCafYRAlwXCyBU+ZMHQOEk6YAMgBDIDvB9DZ6a0llH6lazPjNjmfThABSuu8qpoTxch/NSQIwAgHifcJsGgJAAwQCYIx5hSIAQBAAC0RF0LA6AL/tTAABE7C4YHPCN/aW4IAPIDshLIPEaoJQyf4agsfG1wNzWNrYYhe6qAQC2uDAOtcFTfQGCiiWGAeDKsKv54TqBvia57bUv9i+fYwSAe6PQvNhiBB0wN9sxzmcB8GWVm22sMa6l8O8Yb56mP6oG3pCsAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAAXNSR0IArs4c6QAAAWtJREFUaEPtlyEOAkEMRWeD4BwIEgwGNJIDoBAcAM9B8BwAgSLBYkjQYDAkCC6BWUEgneRPujMdWNvdrtxZxHvT/pZiX74/rsVPYQKsAqwFLANanIHOQtCmgE0BmwLJFJh1O0ku7st3Y7KS8yUhSIer+9zD3i7XAH1cPFwTJMR8FQH8kF83RGiXIPGJAtaDXVLu023fv9MsAQI4XxBAhwRJgPTEbUDvca6xFXJ8FQEcPNcCWiUg+HCx4KsIiA/xEc8AzQIkPlHApLdx5+cyFAEXgJfa2oAHIOfzAuJDQMYSkAPawvAXXyKA4OIKwE5AAqiMqCI0TYN4/P2sgNy6R9DD8aiyIGmRkNtvCKZwzn0QDtLNS0I0LUa53g9TAAIIXup9qSU0Csjx/a0A6YcaBeSyzQug2Y7+lkqet4a2P0jYAHN8YQpg16/7n1dLABIPJEhsvgLqQjfxu+J1OpiAJt5sXSargNa3QNtD8AtPNFLEW9t33AAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAAXNSR0IArs4c6QAAALRJREFUaEPtl8sNgCAQRJfEAjxYAGVYkGVZkGVYgAcKINGgLlG0Adi3N1kuM5kPujmGXQyPgwAUgAVeGTB1fU6EOYZPOrS2zxmgwPy4ZdDrMoiS0OreicipAAWeQOukM/1ude/8uJ0ElED1rAReKqT2/UcBpen/iHneqX2fFWD1LQQBmgEowCgDWAAL3O8Aow4QLIAFsMD1L2B1yAAygAwgAwhBqw2QcNMCtAAtQAvQApZb4ACVJQZcANljHgAAAABJRU5ErkJggg==""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 16,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": -42,
        "SPRITE_Y_POS": 10,
        "SPRITE_MOVE_SPEED": 1,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Mario walking
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAK5JREFUOE+lk8EJgDAMRauTuILgzREcwbMjihN4E1zBSaykNCUmP1iwF0vMfwk/aRN+nsbRRydu8hEgrn0H9dN5cbzoNMAVS2IGJa0BcOJ97OnaDmOgO33FgR1EKaJkFnKcARlmOoAA2cUXgP4n92VF1fqniRCCKhtSDpQp8Mh4pNJ56Ca1r+dfA5FjdAFqq16jN3uADFR7UAfYlrkUFitslq/6LdSYyBW9l4hWPzxYX1ERBp7bCQAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAANFJREFUOE+Fk8ENwjAMRRsm6QpI3JgAdQTOTMWZERAT9IbECkxCkKN869v5lFwaufaL879TJr2qCBeVqoL1vp+H3OX15pjXZYAszrQOa7UDAMmf59q2u8Nxsr19ackOKhdZMgoRB6DDhg4kgLv4B7D/TX0+MbUOxm8RswZ8cW49k9rJbB9sQ2zLRr/743IOjimIAbONDrBqQNKJDjbA6XqDrQViDA6wFhCSbYUePEhq/sOVkh5hDnyEt1oHTY1yeAOcYLMh3NGjrGa9x/h64f18ARRDbBFCmAfSAAAAAElFTkSuQmCC""",
            ],
            [
                # Mario swimming
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAALZJREFUOE+dk8EJgDAMRdVJXEHw5giO4NkRxQm8Ca7gJFYSmvpNvyj2YkmT19/8WBZ8BRIuWSoLhqmps9x+2y12q/EAWoy0CEp1GcCSj3XRbdV2hezlC4sCAhZJshVa3AARphBUQAGo4g0g59p9vNFJzxpJXfCS2c3UElFgFoJttHkMkFloEIF6+xCQmifBeRz0DBX8Bjj/H0eZzf3Xsdc5eGucn5cbPAG+dt1LU0AM0jfyv/2Knn5bVRFWGIrGAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAALxJREFUOE+Vk9ENwjAMRFsm6QpI/DEB6oh8MwIj8IfECkxC0FmxdXUuKeQnkXN+sXzOPOlVRHhWUhUs9+PSaNfX22ObnAyQyUyroMhrAC7+PB92PJzOE87YaUlA4SSIPdHjDqgwg3AFEsBV7AFwb93nF1PpTSOlCxmiXpaW1KCaga7eK4gkngH3HrFsHxPDe4ggvlxv4Rh68Bdg0MTuKG8q6PyNbHnIQDUAzfqvf8Z0BqgZssRBRQHY0wzvv19XThEU4DxwAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAALNJREFUOE+tk8sNgDAMQ4FJWAGJGyMwLyNwQ2IFJqEoEa5Maj4HegGl8UsUp3WlTxLhWqWqYJq6tsgd1w2xiyYCpJhpJyjrCgCS92X236YfKvu3Lx0JSCyyZAgRB+CEOYQ7kADu4g1g9z59rhhaLwYpXYgth8oXhwBQvssNid0ZIFsHr9UeGM3ufwPACdmBVXvZxuxgBtCq3jwPDxdDdwAqPkDkQ2KiDzIAbkVqp2HjJxEDDvQcWA6ewAySAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAALNJREFUOE+Nk80NgCAMhcFJXMHEmyM4ryN4M3EFJxHThpLSvga5QMrrR+lPTngVYM5IiozlWGan3e9HbJ2PBUBnTaug5ucAIn6vk4/TuiU6064WBBTtRGJxFLsAKowhOgII0FGMAHTP2dcvmtBdImEVbMj68xYYJjHoDxedALrGQX1AQCqh/R4BWu2lWf4ApBIQQK8NurFVMAQEOXBJbwDV639nhnUMqB5w2qJqwMkaidH9ByHuUQ5fGfU8AAAAAElFTkSuQmCC""",
            ],
        ],
    },
    # 2 - Mega Man
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAAXNSR0IArs4c6QAAAI5JREFUaEPt17EJgDAQheF3lQ7nAG6gI2UAxQUcxhEcIV0EQbAIaBven/pS5HF3HwmdR5HxCQKgAxgBdoDxDhRLEAVQAAVQAAWME4BBGIRBGIRBYwT4DMEgDMIgDMKgNYOlFO8OGHMigGcEtm7SGqE9p8+pqNW2eD/eHTD08/3wPwHUalu8H4vkPQIyD+AC4U+KUvuYVnUAAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 24,
        "DIST_BETWEEN_SPRITES": 60,
        "SPRITE_MIN_X": -108,
        "SPRITE_Y_POS": 2,
        "SPRITE_MOVE_SPEED": 2,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Mega Man
                """iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURQAAAADo2ABw7PzkoPz8/AAAAO8UHAIAAAAGdFJOU///////ALO/pL8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAACgSURBVChTjZHbDsMgDENz4/9/ebYDW6q20vxQwIckFrX1or+B2XauALZ7WxdgEXHIBPRButsDcA+4A5gLoOQBZFVF1AQMRN8sbQDGdLsDjiVJtsrKAxQHvnsyLP0f4AwoMgknQCoKbp8I9HQWmI4SaQPc0UWSCViLl9B3SzPkM+1edvdu1I6CsU8DjtYAbln1BVr7lxL09oCWCshu4GitD/uQBuB2YZXNAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURQAAAADo2ABw7PzkoPz8/AAAAO8UHAIAAAAGdFJOU///////ALO/pL8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAACSSURBVChTbZJZDsAgCAXZvP+VywOs0Er8MDNhs6U1g6jIFI6ZEw1BIrJNF+BustpFMIvTJohDeMpFqJmJ2BA+EDiR0hCY5iacQ6CUmh4BHgbDgneBYooIVuJdOiJA4BS+QRYE3AIGB3yKytlP1UTmUL16F9jdR/uLaL0/4LdH9I04l8mnqIEi2m2mHIFf5E1Z6wHrlQeqWUG/UwAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURQAAAADo2ABw7PzkoPz8/AAAAO8UHAIAAAAGdFJOU///////ALO/pL8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAACmSURBVChTjZBRDgMgCENB9P5XXlsQyZIl40NjX8GqnR/1HzB7xwEgu/d5WNZagzwHdJCe9g3cV0q1YrwAWgbQpQCx915rN4BHALpZWIObZgAmwMwGHBU7JIFxPUkYNmrGA27BMq8ODYSJhIU9rQyQ3ZAAS8+4fJYKP8UHyS2zCP3q51pxYdUt79cFyq17mygV3Xdm6UpVcwnqAkq1p84qZYBbPJzzAVOBBm9yUgVbAAAAAElFTkSuQmCC""",
            ],
        ],
    },
    # 3 - Kirby's Adventure
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURby8vACoAECI/Pz8/AAAACIqD1IAAAAJcEhZcwAADsIAAA7CARUoSoAAAACISURBVDjLzZHbDYAwCEUxXUCcQJ2ABDeQ/WeyL7U+74fGeP4oJ3DbElHFzE2f6DgR6pYi6i4FUU8WsjH3Y50Fl4RorP1QtyLFhHBS9n3tJzgVLMwrmHvekldAYVlxoN5lOBPghA+EQcfimkdBTA0LtyueC9u/OMtAb2T4wzsYAAsKwALkPoHZBAq2b/W6zH+xAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURfC8PPzYqDy8/HwIAPyYOF2EV7sAAAAJcEhZcwAADsEAAA7BAbiRa+0AAABrSURBVDjL7crRCYAwDATQK7jAiQvUFdIFRPefSdOioDTJh+CX99FLuYdn0jjfgkBk+IKEJzL74BS690ETdTeAirZbAIn0wSUQCUQCkUAk4CcESPjzWaToO4jV2Nai38lqHJfIQloNBnkLyB3weh8NRXuCjAAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURQBw7MTU/CQYjFyU/AAAqCA47BQJ0CMAAAAJcEhZcwAADsAAAA7AAWrWiQkAAAClSURBVDjLpZLrCQQhDIQnbgOKDYgVGGzhOjiu/1Yu2cex/tA52AGFMR+TKAIRQA21loqfLi8qkOYnpdaAm04vmh2wjBmQOrI6EEIpd+D0khRJvckUSA5YC8sbgcOLJMQW/R5lGOHyNyCUETi8WHrc61M5sD/VAsBSpMwBVhcKNAJsyhLsPxAgkxZpIwnyGAAZ8g89TwBeRPgQ8RadCP1t+2KRhN6/xj8xkrtbGIsAAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 16,
        "DIST_BETWEEN_SPRITES": 5,
        "SPRITE_MIN_X": -37,
        "SPRITE_Y_POS": 11,
        "SPRITE_MOVE_SPEED": 2,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Kirby
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQQCBPxuzPzC5AAAAHHu1hwAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAYklEQVQoU22PQQ4AMQgCUf//52Ww7WlpYhUVogYIJBs+qbq7lnJICSpdxg/R7GWcEfmVw2tDEH6IOES3SlgttaB8rt7A1/2rwkAWHmOJaKCV0tkh/GG3JbfkCG7Y45xRBzMf0+EBhzj2w3oAAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQQCBPxuzPzC5AAAAHHu1hwAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7BAAAOwQG4kWvtAAAAWElEQVQoU22PCw7AIAhDrdz/zusH3LJYI6FPEVz1U8CyktpiUzBhiJV8+vEDxmmpvn0Az68AG91HgOl7i0BdAhgNZi5Ko7l1E4/qzcfOZxJAER/Aor5Q9QAApQHH/bXo5wAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQQCBPxuzPzC5AAAAHHu1hwAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7BAAAOwQG4kWvtAAAAX0lEQVQoU1WPAQ7AIAwCAf//5wGtSyRG7YFacSJE3Z0sACVxkKeWEet6bC0N+ANCiMGWD2Dpk4DoowN6x2IDK9bAAjeE8duIAe/D7TVgiWtHcmkPWbY2lE/FWHCVEM4H7RQBnYG2LTcAAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQQCBPxuzPzC5AAAAHHu1hwAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAWElEQVQoU22PCw7AIAhDrdz/zusH3LJYI6FPEVz1U8CyktpiUzBhiJV8+vEDxmmpvn0Az68AG91HgOl7i0BdAhgNZi5Ko7l1E4/qzcfOZxJAER/Aor5Q9QAApQHH/bXo5wAAAABJRU5ErkJggg==""",
            ],
        ],
    },
    # 4 - The Legend of Zelda
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAVUExURQCoAAAAAPzYqCA47EI4LIJvVorCXPUXXY8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAACNSURBVDjL7ZOxDcMwDASf8QKisoBMBK5jaINAEwTw/quYpCXbRYS0LvzNEfp/dQ9ilgQVc2wU424EJdkDxUZBOAwriBf5YPIPqvEQFd5zODMNQzWQvTLmPFulUZ65GiilaLCYPrLz5YcZkD+6A3fgcoHla5imHm1KupPUJyhE32CPGt3W3CUR60G/CVoBgzx4ThwyyF4AAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJUExURchMDAAAAPzYqBTcGz8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB0SURBVDjL7ZNBDsAgCASXH4Av0P3/IwtWD43SXnoUTSbKBC8uBFIBU6CsVF8Ci4s6Gk/aLcAPhHClzQlSWH0vHAJ991oZgttpNVWY5X3SDPyoIxzhZ0He+5Ew5t+ezUMkzIMTA7aRm+zCLrST8QKgefwFuABLgm9cOXoqIgAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURchMDAAAAPzYqCA47HBLeoYAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACESURBVDjL7ZJRDsMgDENddgFMLxA4wbbc/24NkzPtp+Vnn7VkHKOniA8A0FCAtvvUu6pnomzsaNgSaNmVAYxeYxhfQF0ZuxF4XBBTpaqb8gPwZ0NVNyVgQTLmBNQz461WGgdzQ/auxFjoBm7g3wDnzzs3uBC4v/zKcH/4leEL4RnHud0PzoV7Rv/QahwAAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 16,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": -42,
        "SPRITE_Y_POS": 8,
        "SPRITE_MOVE_SPEED": 1,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Link
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURYDQEMhMDPyYOAAAAHHrSF4AAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA+HAAAPhwFgBgucAAAAYUlEQVQoU02OARIAIQgCC///51ugmmNs0lWpNdZCSUh9rI0KKNQ6JF3p1QBCEGlpZtuD8QBCAcMwOToTNfqBHeM8lBVut0MusEVAVgpc298edPrTA+xX+UFPwNuOHiiZ+QDdBgGqhc1kBgAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURYDQEMhMDPyYOAAAAHHrSF4AAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA+HAAAPhwFgBgucAAAAYElEQVQoU12OwQ0AMQjDaNh/5zO46uMQUokLgepfCIrYQjCyDiFARL1kf5OnAWQgScWRpn0BCRpTmqlHMrTb9HmAEW1OBLsAUBd4ArqOIx6FC2rA1hdeICE8fTxntW/3B/mRAbQHIoWLAAAAAElFTkSuQmCC""",
            ],
        ],
    },
    # 5 - Contra
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAkUExURQCQAAAAAJDVAAQEBERQAJI0BPfOw0sk3uLNp7Ozs////3koAAtTo98AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE5SURBVDjLhZNBboNADEX/jHqAcTpECdm4o14EqRdgAXsWzL6LHqGo2y6nN2iO0F6uNiiVSnD6JSOB33wbG+CICbSle3LUaM7zjgzF2KCJ8MEEiARw/GABT8EJQDbQBEIUG9NBiijQOCMbsHsUQCwMeYa/DdyJyS2AY1SgMQEnh/8D4k1AZ42E7VWpgpdsSuaYQhIJUHUG4BeAzQY0z0hEWe+qLQdOHu6lzZT7/ThcA5zAOEwjDVXXde0VAFHA2zRWOW+/BeR7WYCRstUqDq9t33fUlnIsq5hraA+5pX4opS6rmPN4nvqx6vKxvH+WVSwATXmgnooJuH0OoLJRofAMyJW53gR0koBsBOHjfD5fB1gJ9jKty6nyxwHzNrUNNz9YBlP/AuS9LsuDw/zz1qdv1ddlhPUpJM/8A16bqsgS5kkcAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAYUExURQAAAPz8/Ly8vACAiJI0BPfOw0sk3uLNp9C6dMUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADWSURBVDjL5Y8xbsMwDEV/JAdZa+QCCXkBRbyABmn3IO0ZeoQavX5pW06TAAoCBO2SD2h45NcniWe1wT/I3KKt789nGryPuvhyRJlzmu3PUFDSNg+N/m7MGLoYY2gYvsfclfJggdmQ0bbsvkJK0QWR9g4lIA1E4q7rIpXPY8pdLIZUB1kFWRkYy4CEiffWU5VjXxnY6u+5f3SGLhJ7WhhsRfq5tsdv3xPbhUGsg1j6nuUqQFVZDeQxnShOp2iNp6fDeeFLrDivwR90z6vhyG4zHWZu+WB+ANVfMZxWD3i+AAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAbUExURQAAAPz8/HR0dCQYjACoAJI0BPfOw0sk3uLNp/gjMqwAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACoSURBVDjLzZAxEgIhDEX/4LKzpbNHUA6AN6DIAWigpiG1jUeQ8dji2lgQUBv9Mx/C5JFkgqrVoqXTcfcM6mUx9YDV2m6F91rgty0k/T+wxwfSAV/pZXm81RHJi2dwnHMS8kvJSDqE4AXgVrJm7syyARkyslx9jAGenKKWHzOwR0wkEDiXmHVgKFNfDQOFEyLa2Wq4mScS/yuDQz17hhoQGIqcoZ4HgKE7u7NKrjPZ/CcAAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """iVBORw0KGgoAAAANSUhEUgAAAAMAAAAHCAYAAADNufepAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAYSURBVBhXY8APFi5c+B/KRAO4ZSCAgQEABaYFxXJYJA0AAAAASUVORK5CYII=""",
        "NUMBER_IMG_HEIGHT": 7,
        "NUMBER_IMG_WIDTH": 7,
        "NUMBER_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsEAAA7BAbiRa+0AAAAsSURBVBhXY2QAgoULF/4H0cggPj6ekREmAeKARYEAJsYE5uEANJLE49p4RgCeiA7umpx5+AAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAqSURBVBhXY2QAgoULF/4H0TAQHx8PFmdC5qADsCQuQCNJrK4Fgfj4eEYABe0JK0RtiEEAAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAA4SURBVBhXY2QAgoULF/4H0cggPj6ekREmAeKAaGSFTCACJoEOUASRdaFoAElgsxunBNxBmICBAQCdkR5xgSHm8QAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAvSURBVBhXY1y4cOF/BhyAEUrDAbJiuCSyYHx8PFgcTGAzGqQAr7FMBB2E3dh4RgBaLBeRFWmSCAAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAA5SURBVBhXfY3BDQAwCAKLizKbk7aB+DAm9j6iBMQpMvOWNCQREjK0+NqIzRBObmD+6vyTNU1vIYkH5TAS7iOn38IAAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAA2SURBVBhXY1y4cOF/BiwgPj6ekQXKBnOgTDjAqxNDNQjANDCBeTgAE0gVLqPBxmKTjI+PZwQAaKIV0ZieNr4AAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAA0SURBVBhXY2QAgoULF/4H0cggPj6ekRFZAiQAZYI1MEHZGABDJzLAaSxMDKexIIDHtfGMALwVGuybY3eSAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAArSURBVBhXY1y4cOF/BhyABUozxMfHM0KZDDg1gCSwSpIkwQSlsQI8kgwMAGg5GDixoqlUAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAoSURBVBhXY2QAgoULF/4H0cggPj6ekREmAeKAaGSFTFAaK6C/sfGMAFclGc4wUy2XAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA2SURBVBhXY2QAgoULF/4H0cggPj6ekREmAeKAaGSFTFAaK8BpLAiAJZEBirG4dIEAHtfGMwIASO4XkljJtZIAAAAASUVORK5CYII=""",
        ],
        "SPRITE_WIDTH": 4,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": 19,
        "SPRITE_Y_POS": 17,
        "SPRITE_MOVE_SPEED": 5,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # A single bullet
                """iVBORw0KGgoAAAANSUhEUgAAAAMAAAADCAIAAADZSiLoAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsEAAA7BAbiRa+0AAAAfSURBVBhXY5hkwvL//38gyQikGMCAabIpK5CabMoKALJzCSxSzqDMAAAAAElFTkSuQmCC""",
            ],
        ],
    },
    # 6 - Excitebike
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAABGdBTUEAALGOfPtRkwAAACBjSFJNAACHDwAAjA8AAP1SAACBQAAAfXkAAOmLAAA85QAAGcxzPIV3AAAKL2lDQ1BJQ0MgUHJvZmlsZQAASMedlndUVNcWh8+9d3qhzTACUobeu8AA0nuTXkVhmBlgKAMOMzSxIaICEUVEmiJIUMSA0VAkVkSxEBRUsAckCCgxGEVULG9G1ouurLz38vL746xv7bP3ufvsvc9aFwCSpy+XlwZLAZDKE/CDPJzpEZFRdOwAgAEeYIApAExWRrpfsHsIEMnLzYWeIXICXwQB8HpYvAJw09AzgE4H/5+kWel8geiYABGbszkZLBEXiDglS5Auts+KmBqXLGYYJWa+KEERy4k5YZENPvsssqOY2ak8tojFOaezU9li7hXxtkwhR8SIr4gLM7mcLBHfErFGijCVK+I34thUDjMDABRJbBdwWIkiNhExiR8S5CLi5QDgSAlfcdxXLOBkC8SXcklLz+FzExIFdB2WLt3U2ppB9+RkpXAEAsMAJiuZyWfTXdJS05m8HAAW7/xZMuLa0kVFtjS1trQ0NDMy/apQ/3Xzb0rc20V6Gfi5ZxCt/4vtr/zSGgBgzIlqs/OLLa4KgM4tAMjd+2LTOACApKhvHde/ug9NPC+JAkG6jbFxVlaWEZfDMhIX9A/9T4e/oa++ZyQ+7o/y0F058UxhioAurhsrLSVNyKdnpDNZHLrhn4f4Hwf+dR4GQZx4Dp/DE0WEiaaMy0sQtZvH5gq4aTw6l/efmvgPw/6kxbkWidL4EVBjjIDUdSpAfu0HKAoRINH7xV3/o2+++DAgfnnhKpOLc//vN/1nwaXiJYOb8DnOJSiEzhLyMxf3xM8SoAEBSAIqkAfKQB3oAENgBqyALXAEbsAb+IMQEAlWAxZIBKmAD7JAHtgECkEx2An2gGpQBxpBM2gFx0EnOAXOg0vgGrgBboP7YBRMgGdgFrwGCxAEYSEyRIHkIRVIE9KHzCAGZA+5Qb5QEBQJxUIJEA8SQnnQZqgYKoOqoXqoGfoeOgmdh65Ag9BdaAyahn6H3sEITIKpsBKsBRvDDNgJ9oFD4FVwArwGzoUL4B1wJdwAH4U74PPwNfg2PAo/g+cQgBARGqKKGCIMxAXxR6KQeISPrEeKkAqkAWlFupE+5CYyiswgb1EYFAVFRxmibFGeqFAUC7UGtR5VgqpGHUZ1oHpRN1FjqFnURzQZrYjWR9ugvdAR6AR0FroQXYFuQrejL6JvoyfQrzEYDA2jjbHCeGIiMUmYtZgSzD5MG+YcZhAzjpnDYrHyWH2sHdYfy8QKsIXYKuxR7FnsEHYC+wZHxKngzHDuuCgcD5ePq8AdwZ3BDeEmcQt4Kbwm3gbvj2fjc/Cl+EZ8N/46fgK/QJAmaBPsCCGEJMImQiWhlXCR8IDwkkgkqhGtiYFELnEjsZJ4jHiZOEZ8S5Ih6ZFcSNEkIWkH6RDpHOku6SWZTNYiO5KjyALyDnIz+QL5EfmNBEXCSMJLgi2xQaJGokNiSOK5JF5SU9JJcrVkrmSF5AnJ65IzUngpLSkXKabUeqkaqZNSI1Jz0hRpU2l/6VTpEukj0lekp2SwMloybjJsmQKZgzIXZMYpCEWd4kJhUTZTGikXKRNUDFWb6kVNohZTv6MOUGdlZWSXyYbJZsvWyJ6WHaUhNC2aFy2FVko7ThumvVuitMRpCWfJ9iWtS4aWzMstlXOU48gVybXJ3ZZ7J0+Xd5NPlt8l3yn/UAGloKcQqJClsF/hosLMUupS26WspUVLjy+9pwgr6ikGKa5VPKjYrzinpKzkoZSuVKV0QWlGmabsqJykXK58RnlahaJir8JVKVc5q/KULkt3oqfQK+m99FlVRVVPVaFqveqA6oKatlqoWr5am9pDdYI6Qz1evVy9R31WQ0XDTyNPo0XjniZek6GZqLlXs09zXktbK1xrq1an1pS2nLaXdq52i/YDHbKOg84anQadW7oYXYZusu4+3Rt6sJ6FXqJejd51fVjfUp+rv09/0ABtYG3AM2gwGDEkGToZZhq2GI4Z0Yx8jfKNOo2eG2sYRxnvMu4z/mhiYZJi0mhy31TG1Ns037Tb9HczPTOWWY3ZLXOyubv5BvMu8xfL9Jdxlu1fdseCYuFnsdWix+KDpZUl37LVctpKwyrWqtZqhEFlBDBKGJet0dbO1husT1m/tbG0Edgct/nN1tA22faI7dRy7eWc5Y3Lx+3U7Jh29Xaj9nT7WPsD9qMOqg5MhwaHx47qjmzHJsdJJ12nJKejTs+dTZz5zu3O8y42Lutczrkirh6uRa4DbjJuoW7Vbo/c1dwT3FvcZz0sPNZ6nPNEe/p47vIc8VLyYnk1e816W3mv8+71IfkE+1T7PPbV8+X7dvvBft5+u/0erNBcwVvR6Q/8vfx3+z8M0A5YE/BjICYwILAm8EmQaVBeUF8wJTgm+Ejw6xDnkNKQ+6E6ocLQnjDJsOiw5rD5cNfwsvDRCOOIdRHXIhUiuZFdUdiosKimqLmVbiv3rJyItogujB5epb0qe9WV1QqrU1afjpGMYcaciEXHhsceiX3P9Gc2MOfivOJq42ZZLqy9rGdsR3Y5e5pjxynjTMbbxZfFTyXYJexOmE50SKxInOG6cKu5L5I8k+qS5pP9kw8lf0oJT2lLxaXGpp7kyfCSeb1pymnZaYPp+umF6aNrbNbsWTPL9+E3ZUAZqzK6BFTRz1S/UEe4RTiWaZ9Zk/kmKyzrRLZ0Ni+7P0cvZ3vOZK577rdrUWtZa3vyVPM25Y2tc1pXvx5aH7e+Z4P6hoINExs9Nh7eRNiUvOmnfJP8svxXm8M3dxcoFWwsGN/isaWlUKKQXziy1XZr3TbUNu62ge3m26u2fyxiF10tNimuKH5fwiq5+o3pN5XffNoRv2Og1LJ0/07MTt7O4V0Ouw6XSZfllo3v9tvdUU4vLyp/tSdmz5WKZRV1ewl7hXtHK30ru6o0qnZWva9OrL5d41zTVqtYu712fh9739B+x/2tdUp1xXXvDnAP3Kn3qO9o0GqoOIg5mHnwSWNYY9+3jG+bmxSaips+HOIdGj0cdLi32aq5+YjikdIWuEXYMn00+uiN71y/62o1bK1vo7UVHwPHhMeefh/7/fBxn+M9JxgnWn/Q/KG2ndJe1AF15HTMdiZ2jnZFdg2e9D7Z023b3f6j0Y+HTqmeqjkte7r0DOFMwZlPZ3PPzp1LPzdzPuH8eE9Mz/0LERdu9Qb2Dlz0uXj5kvulC31OfWcv210+dcXmysmrjKud1yyvdfRb9Lf/ZPFT+4DlQMd1q+tdN6xvdA8uHzwz5DB0/qbrzUu3vG5du73i9uBw6PCdkeiR0TvsO1N3U+6+uJd5b+H+xgfoB0UPpR5WPFJ81PCz7s9to5ajp8dcx/ofBz++P84af/ZLxi/vJwqekJ9UTKpMNk+ZTZ2adp++8XTl04ln6c8WZgp/lf619rnO8x9+c/ytfzZiduIF/8Wn30teyr889GrZq565gLlHr1NfL8wXvZF/c/gt423fu/B3kwtZ77HvKz/ofuj+6PPxwafUT5/+BQOY8/xvJtwPAAAADFBMVEWM1gT/zsbnmyFrawBAGQdHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAVElEQVQ4y2MYGkBQUBCvFCOQFMAuD5FiEhJUxKEAIsWkrGSESwFYihlIKmBXAJFiNlYyMsChACzFbGxsjFMBSIqgghEClAiAUQVUUwBMmMq4sZEyAL0NPJXbDeuKAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAABGdBTUEAALGOfPtRkwAAACBjSFJNAACHDwAAjA8AAP1SAACBQAAAfXkAAOmLAAA85QAAGcxzPIV3AAAKL2lDQ1BJQ0MgUHJvZmlsZQAASMedlndUVNcWh8+9d3qhzTACUobeu8AA0nuTXkVhmBlgKAMOMzSxIaICEUVEmiJIUMSA0VAkVkSxEBRUsAckCCgxGEVULG9G1ouurLz38vL746xv7bP3ufvsvc9aFwCSpy+XlwZLAZDKE/CDPJzpEZFRdOwAgAEeYIApAExWRrpfsHsIEMnLzYWeIXICXwQB8HpYvAJw09AzgE4H/5+kWel8geiYABGbszkZLBEXiDglS5Auts+KmBqXLGYYJWa+KEERy4k5YZENPvsssqOY2ak8tojFOaezU9li7hXxtkwhR8SIr4gLM7mcLBHfErFGijCVK+I34thUDjMDABRJbBdwWIkiNhExiR8S5CLi5QDgSAlfcdxXLOBkC8SXcklLz+FzExIFdB2WLt3U2ppB9+RkpXAEAsMAJiuZyWfTXdJS05m8HAAW7/xZMuLa0kVFtjS1trQ0NDMy/apQ/3Xzb0rc20V6Gfi5ZxCt/4vtr/zSGgBgzIlqs/OLLa4KgM4tAMjd+2LTOACApKhvHde/ug9NPC+JAkG6jbFxVlaWEZfDMhIX9A/9T4e/oa++ZyQ+7o/y0F058UxhioAurhsrLSVNyKdnpDNZHLrhn4f4Hwf+dR4GQZx4Dp/DE0WEiaaMy0sQtZvH5gq4aTw6l/efmvgPw/6kxbkWidL4EVBjjIDUdSpAfu0HKAoRINH7xV3/o2+++DAgfnnhKpOLc//vN/1nwaXiJYOb8DnOJSiEzhLyMxf3xM8SoAEBSAIqkAfKQB3oAENgBqyALXAEbsAb+IMQEAlWAxZIBKmAD7JAHtgECkEx2An2gGpQBxpBM2gFx0EnOAXOg0vgGrgBboP7YBRMgGdgFrwGCxAEYSEyRIHkIRVIE9KHzCAGZA+5Qb5QEBQJxUIJEA8SQnnQZqgYKoOqoXqoGfoeOgmdh65Ag9BdaAyahn6H3sEITIKpsBKsBRvDDNgJ9oFD4FVwArwGzoUL4B1wJdwAH4U74PPwNfg2PAo/g+cQgBARGqKKGCIMxAXxR6KQeISPrEeKkAqkAWlFupE+5CYyiswgb1EYFAVFRxmibFGeqFAUC7UGtR5VgqpGHUZ1oHpRN1FjqFnURzQZrYjWR9ugvdAR6AR0FroQXYFuQrejL6JvoyfQrzEYDA2jjbHCeGIiMUmYtZgSzD5MG+YcZhAzjpnDYrHyWH2sHdYfy8QKsIXYKuxR7FnsEHYC+wZHxKngzHDuuCgcD5ePq8AdwZ3BDeEmcQt4Kbwm3gbvj2fjc/Cl+EZ8N/46fgK/QJAmaBPsCCGEJMImQiWhlXCR8IDwkkgkqhGtiYFELnEjsZJ4jHiZOEZ8S5Ih6ZFcSNEkIWkH6RDpHOku6SWZTNYiO5KjyALyDnIz+QL5EfmNBEXCSMJLgi2xQaJGokNiSOK5JF5SU9JJcrVkrmSF5AnJ65IzUngpLSkXKabUeqkaqZNSI1Jz0hRpU2l/6VTpEukj0lekp2SwMloybjJsmQKZgzIXZMYpCEWd4kJhUTZTGikXKRNUDFWb6kVNohZTv6MOUGdlZWSXyYbJZsvWyJ6WHaUhNC2aFy2FVko7ThumvVuitMRpCWfJ9iWtS4aWzMstlXOU48gVybXJ3ZZ7J0+Xd5NPlt8l3yn/UAGloKcQqJClsF/hosLMUupS26WspUVLjy+9pwgr6ikGKa5VPKjYrzinpKzkoZSuVKV0QWlGmabsqJykXK58RnlahaJir8JVKVc5q/KULkt3oqfQK+m99FlVRVVPVaFqveqA6oKatlqoWr5am9pDdYI6Qz1evVy9R31WQ0XDTyNPo0XjniZek6GZqLlXs09zXktbK1xrq1an1pS2nLaXdq52i/YDHbKOg84anQadW7oYXYZusu4+3Rt6sJ6FXqJejd51fVjfUp+rv09/0ABtYG3AM2gwGDEkGToZZhq2GI4Z0Yx8jfKNOo2eG2sYRxnvMu4z/mhiYZJi0mhy31TG1Ns037Tb9HczPTOWWY3ZLXOyubv5BvMu8xfL9Jdxlu1fdseCYuFnsdWix+KDpZUl37LVctpKwyrWqtZqhEFlBDBKGJet0dbO1husT1m/tbG0Edgct/nN1tA22faI7dRy7eWc5Y3Lx+3U7Jh29Xaj9nT7WPsD9qMOqg5MhwaHx47qjmzHJsdJJ12nJKejTs+dTZz5zu3O8y42Lutczrkirh6uRa4DbjJuoW7Vbo/c1dwT3FvcZz0sPNZ6nPNEe/p47vIc8VLyYnk1e816W3mv8+71IfkE+1T7PPbV8+X7dvvBft5+u/0erNBcwVvR6Q/8vfx3+z8M0A5YE/BjICYwILAm8EmQaVBeUF8wJTgm+Ejw6xDnkNKQ+6E6ocLQnjDJsOiw5rD5cNfwsvDRCOOIdRHXIhUiuZFdUdiosKimqLmVbiv3rJyItogujB5epb0qe9WV1QqrU1afjpGMYcaciEXHhsceiX3P9Gc2MOfivOJq42ZZLqy9rGdsR3Y5e5pjxynjTMbbxZfFTyXYJexOmE50SKxInOG6cKu5L5I8k+qS5pP9kw8lf0oJT2lLxaXGpp7kyfCSeb1pymnZaYPp+umF6aNrbNbsWTPL9+E3ZUAZqzK6BFTRz1S/UEe4RTiWaZ9Zk/kmKyzrRLZ0Ni+7P0cvZ3vOZK577rdrUWtZa3vyVPM25Y2tc1pXvx5aH7e+Z4P6hoINExs9Nh7eRNiUvOmnfJP8svxXm8M3dxcoFWwsGN/isaWlUKKQXziy1XZr3TbUNu62ge3m26u2fyxiF10tNimuKH5fwiq5+o3pN5XffNoRv2Og1LJ0/07MTt7O4V0Ouw6XSZfllo3v9tvdUU4vLyp/tSdmz5WKZRV1ewl7hXtHK30ru6o0qnZWva9OrL5d41zTVqtYu712fh9739B+x/2tdUp1xXXvDnAP3Kn3qO9o0GqoOIg5mHnwSWNYY9+3jG+bmxSaips+HOIdGj0cdLi32aq5+YjikdIWuEXYMn00+uiN71y/62o1bK1vo7UVHwPHhMeefh/7/fBxn+M9JxgnWn/Q/KG2ndJe1AF15HTMdiZ2jnZFdg2e9D7Z023b3f6j0Y+HTqmeqjkte7r0DOFMwZlPZ3PPzp1LPzdzPuH8eE9Mz/0LERdu9Qb2Dlz0uXj5kvulC31OfWcv210+dcXmysmrjKud1yyvdfRb9Lf/ZPFT+4DlQMd1q+tdN6xvdA8uHzwz5DB0/qbrzUu3vG5du73i9uBw6PCdkeiR0TvsO1N3U+6+uJd5b+H+xgfoB0UPpR5WPFJ81PCz7s9to5ajp8dcx/ofBz++P84af/ZLxi/vJwqekJ9UTKpMNk+ZTZ2adp++8XTl04ln6c8WZgp/lf619rnO8x9+c/ytfzZiduIF/8Wn30teyr889GrZq565gLlHr1NfL8wXvZF/c/gt423fu/B3kwtZ77HvKz/ofuj+6PPxwafUT5/+BQOY8/xvJtwPAAAAD1BMVEUdH4zO8pSO2gA+hgD///9kzFd8AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAV0lEQVQ4y2MYGkBQUBCvFCOQFMAuD5FiEhJUxKEAIsWkrGSESwFYihlIKmBXAJFiNlYyMsChACzFbGxsjFMBSIqgghEClAiAUQVUU2BkrKSMip2Q2ErKAL9FPLVJi9TlAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAABGdBTUEAALGOfPtRkwAAACBjSFJNAACHDwAAjA8AAP1SAACBQAAAfXkAAOmLAAA85QAAGcxzPIV3AAAKL2lDQ1BJQ0MgUHJvZmlsZQAASMedlndUVNcWh8+9d3qhzTACUobeu8AA0nuTXkVhmBlgKAMOMzSxIaICEUVEmiJIUMSA0VAkVkSxEBRUsAckCCgxGEVULG9G1ouurLz38vL746xv7bP3ufvsvc9aFwCSpy+XlwZLAZDKE/CDPJzpEZFRdOwAgAEeYIApAExWRrpfsHsIEMnLzYWeIXICXwQB8HpYvAJw09AzgE4H/5+kWel8geiYABGbszkZLBEXiDglS5Auts+KmBqXLGYYJWa+KEERy4k5YZENPvsssqOY2ak8tojFOaezU9li7hXxtkwhR8SIr4gLM7mcLBHfErFGijCVK+I34thUDjMDABRJbBdwWIkiNhExiR8S5CLi5QDgSAlfcdxXLOBkC8SXcklLz+FzExIFdB2WLt3U2ppB9+RkpXAEAsMAJiuZyWfTXdJS05m8HAAW7/xZMuLa0kVFtjS1trQ0NDMy/apQ/3Xzb0rc20V6Gfi5ZxCt/4vtr/zSGgBgzIlqs/OLLa4KgM4tAMjd+2LTOACApKhvHde/ug9NPC+JAkG6jbFxVlaWEZfDMhIX9A/9T4e/oa++ZyQ+7o/y0F058UxhioAurhsrLSVNyKdnpDNZHLrhn4f4Hwf+dR4GQZx4Dp/DE0WEiaaMy0sQtZvH5gq4aTw6l/efmvgPw/6kxbkWidL4EVBjjIDUdSpAfu0HKAoRINH7xV3/o2+++DAgfnnhKpOLc//vN/1nwaXiJYOb8DnOJSiEzhLyMxf3xM8SoAEBSAIqkAfKQB3oAENgBqyALXAEbsAb+IMQEAlWAxZIBKmAD7JAHtgECkEx2An2gGpQBxpBM2gFx0EnOAXOg0vgGrgBboP7YBRMgGdgFrwGCxAEYSEyRIHkIRVIE9KHzCAGZA+5Qb5QEBQJxUIJEA8SQnnQZqgYKoOqoXqoGfoeOgmdh65Ag9BdaAyahn6H3sEITIKpsBKsBRvDDNgJ9oFD4FVwArwGzoUL4B1wJdwAH4U74PPwNfg2PAo/g+cQgBARGqKKGCIMxAXxR6KQeISPrEeKkAqkAWlFupE+5CYyiswgb1EYFAVFRxmibFGeqFAUC7UGtR5VgqpGHUZ1oHpRN1FjqFnURzQZrYjWR9ugvdAR6AR0FroQXYFuQrejL6JvoyfQrzEYDA2jjbHCeGIiMUmYtZgSzD5MG+YcZhAzjpnDYrHyWH2sHdYfy8QKsIXYKuxR7FnsEHYC+wZHxKngzHDuuCgcD5ePq8AdwZ3BDeEmcQt4Kbwm3gbvj2fjc/Cl+EZ8N/46fgK/QJAmaBPsCCGEJMImQiWhlXCR8IDwkkgkqhGtiYFELnEjsZJ4jHiZOEZ8S5Ih6ZFcSNEkIWkH6RDpHOku6SWZTNYiO5KjyALyDnIz+QL5EfmNBEXCSMJLgi2xQaJGokNiSOK5JF5SU9JJcrVkrmSF5AnJ65IzUngpLSkXKabUeqkaqZNSI1Jz0hRpU2l/6VTpEukj0lekp2SwMloybjJsmQKZgzIXZMYpCEWd4kJhUTZTGikXKRNUDFWb6kVNohZTv6MOUGdlZWSXyYbJZsvWyJ6WHaUhNC2aFy2FVko7ThumvVuitMRpCWfJ9iWtS4aWzMstlXOU48gVybXJ3ZZ7J0+Xd5NPlt8l3yn/UAGloKcQqJClsF/hosLMUupS26WspUVLjy+9pwgr6ikGKa5VPKjYrzinpKzkoZSuVKV0QWlGmabsqJykXK58RnlahaJir8JVKVc5q/KULkt3oqfQK+m99FlVRVVPVaFqveqA6oKatlqoWr5am9pDdYI6Qz1evVy9R31WQ0XDTyNPo0XjniZek6GZqLlXs09zXktbK1xrq1an1pS2nLaXdq52i/YDHbKOg84anQadW7oYXYZusu4+3Rt6sJ6FXqJejd51fVjfUp+rv09/0ABtYG3AM2gwGDEkGToZZhq2GI4Z0Yx8jfKNOo2eG2sYRxnvMu4z/mhiYZJi0mhy31TG1Ns037Tb9HczPTOWWY3ZLXOyubv5BvMu8xfL9Jdxlu1fdseCYuFnsdWix+KDpZUl37LVctpKwyrWqtZqhEFlBDBKGJet0dbO1husT1m/tbG0Edgct/nN1tA22faI7dRy7eWc5Y3Lx+3U7Jh29Xaj9nT7WPsD9qMOqg5MhwaHx47qjmzHJsdJJ12nJKejTs+dTZz5zu3O8y42Lutczrkirh6uRa4DbjJuoW7Vbo/c1dwT3FvcZz0sPNZ6nPNEe/p47vIc8VLyYnk1e816W3mv8+71IfkE+1T7PPbV8+X7dvvBft5+u/0erNBcwVvR6Q/8vfx3+z8M0A5YE/BjICYwILAm8EmQaVBeUF8wJTgm+Ejw6xDnkNKQ+6E6ocLQnjDJsOiw5rD5cNfwsvDRCOOIdRHXIhUiuZFdUdiosKimqLmVbiv3rJyItogujB5epb0qe9WV1QqrU1afjpGMYcaciEXHhsceiX3P9Gc2MOfivOJq42ZZLqy9rGdsR3Y5e5pjxynjTMbbxZfFTyXYJexOmE50SKxInOG6cKu5L5I8k+qS5pP9kw8lf0oJT2lLxaXGpp7kyfCSeb1pymnZaYPp+umF6aNrbNbsWTPL9+E3ZUAZqzK6BFTRz1S/UEe4RTiWaZ9Zk/kmKyzrRLZ0Ni+7P0cvZ3vOZK577rdrUWtZa3vyVPM25Y2tc1pXvx5aH7e+Z4P6hoINExs9Nh7eRNiUvOmnfJP8svxXm8M3dxcoFWwsGN/isaWlUKKQXziy1XZr3TbUNu62ge3m26u2fyxiF10tNimuKH5fwiq5+o3pN5XffNoRv2Og1LJ0/07MTt7O4V0Ouw6XSZfllo3v9tvdUU4vLyp/tSdmz5WKZRV1ewl7hXtHK30ru6o0qnZWva9OrL5d41zTVqtYu712fh9739B+x/2tdUp1xXXvDnAP3Kn3qO9o0GqoOIg5mHnwSWNYY9+3jG+bmxSaips+HOIdGj0cdLi32aq5+YjikdIWuEXYMn00+uiN71y/62o1bK1vo7UVHwPHhMeefh/7/fBxn+M9JxgnWn/Q/KG2ndJe1AF15HTMdiZ2jnZFdg2e9D7Z023b3f6j0Y+HTqmeqjkte7r0DOFMwZlPZ3PPzp1LPzdzPuH8eE9Mz/0LERdu9Qb2Dlz0uXj5kvulC31OfWcv210+dcXmysmrjKud1yyvdfRb9Lf/ZPFT+4DlQMd1q+tdN6xvdA8uHzwz5DB0/qbrzUu3vG5du73i9uBw6PCdkeiR0TvsO1N3U+6+uJd5b+H+xgfoB0UPpR5WPFJ81PCz7s9to5ajp8dcx/ofBz++P84af/ZLxi/vJwqekJ9UTKpMNk+ZTZ2adp++8XTl04ln6c8WZgp/lf619rnO8x9+c/ytfzZiduIF/8Wn30teyr889GrZq565gLlHr1NfL8wXvZF/c/gt423fu/B3kwtZ77HvKz/ofuj+6PPxwafUT5/+BQOY8/xvJtwPAAAAD1BMVEW5wApl6y0klwAAAAD///+3aSBzAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAV0lEQVQ4y2MYGkBQUBCvFCOQFMAuD5FiEhJUxKEAIsWkrGSESwFYihlIKmBXAJFiNlYyMsChACzFbGxsjFMBSIqgghEClAiAUQVUU2BkrKSMip2Q2ErKAL9FPLVJi9TlAAAAAElFTkSuQmCC""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 20,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": -50,
        "SPRITE_Y_POS": 6,
        "SPRITE_MOVE_SPEED": 5,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                """iVBORw0KGgoAAAANSUhEUgAAABQAAAAVCAMAAABxCz6aAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURf///9srAAUFBQAAAGUxTVgAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAi0lEQVQoU1WQARKAMAjDBvz/zzYFpnKe0AzK9NTEUUxZW8BOrNgMi6ELBTJzxLczr5icEfAWm15DRUONqtMlMTDpVG+vuhCa8YfeLJeWvqKUqLI9plPIBr5TAFObAzojdOptSKdc0T6BcYBNe+nN3oa0lqF/hmAfG6roXXxQCxvDmAXw2FjS06ZZ9QD/WQNdfW6GNAAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABQAAAAVCAMAAABxCz6aAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURf///9srAAUFBQAAAGUxTVgAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAiUlEQVQoU1WPQQLEIAgDBf7/550k2G05CBlj1DNbh9px7iB26orbxWrphYDuXvF29iO2d5V4xG3/QCqQozg9qha2nHhz1QNFu77QN5MS6SeioHRnrBPkAL+pBJubS3SPyMlqKCep0t6R0oZiksWqewNlHUN/GphtQ4bN5UMRDvbsL0Y42CyFmPkBAYwDbBAMK70AAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABQAAAAVCAMAAABxCz6aAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURf///9srAAUFBQAAAGUxTVgAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAiElEQVQoU22QAQ7DMAgDA/z/z/MZyDa1SClwMibpqYmjmLK2gJ3YZjMshi4UyMxpfpV5m8kZAe9m09dQ0VCjUrokBqaUr/AxnqZRfamZaZrxBzE47OtmH9O77GGlkCBX5VkVQCXsfOQhB38EGExtN/VBAaRm1Ep8BfeaQFX+kzfzC9lthYK66gMX2AOBspiuKQAAAABJRU5ErkJggg==""",
            ],
        ],
    },
    # 7 - Little Nemo
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQAAAC1zAP6TCKpEAFj4m+AAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB+SURBVDjL7Y3BDcQgDARZXQN2C3YD0dJ/b1mTBJS7T74nxQiYtUfQ3nrrX8t+ALc5rtGEOi8H1nx0JujCTRjJFkgo058Kbq6J+QI4lACbQm0skGC1T2FwvTzhcI8von8iYmNELtCxKaVSi6BWRp7Xd269Z2YnmQIKlJKC0SZ3n1AT1Yqi3sYAAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAYUExURUQAnPx0tPz8/ACUAEzcSPzYqIhwAAAAAH/wwpwAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADHSURBVDjLtZBRDsMgCIZp2QGWnmDpCUjwAE3cFfAGuhvs/AN9mrPy0Iw0CL9fAQHHNg9YnPsH/N9W5373gG2Bi7beHWD3FrHDNUNzNAF4DjAQmjsvQIRIrc8JYCVmgP6vU8QZYAP4AI67tO4U2jEAuE6J2iAeA8B2YPpNPw5HX4HqDkwPBE/G0D0Vqe1AdUaIDD8A1x2YHhgiAXdP5QqA6RpyG3UEqM4BpIikkt5J5KWR9DlI1jDlLOZFjy4HhSypVqzCV57kAyvTMzpClI19AAAAAElFTkSuQmCC""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 20,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": -50,
        "SPRITE_Y_POS": 5,
        "SPRITE_MOVE_SPEED": 3,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Nemo
                """iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQAAAIAA8Py8sPz8/AAAAM1PdRMAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAKxJREFUKFNdjwEWwyAMQqPx/mcefOLajWeVQoixzoMS1vBzjVq1QI3yGF+MkH00MBL7dTZ7FF8ZfQtri8co/RaVOksL+TFcbLJ/jfa+t46WQYo7Wh+OcRKT0hSS9Gdmg4RxVTMMRbu9ElIJA9gwdYZARXcrOtx2nsN6DNXEsI78bwjm9w4Rpgnm+dPQI42RDjFcwwR5hXUMajp1fkyKJ8BNCNGnVXgw/C29cM4H7AMFRGccYu0AAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQAAAIAA8Py8sPz8/AAAAM1PdRMAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAKpJREFUKFNlkAsSxCAIQxG8/5k3CUTtbKb1kycNNvZVQGvW2yBWLCnGueBojB7Hk8bSaJIa22Fk+wmtxLpBZGXoZCY2zgaoqii4rAg8B7Ci4ECY6gBmADWhDHCIISJ6DVgBn59hun1fEB1M0feXIL0R4Vga1A/7vg03oMcbsb+/Chztz8l3Bn3eE0UyDFikAjAbnvXTmG7Ds7o6CReIPP4L7q2p54gam83eP2z5BdDYSN8aAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQAAAIAA8Py8sPz8/AAAAM1PdRMAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAKhJREFUKFNtkAkSwzAIA/Hx/zdXK8Cup9VkMNFiIIl9FdKofDeIEcOKci44KiNjeVZZjk2mYzqMTH9KYypPEHoNV+oMPbYvoJhkvmAR59SxDmDGokmrgYrkJ+F4btCB/s+MjNyjQKBIH0tAPX+ASV2qJo46awlREX5GAxayb94dVaD2dqW7A7uW5/WYAyCxzdyez+Mvw/Z17hMN8vttS04Mj/Wlf5609wdLsgWgK7Ip9AAAAABJRU5ErkJggg==""",
            ],
        ],
    },
    # 8 - DuckTales
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJUExURf///6DZ/h+l/hset/UAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABcSURBVDjL7ZPBDQAhCASXDlg7gP6LPJB4lxgvNsA+fDATf4N3wpivkR/RYsO3WUnkka5/CP7SUsCLAb+shRZaOAkmXm1lqpI3w7AZOjXjjetsWKt1Bs/iI/l4gAeVIH107coj+AAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURRg8XABw7AAAAACoAPz8/PWBHj8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAABaSURBVDjLY2BgEARiJQasQMHYhIACIyVCCoxprYCJWZnWCoCOoFQBEzMhBQwEFDAo4FegpEQwLkwoVDA4QpKBYTQcGIgLB2MkYGSMCkB8Bhck4OSCCpxcXFwAn5Ud2CRAzuoAAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 23,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": -56,
        "SPRITE_Y_POS": 1,
        "SPRITE_MOVE_SPEED": 5,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Scrooge McDuck
                """iVBORw0KGgoAAAANSUhEUgAAABcAAAAeCAMAAADw+3VaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURQAAAPz8/NgoAKjk/PyYOAAAAAWmpAwAAAAGdFJOU///////ALO/pL8AAAAJcEhZcwAAFiMAABYjAclRYGsAAADOSURBVChTbZBbFsUgCANB6f63fDOB9vRx86E4QRDj+K8nD8uRzyNgtnHn4EgZxI0scy4QN7Karw+3sdb6cBnKbg1BPqcaZ9zzG++dufPNhWXs/e4rxEtfXLWHq8Mpl5ERUVEX5+H8QVXlrqsO48zT5UjmntIGv9kC6yR2XiDPdTrL+V7Ov5aB40q5tN95NldBtn4PZcjBcRMhcHkid6GlmTGVRgzgfGMlJdOoTQ/Fb2DBjGZYsBbHTsqckGXeS4Y6OPBCOwJuTjCn6+ztOH5fpQeFPHimPAAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABcAAAAeCAMAAADw+3VaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURQAAAPz8/NgoAKjk/PyYOAAAAAWmpAwAAAAGdFJOU///////ALO/pL8AAAAJcEhZcwAAFiMAABYjAclRYGsAAAC8SURBVChTZZBLAsQgCENB8f5XnnywOm0WVl4MFWMdhdR7fyjC3MbhxJEwXGmlxBlwpZUyHx8uY4zx4Z2gbi6Q+HGSPdx4zsyZLE3NgWHMydKUEudNXxy9m6PRfZ5GREVdnN0zqipnnT4ciD/GaUkcFcdk5y1y5skdUBw6nEs/DsQI8mJj6Akk8Q5gvbkDch/cnDf5chq+o5BkXhj+D5tjtAq++lFzntduq/u8sTibnIksn896G670vJex1g+7/Qi2ZSrEaAAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABcAAAAeCAMAAADw+3VaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURQAAAPz8/NgoAKjk/PyYOAAAAAWmpAwAAAAGdFJOU///////ALO/pL8AAAAJcEhZcwAAFiQAABYkAZsVxhQAAADESURBVChTbZLRFoAgCENB8f9/uW1gYcUD4d1E9GTrPw5uiiyVMwi9hMaJzSFoIaQQ5wYthBTJx4dLGGN8OAS4FT/nOo7o/sRzuk9/c2AIc3ZOBYiTvjh6F/fTT8EsLDqH0S0ifEbrc48OBZEcS96TrSvE2QBcSj3DybPVzSHQlwI8jW/h5NxAgTPp0fZ7wrVHCbAInUIHBAYvyyuQo+J1Hu7F8UVFSotk9EBR/XJrcTxe/RrCTDkSOz92JmV+2T4FJVtrXccJB7OYXbz4AAAAAElFTkSuQmCC""",
            ],
        ],
    },
    # 9 - Bubble Bobble
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJUExURQAAAP5l9v68+4NhtBUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABISURBVDjL7Y7BDQAgCAO7Amxg9x9SjREhyAb0QXLlEkCn08kRJUXIsYcsGodujUAfCbYrJByqJTzyklqNQB8J8WaWkB/zEjkBQ6MZgd/hDsMAAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQAAAAQCBLQyJPzOxPyCdNtELoYAAAAJcEhZcwAADsIAAA7CARUoSoAAAABBSURBVDjL7c1BDQAhEEPRaiAYmKEKNigo+NcEd7JVMD9554+qqt7aZDgYJB1QKQfKmQ74SQ647smA7sdBzx3/dhxYKi1JnjZ6ngAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQAAAPTapKQazPyCdKyPcJQAAAAJcEhZcwAADsIAAA7CARUoSoAAAAA6SURBVDjL7c5BDQBACAPBWmhwAAoA/94QcLligEn2SQPOOS+6UwWrSBV6AX1vBf0BfV+w7lSBFfwXHKLeJCGBXtgfAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQAAAMzulIzaBAxKBMdzHEgAAAAJcEhZcwAADsEAAA7BAbiRa+0AAAA8SURBVDjL7c3BCQAwDEJRVzDZwA1a99+tuRecIB8e5CAE27b9laQEJDsBbSfgKSczkBPwzhGg508Cx+wHxYAksWuGyw4AAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAbSURBVBhXYyAOxDwz+Q/CIDYTWIQgIEULAwMAm3YJ2XpE6oQAAAAASUVORK5CYII=""",
        "NUMBER_IMG_HEIGHT": 8,
        "NUMBER_IMG_WIDTH": 4,
        "NUMBER_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAjSURBVBhXYwCBmGcm/0EYzgEzgADEZoKy4YAaAmCAsJaBAQC7GA7JU/TE3gAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAApSURBVBhXY4CBmGcm/0E0EzIHBJiQOSDAtETqDCOUDQZgLciAZAEGBgC/wQj5xge3XQAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAxSURBVBhXY4x5ZvKfAQqWSJ1hZISyGWASTGAeEsAQAAOQcrhZKBwgwNCCYi0DAwMDADqPEshqm7PpAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAqSURBVBhXY4x5ZvKfAQqWSJ1hZISyGWASTGAeOgDJwlQQ1oIhgGbtGUYAO/IR3wmZgMgAAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAwSURBVBhXY2SAgphnJv9BNFgAxgEBJigNB0wg2SVSZ+BaMVQwIusHAQxb0LQwMAAAP0wN4Rgdud8AAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAxSURBVBhXY4x5ZvKfAQmwQGmGJVJnGEE0E5iHBOACMK1gZSAAE8CtBQZQrF0idYYRAF+UDPrJmuh0AAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAxSURBVBhXY2QAgphnJv9BNBiAOMgCTFAaDuACMFVggSVSZ+Bm4dYCA4zINiyROsMIADNfEeF+nSdjAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAkSURBVBhXY4x5ZvKfAQkwQmkGmAQTmIcNoKhANgdDCyEBBgYAoigJ4YbxWf0AAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAArSURBVBhXY4x5ZvKfAQqWSJ1hZIIxQDRIEiyADFC0gACKFhDA0ELIDAYGAAMfDoNMDMvcAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAxSURBVBhXY2QAgphnJv9BNAgwwThLpM6AJZlABDLAEMAwAywAAjBBTC3IypdInWEEACibD2wJSVQzAAAAAElFTkSuQmCC""",
        ],
        "SPRITE_WIDTH": 16,
        "DIST_BETWEEN_SPRITES": 5,
        "SPRITE_MIN_X": -37,
        "SPRITE_Y_POS": 8,
        "SPRITE_MOVE_SPEED": 2,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Bub
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURfyCdFzmNPz+/AQCBAAAAJpX5XIAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAFxJREFUKFNdjgEKwDAIA2Ps/988Y3QbFUrN4Yk4U9u8P6bTVwGhWlCkcxMPKpDBIgUskBlJT7TwB2MIhJULWPFSgxOFMpP1GsQepkM+wCr5WrFZBLMSWNBRkgiAB1FZAjQDo4idAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURfyCdFzmNPz+/AQCBAAAAJpX5XIAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAF5JREFUKFNdjwEOwDAIAhH7/zcPpC7LTIxyEWtxbmzzVtzORQLlWCAyekgGLciiiEAMZFczE2P4guswqFh+IJYsDTgl1N1UDqg9zIdAGUDF+CVWm2DeLLEXDPH/pAE8T7MCMXnmUzIAAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAMAAAD+iNU2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURfyCdFzmNPz+/AQCBAAAAJpX5XIAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAFxJREFUGFdVjoEOACEIQhH7/28+EGs7txqP0MTZWnEZiPItjXItyxi0kZQ1WSxz0mRXM/15frxxc03+z8ln3vApOd1NHXPdfbQAtEOYKvdKDwI2MJ9pjmt4jEXgAxu6AenG7fhtAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAMAAAD+iNU2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURfyCdFzmNPz+/AQCBAAAAJpX5XIAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAFtJREFUGFdVjwsOwCAIQ6F4/zOvH9wyEk1fLQTrbK24XBWlm7patUzDKCMpaaDR4qSB6UH68/zyxsXt/J+TzzzzaTozAx5x3324wMdgeZ8iB2nUTtMfzCYjjToPHgEB9FmClCoAAAAASUVORK5CYII=""",
            ],
            [
                # Bob
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURcR2/EzO3Pz+/AQCBAAAAAfSYwkAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAFxJREFUKFNdjgEKwDAIA2Ps/988Y3QbFUrN4Yk4U9u8P6bTVwGhWlCkcxMPKpDBIgUskBlJT7TwB2MIhJULWPFSgxOFMpP1GsQepkM+wCr5WrFZBLMSWNBRkgiAB1FZAjQDo4idAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURcR2/EzO3Pz+/AQCBAAAAAfSYwkAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAF5JREFUKFNdjwEOwDAIAhH7/zcPpC7LTIxyEWtxbmzzVtzORQLlWCAyekgGLciiiEAMZFczE2P4guswqFh+IJYsDTgl1N1UDqg9zIdAGUDF+CVWm2DeLLEXDPH/pAE8T7MCMXnmUzIAAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAMAAAD+iNU2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURcR2/EzO3Pz+/AQCBAAAAAfSYwkAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAFxJREFUGFdVjoEOACEIQhH7/28+EGs7txqP0MTZWnEZiPItjXItyxi0kZQ1WSxz0mRXM/15frxxc03+z8ln3vApOd1NHXPdfbQAtEOYKvdKDwI2MJ9pjmt4jEXgAxu6AenG7fhtAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAMAAAD+iNU2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURcR2/EzO3Pz+/AQCBAAAAAfSYwkAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAFtJREFUGFdVjwsOwCAIQ6F4/zOvH9wyEk1fLQTrbK24XBWlm7patUzDKCMpaaDR4qSB6UH68/zyxsXt/J+TzzzzaTozAx5x3324wMdgeZ8iB2nUTtMfzCYjjToPHgEB9FmClCoAAAAASUVORK5CYII=""",
            ],
        ],
    },
    # 10 - Chip 'n Dale: Rescue Rangers
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAVUExURaGhoVhYWB+l/v6TCKpEAAAAAF8YAD6Rd8gAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACoSURBVDjL1ZHRDcMgDETpBmSFok5gNuDCAogNIvYfIT5KP2N/8FVLQeZ8ejh20Hgd7+egIXqGTcLBsAzRI0Svh78gGHNIomFNMkHD2kU6e+8m4XQJy/BMWE9sEGiw5jAN0eshej1Er4ctQuGyLAIcwqfzL7hz6Jd5oEmmILn85JAHiuCal2s00UoFNAc9tQZoklURPjgaT5aoqIwaZmXmgqqE5S1fBeMGhf2RRyNchCUAAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAVUExURUzcSABQAAAAAABw7HwIAMhMDPyYOKMICyEAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACVSURBVDjL7Y7LDQMhDAVNB8Ed2NsB3g4wHeASkv5LCEQJHx8iRbmuD4iZ9wQGwBhQ3oMU0XEr0BRMkR0DRAq8CHIMIWAcInGLd4ZwYzymQHLcvmBeRN9i47Ykjxe7SY4BOC1CjuQYUL4P8N8FuQpX4ZeCjskiZ1bPn4JZ1XzOdDBosY5atdSXdgztXuxx72dLqu1c7QlXPssmwzKabQAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAVUExURQCoAAAAAABw7Ly8vPz8/MhMDHwIAFSgTGMAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADCSURBVDjLnZPbDcMgDEUvG+CMQDaIu0GzAtkg3X+EYjsPVAVb6v0xyEd+AlJRzWvTa1W9WY05ACKxM1+OZuXAJ5AxyYFFFoIXvdyAZWFeZrYAipcDIDrLUEj8S+kEpCOHVXLHvgCQFXER5RdIeSpjQUK4QEaX4QkgdF08AjkAMkVAsmWMAeiynBr8LgVIx5MYATkAMiV3Um1M/bKeAHTr/hOIaojabIA/qGCZOskAcF+k/gtf2Pa6ffZaRxY1UADU+gXEKpZbGBFnrwAAAABJRU5ErkJggg==""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 18,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": -46,
        "SPRITE_Y_POS": 4,
        "SPRITE_MOVE_SPEED": 5,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Chip
                """iVBORw0KGgoAAAANSUhEUgAAABIAAAAYCAMAAADAi10DAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQQEBP/YqNgoAP///wAAAFCEpa4AAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAIxJREFUKFNV0EsSwyAMBUFhuP+ZM6MPVN7CsbqQIhPnJqKKSxFrrayGgI9YNoVl5RKh0czEetf7FGK193ZYk7ME/7MbCWQfKXKBj1PoI/Zy2H5LQIsjjzyugRQjiTz+ifjlUpfEb4C6yijSXEHGJvvuzTg4yc1zSqUJyRstmjYeTUjuZ3fZDPU33875ATCnA2AMvsYKAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABIAAAAYCAMAAADAi10DAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQQEBP/YqNgoAP///wAAAFCEpa4AAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAItJREFUKFNdkAEOgDAIA8Hx/zd7LcypTUzWs3Ro1FbEnDeKyMw2+03mhezmhWzrQYhBKRrZOqM6IYjcWstljdQl4Dv1uAqkOfobaYGLFPQg9lLZwnuYMa4k8kZeS22yQxCzIi+k5URAQ7SBCaC/98k4ZfZD82OGDIL1bRKHYV+EP6GdOhmj3qxtVdUNSVQDvg5yAaEAAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABIAAAAYCAMAAADAi10DAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQQEBP/YqNgoAP///wAAAFCEpa4AAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAIxJREFUKFNVkAEOwCAIA0H9/5vXa9FkTbbIWSpa56pq1hdVdXeKu9O9JFezQRk9JKkRVZBLe4gDiVDtvR0WRBbAZ/I5Sog+5QcxwJJL1MgezUXYpjbxCLL8kJmg4wcB74UyFa55ij+ShEYiz1V5gpjU5EbPyV1gQcPSJaURNMDIbJoQ1Y17SCv9kME5Hw+7A0vGbM4vAAAAAElFTkSuQmCC""",
            ],
            [
                # Dale
                """iVBORw0KGgoAAAANSUhEUgAAABIAAAAYCAMAAADAi10DAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQQEBNgoAP/YqP///wAAAGLe3LkAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAItJREFUKFNl0FsSgCAMQ9Hy2P+azU2qMsoH0GMJjLV/46WqLh6qMXt/UGl45xrxoDxpzok1WdZaHwK44qYqUYmSlya1jVonKZowdT5Zuk6lqLN4JSZUkR4lgJpforLmoIJ8o54V0reAGhFIR4hC/QDUfcwODp1gck7+SxMh9CQI8imtTm/KR1bv9r4AzQ0Dz3VaEdUAAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABIAAAAYCAMAAADAi10DAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQQEBNgoAP/YqP///wAAAGLe3LkAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAIdJREFUKFNljwEOBCEIAxH9/5tvWkTNHokKk1Ik1l8cFNF5oxh50n5HEJX6hjhcPSgzzbZWZM75QQIesVEEKEBjFCpzVPNFWMsMpZHaGEcJKi9/U0waIwhOguergEids5DHacHeG2e3ZWusEsX8Re4iNtleCGuagqT9NylEfUWtuhojzbxorR/dCAQg/n/uXwAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABIAAAAYCAMAAADAi10DAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQQEBNgoAP/YqP///wAAAGLe3LkAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAI5JREFUKFNlj0ESwCAIAxH9/5ubDeB0Wg4KawgS5xcXRUw+KFbedO4Vikp9ijhcvVBmmrUWsvf+IIBHNIoQCqG1CpW5VLsR0+VtMymFkKglU6UQXu4qhsYITzH+Vc5CYonqLmQkGZfXZFy5+U9W6Qmi9UBtPzIyq/gEtKwJGls0QU3nS0bVaw/zK1ZOFOc8sAsDutfbWBMAAAAASUVORK5CYII=""",
            ],
        ],
    },
    # 11 - Bionic Commando
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAqUExURYhwAPC8PDy8/Pz8/AAAAPzkoKcAAOQAWKgAEP+/swgICP///0/fS/yYOFL67X8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEMSURBVDjLhZExasNAEEUHY1ykcm4gVoKklw8gxILd+gapDOkDq0ZNMGiuoFQmnceqUlpNSLlMr0p3ya4ck2Zn9Ztf7GPm/x2A9SMsVEjpBpIkAa/gu0rSYnqFZRkGsnKjtYb9HiRAp3mew2olrVBvO0SEw+FFyKAq7VfEgDJzwGt7koGn6ghEy0KYYN490JIWWqjGOEHb0uV66b8CwPMEnD/6XgAU+pqWmG3HPyEg27oMTJM+gyl8SGb+Xgg17sApChDbONBRJ/3kDbAcbvA/wc4A1HF8xZooDjyQeO6/FfPAtZgBhDvcAZwRVM0wOtWSw3HX1PVoKskdgGYcBpTcZTB+lJEctL6FCTviL8BfIF5WWjV+AAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAeUExURaQAAPx0YAAAANgoAKcAAP+/swgICP///0/fS/zYqKiMvl0AAAAJcEhZcwAADsMAAA7DAcdvqGQAAADzSURBVDjLhdKxbsIwEAbgc+gDYGXqBnZVqZvhJmboI6RzKtTDYyeyVkKybiUbb8slZOvl+KXYGT7JJ/sHFxAiuqUDTAv8H5BUEwAduFUMI0g6SNUqbuMAQD/i5S2sMQxgoYPDYQ/11hhSQHLjDKDP8NkcEWoDECEmZxzRkB9igIZO51P3Owt+vrrOBIWYS+a/2XtgGtPKVc8A5gtE47EEtJX13MSlNfuQKdt9KDKD2Ydc+GL2gTLbfaiI7D6809HuA9HTPpztPsg7fHurD6jFPzKCm5LrtO/kmwH9sH0YIMjaP4DXMsGN/Kqgvvayvq433vs7j7rdVqCq4TAAAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 7,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": 15,
        "SPRITE_Y_POS": 9,
        "SPRITE_MOVE_SPEED": 5,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Ladd 'Rad' Spencer
                """iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAMAAAA40HREAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJUExURU/fS////wAAAOvcCpQAAAADdFJOU///ANfKDUEAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAfSURBVBhXY2BiYoJgBgZGBhDJwMgIZMBpmDhYDRMTAAPwACn+cxKCAAAAAElFTkSuQmCC""",
            ],
        ],
    },
    # 12 - Kid Icarus
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAVUExURfz8/AAAqDy8/OQAWPyYOACoAPC8PB1nznEAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABrSURBVDjL7Y6xDcAgDASfDeJIZAAYISNkAopPn4L9V4hBlI5pUnLSdecHAGFTxSBfCgZWkU5lDGxWsOceCELTeiMpkHZsDuhEWxCHNAvydKH/YcIKVvBzUOoRPUE+1RM1kp7gzegJFvJb8gUOzWokgpXW/AAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQAAqABw7AAAAPz8/FfqunIAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABNSURBVDjLY8ANhBQY8AJGQSUCCoQIKBBUUiJgByF5go4krECQUhNGwwECRsMBAqgXDsYEAFEKjIyNlY2xY5ACZWMjI2MlY2xYycjYGAC8Hx9WR2YEcQAAAABJRU5ErkJggg==""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 16,
        "DIST_BETWEEN_SPRITES": 5,
        "SPRITE_MIN_X": -37,
        "SPRITE_Y_POS": 4,
        "SPRITE_MOVE_SPEED": 2,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Pit walking
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAYCAMAAADEfo0+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAPx0YPz8/AAAAF4gNIYAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAiklEQVQoU1WQARaDMAhDgdz/zssP6JuZQ/gtKbUUFdrsLdGBq6wP6P6CnmrnB7wKgAAUYCVPoHRYMDMS6739Q+8MR/AzyPYehxi4ZR2nRsu8JUfYCztM75A0Yypv8is8Ng6R8/VlkigF89HKP6KR3j+AWWY/4KtilY/zANb3qgE8Xb7AC4g7iCT9AOlGAouiOIOzAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAYCAMAAADEfo0+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAPx0YPz8/AAAAF4gNIYAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAgklEQVQoU12OAQ6AMAgDR/n/n70WNGqXMLhBx+mfFhxrsqe0FmyFPqDqC0qnyBfwamBi0AEoeYJLwgBJ3X6vmZdnJX/hA0h7iRADRsZRRz2MlnyBl+1sup9k2KZNE1d4bAgR+fh6kyhFOuyZNdENclvpQu8OLzauA3hl2RTWPbIe3RcPqgKphQb3bAAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAYCAMAAADEfo0+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAPx0YPz8/AAAAF4gNIYAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAhklEQVQoU1WPAQ4DMAgCK/7/z4PDLRlNrKJg+xa8oNmvDI64yvgjZv6J0RvnR7gbIkyIhTDICSkdSkjaTX+qV7RSVuSYYHzkgIElddTTlvMIK+wVu5jeEsQxXQ/5gsfGATivb14C4tmJaOP7/UtTVBA1M89nUrXll3RL9tMBJ4nigA8SsPsB5iYCgSm6+8gAAAAASUVORK5CYII=""",
            ],
        ],
    },
    # 13 - Final Fantasy
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURQCtAHt7ewAAAP///617AP+9AH85AxQAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABgSURBVDjLYwABQShQVDZUFDIWEoLxlRQYIMAYCmAKYHwliLQLQoGSkqKQkhJcAcwACoELAwOLAx56kACaO3M0HOhkAXUA7Z3JpMTEpICPVg0IYACycNEMqqxgY3DQTAwA/x4dWcQ9yBoAAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAVUExURTm9/6Xn/wCtAACoAAAAALy8vPz8/OyW6DQAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABdSURBVDjL7YqBDYAgDARxFVZoN+iXCYAJlP1HQESUREgcgCPkm9yZh83YEUXUN/a2mOvbCVOxghWs4E9AREJfuoDha8Foiz5gjdELg6Dp3gOQN9CYXNpdwHm0DYoMblaPgiKy1wMAAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 16,
        "DIST_BETWEEN_SPRITES": 5,
        "SPRITE_MIN_X": -37,
        "SPRITE_Y_POS": 4,
        "SPRITE_MOVE_SPEED": 2,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Light warrior red walking
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAYCAMAAADEfo0+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURfg4AAAAAPDQsP///wAAABDoywgAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAHdJREFUKFONjksSwCAIQwG5/5mbhLQ6rppWJj75RXdYzY//RmKXlHSIJbbWvmZGqcdbUgkkwEvxZGkiMwDqAIOoAbHYUSAWHyWRhPkAEKZosfYb71EAKEX+5KEvwMyYVb0YCaKqtYeH3cBOsRYkZ+AK2Yn/AG33A7miAq2dOGpWAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAYCAMAAADEfo0+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURfg4AAAAAPDQsP///wAAABDoywgAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAIFJREFUKFNdjwkSgDAIAwH5/5vNpXWMOqULAazdipYP34PEflLRR7QkjM61u0Y9Hss0kAAvw69HE1kBMB9gRBnUxY4CdTEpiTSCFwBhihbb5HivAYAV9a5DXwDP8KpZTGuxERMaRDsPWbSIhTVsAWFhjjeVQiH+hHPqEeCA8SG7ewOSZwI1bUY9EgAAAABJRU5ErkJggg==""",
            ],
            [
                # Light warrior brown walking
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAXCAMAAAA1KD/rAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURT+///i4AAAAAK9/AAAAAKD/xc4AAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAH9JREFUKFNtjgkOxDAIA8Px/zd3bOgqldZqExhz5DQ6kk/iTV8BNrKUXiCmZTMUHiAQeBlxgziRmd6oLQaRscDkAlWVLmJGASohsAHVsl6SpUVySFMfgYZh2aae/7QrODSASwAugAxagGdSMO+wYB9A6fQMsI1+YInzbfkPRLof8jcDRFOQnQUAAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAXCAMAAAA1KD/rAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURT+///i4AAAAAK9/AAAAAKD/xc4AAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAIZJREFUKFNVjgESxDAIAoP6/zffQuxMzmkbWS3kDHVc+dKv/AqwXcryAbq/rKIUAwMxK+kFOqqqJDolQKUFIQ/o7soSHg3ogsAu6PHoI9UO8gRZfmhsxihj9nnPZMMUwEGsPf5Agu3ga/hiUV5iZS/WSeQ0sHa7Jyn+Momis0fARTF9yMz8AOitAyRQedzcAAAAAElFTkSuQmCC""",
            ],
            [
                # Light warrior white walking
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAYCAMAAADEfo0+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURf///wAAAPg4APDQsAAAAKsoa2AAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAIFJREFUKFNFjwcShDAMA+Py/zdHxU40A5ddTsacPkj/EJXhL1bhEGbE4rOMh0IrMCMiGRoLcUWuABcKZAjOzaqKIlicsNBreUnUE5pKtXvELMEN0495A/DlmmjEXrh9AcDBlcmrKGxsxZF4lWRBn0hB0kRUsFiC+H8eQoLp1k929wXvMgJOOMOapQAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAYCAMAAADEfo0+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURf///wAAAPg4APDQsAAAAKsoa2AAAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAIRJREFUKFNljwsOwDAIQqt4/zMP0H6SkXUZz1F1VS2qjpa99AODBGKAEcH1InqssFgfECmRDLBH5Ab0YIBeEfVJAAFfYLCigdv2LwQ4wLcK7TlihtCE6V1m1lTzu4vm4usCGn50ZHQi7bzJA5R4IqmAVxSQY52nkoOlgt3So5OrVDpA1Qf08gJkZCwtXQAAAABJRU5ErkJggg==""",
            ],
        ],
    },
    # 14 - Castlevania
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURSQYjAAAAPyYOHR0dKQAALwAvPRAvaMAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA2SURBVDjLY8ALBBWVBoECZfwKDAkqEBSk2A2j4TB4FIyGA0QBEeEgSAAwuABBqKCjC3ba0QUA5ZIUapjUTMUAAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQCUAAAAACQYjFyU/POFAV0AAAAJcEhZcwAADsMAAA7DAcdvqGQAAACWSURBVDjL1dHBEcUgCARQMjYgsQKxAcL239sn3llz/Vw88AZ1kazLypouAlcCkOC5KWgcjATkBrMuzQ9ALnKDmSagE6Z0JTFs0IX0E0gX9ogPAEqBnsA4g7eeqr27Da0EuWxxADUAdkos7JyBeuEDvieU38jRslZECeZaCewvAGYFNME+K3C/STqiBAjPoKMGYSFKS/UHVdeBYWGG2AwAAAAASUVORK5CYII=""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 16,
        "DIST_BETWEEN_SPRITES": 5,
        "SPRITE_MIN_X": -42,
        "SPRITE_Y_POS": 0,
        "SPRITE_MOVE_SPEED": 4,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Simon Belmont walking
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAfCAMAAADZe72GAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAPzYqPyYOAAAAMmtv3UAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAApzAAAKTAGS+LNaAAAAiUlEQVQoU12PCQ4AIQgDQf//5+3BYZYYtSMFjPuLBwTjAdKIkgaZC6hPngHSZzPwSMC9tO4wNJBBSgDV5Yj0HHiBFnGGvSQNPBGzGrAJ61Bg0SHyALMBbKg+VFiIrjBgibdC7+hDBlTeWvrQxR9nfwHNYS3QIy4ofW+B0V1jM+QRODmAOQqBiIgPWygDLtSjvAIAAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAfCAMAAADZe72GAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAPzYqPyYOAAAAMmtv3UAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAApzAAAKcwHKJplmAAAAj0lEQVQoU22RAQ6AIAwDYfz/z167DSTaBELPsVUdyxpSnrwn8LkwmvMGMWMDPY84FTIstgKRhLIEMSY3dE0eQHsR6qpC89y1K2xF7BnJ/GQNcgiwga6TqnIZgG7gELuHu6AaYmBdwNE2YAmkPaBjHLCD/QL1PTkUhHcvnyn6W0jK+fY/QH/hC949dAuVXesBbtYDhrsTRQ0AAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAfCAMAAADZe72GAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAPzYqPyYOAAAAMmtv3UAAAAEdFJOU////wBAKqn0AAAACXBIWXMAAApzAAAKTAGS+LNaAAAAj0lEQVQoU2WQgRaAIAgDkf7/n9tt4SujTHcgEHUdtkHJvFtFmzwAtdYX9OoBuAETUS0zGWAi+STFFyKJW1dFyEIAwOc4xHy2AVgEBVS/gMsK6IryJKONslrthxoGeBQU/QL9AVgIkaqWHk6wB5R+8g2godl4acwgEe5ZmskBtt5g9B+Q7Izwf7NtMJMIkFXdNogDDskF+TIAAAAASUVORK5CYII=""",
            ],
        ],
    },
    # 15 - Double Dragon
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURby8vHR0dPz8/AAAADsAkKoAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABvSURBVDjL7dC7DYAwDITh3xuQZAGTCYDsvxvhUSHMFVByzcmK9VkKYM6eqMmiz0VLfj/XXLe4H12vM2lKR4LWC38+y2D7h7bo3WzeYlMIlNazlPBCP4CXMQRQAApAASgABaAAXgMogCoAkgBojwCsL9gVkG1vJ10AAAAASUVORK5CYII=""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAVUExURby8vHR0dEAsAAAAAIhwAPC8PPz8/I5ucToAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACGSURBVDjL7dNBCoQgFMbxz41rH3MDywPIowsMXmH2rbz/EfrSFtUwvdZDP3gK8kchCCcCDKpahhhjenPHN20Bl+kqSB9ikIDAs8O0oGFQ4HJwLuxnDcYtGAsky8kaxI47X3zxcD96ADXYweOOWo3AV/MKK/D4Z67/I795kfkyCNYnnHETsAA4vCgKzqOlGwAAAABJRU5ErkJggg==""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQAAAHR0dLy8vPz8/PfckxYAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABnSURBVDjL7Y7BDcAgDAPDBnE6AWaCwv67FVUFIrVSvn1wT+fkWAYJKK22SvIEVN4AbG0IH/deYVPwBfogilzHixWrpIWx3ALUhUtVBXlk077AhX3bxO11IQLEAiQHxA0M2MIW/iWQF8VccRm5Cd/uAAAAAElFTkSuQmCC""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 16,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": -42,
        "SPRITE_Y_POS": 0,
        "SPRITE_MOVE_SPEED": 4,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Billy Lee walking
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAnCAMAAAAxUjhGAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQAAANgoAPx0YCA47AAAAPDbIf0AAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAALVJREFUKFOVj1ESxDAIQonp/c+8gMS0n+tME32CNXgSWI7ngK5rrQDWAI8agFVVko0CBFUzAyha+A1Qm8eAJhdQrjYdBsDe9FsgoJ6JBAR2Y7MkfYOqANUBHmqBt9JBg8YrE7gdi/4Gvv3aZA5v6pdthWoBP27IAMukF3DX1KAN7dNfIojxBY6TCTNeZzYXy0qWGHBV1ZR0nLpb/bBbU/YVCPREA2ZfhUDuBrJIlDVMInewAfwAcF8FDZNxum4AAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAnCAMAAAAxUjhGAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQAAANgoAPx0YCA47AAAAPDbIf0AAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAKVJREFUKFOVkNEWhSAIBBH9/29udzT0dnuJcyJ3WEiK8YgC0YgCU2drC0hHKGWBaJlpWzlCILNmRKRa9BRwWanAJBvI7rI6ABG9qx+DgWsQGwToji4peoLMBawXYCgGbuWkBo/3yWBXMH0GvNl2nQhuymbdYW3Acm+ADsAAKP0B7G9gzngCf7tA3awAS/gXb3Brg6l/wdYTMPAEjDha1pBzuVuNMS7frgVPxfvITgAAAABJRU5ErkJggg==""",
                """iVBORw0KGgoAAAANSUhEUgAAABAAAAAnCAMAAAAxUjhGAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAPUExURQAAANgoAPx0YCA47AAAAPDbIf0AAAAFdFJOU/////8A+7YOUwAAAAlwSFlzAAAOwgAADsIBFShKgAAAAKpJREFUKFOVj1sOxDAIAwnJ/c+8Hoc8qvZnkZrCYCOIURHNMRaYdbZWQHWEntwgWmYi24oQyNwzIlIWfRvQ1rPBJAdITlsOg4je5bcAQM8EgYDd0VWK3iCzAHUBD7XAW/HIwHgywOlY9Dfw39dW5vCmvqwT1AAf9wXsKPCyPAFDTR5gE877AkoOYNEyAnwMCfcYzGTVBrcAMK1V34oClR4LIpnWcMAMcIwxfm87BQoy+rNZAAAAAElFTkSuQmCC""",
            ],
        ],
    },
    # 16 - Ninja Gaiden
    {
        "BACKGROUND_IMGS": [
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURQAAALy8vHR0dMTU/EJwXIAAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACRSURBVDjLpZLRDYAgDEQPXcDUBawuQHT/3RSM2jYiJR4fzUvgem1AGMRhRZkheeynYLnusFWEqoioo26lUgUnLcylmhw+Ba4oOazzefm1uhwcGZxTXPMrRpQNjxeWEU1Pywg69GJZZrjmV4w7MZsJ2vZQeO3bQ4uDI8OLHHtocPi/h7JDZP0PJGeHSPofPEy0A6r5YZVAXixTAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAASUExURchMDAAAAHR0dMTU/Ly8vPx0YIvzqxIAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACdSURBVDjL3ZDRDcMgDETNBnaVDAD2BBUTuAwA+y9TUhpUpDpEkfrTJ93HSWCfD5xzZIiTegaykSheIGPOhtoEt9Yt38VJ6gNAREMcJxnaCjNBzu8VgKshjmkL+c89UCl03AMi/bwHKrMeMKj6YPZQVywSaDnK8AKk4evJ8kH3oJ27jjQPMgF0wj6Bw/ix+9MTzmS4esXjprppZ/SqT28DhnZZGDraAAAAAElFTkSuQmCC""",
            """iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURTy8/AAAALy8vPy8sKt/0/UAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACaSURBVDjL7ZCLEcQgCERpAa2ApYIs/fd2i8akh5sg4xPkI9onn/yfjAyOUYkkiMRhglLCYiikCm2nHIcrQ5sRPrIYOhezcMgVVbQZUIEuy/bXYXF3MZ+QdaGTtB5K0Y1txDVnIfpGisNEPwxlDmcEHBqE3eEh1jTmrt19yK47eXGHJfsNKr9nLrzk6sVUhWu2f/3NPXtz/0niBxbKMAiCZAPdAAAAAElFTkSuQmCC""",
        ],
        "COLON_IMG": """""",
        "NUMBER_IMG_HEIGHT": 0,
        "NUMBER_IMG_WIDTH": 0,
        "NUMBER_IMGS": [],
        "SPRITE_WIDTH": 22,
        "DIST_BETWEEN_SPRITES": 10,
        "SPRITE_MIN_X": -54,
        "SPRITE_Y_POS": 0,
        "SPRITE_MOVE_SPEED": 4,
        "SPRITE_FRAMES_PER_FRAME": 1,
        "SPRITE_SETS": [
            [
                # Ryu Hayabusa Lee walking
                """iVBORw0KGgoAAAANSUhEUgAAABYAAAAfCAMAAADUZc3BAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAFyU/PzE2AAAAK89RG0AAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAv0lEQVQoU32QARIDIQgDFf//5yYLePSmU2ZOZA2Rc52vWAoy1dmZ1lYYFabuLFbY3arXZn0wB6YrwkUywQgJw2qXF4aQsJY2ASYWj4sVpntnx8CeRL5u0J1gc0+HtxoHRuwLFI09isVL5jxKY3Q+qLoS46WSmsXG1l65Vjsyh7GWxAPKpDi/R2UDUr43Y2bZx8ZYZbNHGfiKgUZ8SeFzQIiuhhBpSM/k4Nz5Wdgp/HR3WwLFy7PjD/7BnytHnPMBPqoEsAF9sD8AAAAASUVORK5CYII=""",
                """iVBORw0KGgoAAAANSUhEUgAAABYAAAAfCAMAAADUZc3BAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAFyU/PzE2AAAAK89RG0AAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAvUlEQVQoU22QCRLEIAgEEf//550e8Eg2UymQ5hAT86GQ7B3NUS6GBGrseHmxxnQrjmF7sBPQyCQoJpipwqSacMMUEpZZQwwLi+fGEnSM6rgwm2guDbrTGM52nq3GC7uYC6SFWYXi0HD/lIVdR6Ljdl6vKh3bMFiMRUzBTPQemI03RHu231v/GZ1qn168Lff94WC6OKkH9pvdcDAUx369SuE6O3PhRc3L2265nK/jJbgf+JQYC3xgSj+GzDnnD3srBOAsFmmTAAAAAElFTkSuQmCC""",
                """iVBORw0KGgoAAAANSUhEUgAAABYAAAAfCAMAAADUZc3BAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURXwIAFyU/PzE2AAAAK89RG0AAAAEdFJOU////wBAKqn0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAtElEQVQoU22RARaDIAxDodz/zstPWwFd3lbMp8SqY10akle7NXMZUwIVtu9VrDCn5cd03dgb0BGBSSYYocagG/vAEBJW6RDDxOLxYAk6Z544MJMolwO6pzGc6Zytgwd2MzeQGjMKzUPhfimN3cdG+Vo8XnbauxCc/91NIrH8Ni6Idoofj73ERzdXu72xq1/IH1zxN85n+WJmOGiHPLK9MNVO8oXhpcR8p0uF37zxi6d7ha/1A3vABOmE+Nu6AAAAAElFTkSuQmCC""",
            ],
        ],
    },
]

SMB3_NUMBER_IMGS = [
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAAC5JREFUGFdjZICA/1AanWJkhEn+/4+qhhEsxcAAVgCThAki86mkAOxKPG7A6wsAobUfA63wQV8AAAAASUVORK5CYII=""",
    """iVBORw0KGgoAAAANSUhEUgAAAAYAAAAHCAYAAAArkDztAAAAAXNSR0IArs4c6QAAADNJREFUGFdjZGBg+M+ACRgZQRL//yPkGMFCDBAJEAsmiSwBFYfoIqSDAcMOmC64HegOAwD8YhYFYzLgfAAAAABJRU5ErkJggg==""",
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAAD1JREFUGFdjZICA/1AanWJkBEn+/48pzwiWYmAAK0DXBtMAUgRRhsUUqAmoVsCMRTYRpxvA9kOtwOUDsEEAn+gWAwlpBhYAAAAASUVORK5CYII=""",
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAADdJREFUGFeFjzESACAIw9L/P7oeoIvKwUqaggDTjxSA/TLKFSRwC04goMI+lm2oiskw3pAVzSNab/UWBA+1ZjYAAAAASUVORK5CYII=""",
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAADZJREFUGFdjZGBg+M+AGzAyghT8/w9RwwjmggVgbMoVMKBYge4UkJVgBcgS6O6BuAoVIGtgBAC4Gx8FwM39MAAAAABJRU5ErkJggg==""",
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAADZJREFUGFdjZGBg+M+AGzAyghT8/4+phhEsxYCqACqIbB5BExjAVqA7AWYlyERCbsBuApKJjAC0qBYFBg944wAAAABJRU5ErkJggg==""",
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAADlJREFUGFdjZICA/1AanWJkBEn+/48pzwiWYkAogAqQbAIDihUwU2BWgvhgBWBXorkDphjsEny+AAC3vxkFFemrKAAAAABJRU5ErkJggg==""",
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAADxJREFUGFd9jkkOACAIA9v/PxpTWYJE7YFLhwECMHxCAWZ3hiQ2MAW5kEDvy6ZS8ek5TgUQ2KPshvlHmRdPZxYE6CoPYQAAAABJRU5ErkJggg==""",
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAACpJREFUGFdjZICA/1AanWJkhEn+/4+qhhEsxcAAVgCThAki8+lkAl5fAABLphwD4rXoBgAAAABJRU5ErkJggg==""",
    """iVBORw0KGgoAAAANSUhEUgAAAAgAAAAHCAYAAAA1WQxeAAAAAXNSR0IArs4c6QAAADhJREFUGFd9T0EKADAI0v8/2oGb0Bqri6QmRuzRwQ5kROn20BJgQ8SQdf8m+Jp0wtOhJ9gwdRi/WCyrGQO85BJQAAAAAElFTkSuQmCC""",
]
SMB3_COLON_IMG = """iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAiSURBVBhXY8AGGKH0fygNAoxMUAbD//8IcQpVQmlkwMAAAKEdCQKWHfAeAAAAAElFTkSuQmCC"""

def main(config):
    """App entry point

    Args:
        config: User configuration values

    Returns:
        The rendered app
    """

    # Get the current time in 24 hour format
    location = config.get("location")
    loc = json.decode(location) if location else DEFAULT_LOCATION
    timezone = loc.get("timezone", config.get("$tz", DEFAULT_TIMEZONE))  # Utilize special timezone variable
    now = time.now()

    # Because the times returned by this API do not include the date, we need to
    # strip the date from "now" to get the current time in order to perform
    # acurate comparissons.
    # Local time must be localized with a timezone
    current_time = time.parse_time(now.in_location(timezone).format("3:04:05 PM"), format = "3:04:05 PM", location = timezone)

    # Get config values
    is_24_hour_format = config.bool("is_24_hour_format", DEFAULT_IS_24_HOUR_FORMAT)
    has_leading_zero = config.bool("has_leading_zero", DEFAULT_HAS_LEADING_ZERO)

    print_time = current_time

    speed = int(config.str("speed", DEFAULT_SPEED))
    if speed < 0:
        speed = rand(MIN_SPEED + MAX_SPEED + 1) + MAX_SPEED

    speed = speed * 5
    delay = speed * time.millisecond

    selected_game = int(config.str("game", DEFAULT_GAME))
    level_number = 1
    if selected_game == 0:
        selected_game = random.number(1, len(GAME_LIST) - 1)

    level_number = random.number(0, len(GAME_CONFIGS[selected_game]["BACKGROUND_IMGS"]) - 1)
    time_box = get_bg_image(selected_game, level_number, print_time, is_24_hour_format = is_24_hour_format, has_leading_zero = has_leading_zero, has_seperator = True)

    app_cycle_speed = SECONDS_TO_RENDER * time.second
    num_frames = math.ceil(app_cycle_speed // delay)

    all_frames = []
    frames = render.Text(content = "")

    for _ in range(1, 1000):
        frames = sprite_get_frames(selected_game, level_number, time_box)
        all_frames.extend(frames)

        if len(all_frames) >= num_frames:
            break

    return render.Root(
        delay = delay.milliseconds,
        child = render.Animation(all_frames),
    )

def get_num_image(selected_game, num):
    """Gets the requested numeric image

    Args:
        selected_game: Integer that corresponds to one of the available games
        num: Integer of the image to be returned

    Returns:
        An image of the requested number
    """
    if len(GAME_CONFIGS[selected_game]["NUMBER_IMGS"]) > 0:
        return render.Padding(
            pad = (1, 0, 0, 0),
            child = render.Box(
                width = GAME_CONFIGS[selected_game]["NUMBER_IMG_WIDTH"],
                height = GAME_CONFIGS[selected_game]["NUMBER_IMG_HEIGHT"],
                child = render.Image(src = base64.decode(GAME_CONFIGS[selected_game]["NUMBER_IMGS"][int(num)])),
            ),
        )
    else:
        return render.Box(
            width = 8,
            height = 7,
            child = render.Image(src = base64.decode(SMB3_NUMBER_IMGS[int(num)])),
        )

def get_bg_image(selected_game, level_number, t, is_24_hour_format = True, has_leading_zero = False, has_seperator = True):
    """Overlays the current time onto a game background image in the user specified format

    Args:
        selected_game: Integer that corresponds to one of the available games
        level_number: Integer that corresponds to the level within a game (most have only one)
        t: The current time
        is_24_hour_format: Boolean indication if the time should display in 24 hour format
        has_leading_zero: Boolean indication if single digit hours should include a leading zero
        has_seperator: Boolean indication if a separator character should display between the hour and minutes

    Returns:
        A background image of the requested game and level that includes the current time overlay
    """
    hh = t.format("03")  # Format for 12 hour time
    if is_24_hour_format == True:
        hh = t.format("15")  # Format for 24 hour time
    mm = t.format("04")  # Format for minutes
    # ss = t.format("05")  # Format for seconds

    seperator = render.Box(
        width = 5,
        height = 7,
        child = render.Image(src = base64.decode(SMB3_COLON_IMG)),
    )

    if selected_game == int(GAME_LIST["Contra"]):
        seperator = render.Box(
            width = 3,
            height = 7,
            child = render.Image(src = base64.decode(GAME_CONFIGS[selected_game]["COLON_IMG"])),
        )
    elif selected_game == int(GAME_LIST["Bubble Bobble"]):
        seperator = render.Box(
            width = 4,
            height = 8,
            child = render.Image(src = base64.decode(GAME_CONFIGS[selected_game]["COLON_IMG"])),
        )

    if not has_seperator:
        seperator = render.Box(
            width = 3,
        )

    hh0 = get_num_image(selected_game, int(hh[0]))
    if int(hh[0]) == 0 and has_leading_zero == False:
        hh0 = render.Box(
            width = 7,
        )

    bg_img = render.Image(base64.decode(GAME_CONFIGS[selected_game]["BACKGROUND_IMGS"][level_number]))

    return render.Stack(
        children = [
            bg_img,
            render.Box(
                child = render.Row(
                    cross_align = "center",
                    children = [
                        hh0,
                        get_num_image(selected_game, int(hh[1])),
                        seperator,
                        get_num_image(selected_game, int(mm[0])),
                        get_num_image(selected_game, int(mm[1])),
                    ],
                ),
            ),
        ],
    )

def rand(ceiling):
    return random.number(0, ceiling - 1)

def sprite_get_frames(selected_game, level_number, time_box):
    """Gets an array of sprite animation frames

    Args:
        selected_game: Integer corresponding to the selected game
        level_number: Integer corresponding to the selected level within a game
        time_box: A background image to display under the sprite animation frames

    Returns:
        An array of sprite animation frames
    """
    y_pos = GAME_CONFIGS[selected_game]["SPRITE_Y_POS"]
    begin_x = GAME_CONFIGS[selected_game]["SPRITE_MIN_X"]
    end_x = FRAME_WIDTH
    step = GAME_CONFIGS[selected_game]["SPRITE_MOVE_SPEED"]
    sprite_set_index = random.number(0, len(GAME_CONFIGS[selected_game]["SPRITE_SETS"]) - 1)

    # Super Mario Bros. 3 is a special case where certain sprite sets must be used with certain levels/backgrounds. Refactor later?
    if selected_game == int(GAME_LIST["Super Mario Bros. 3"]) and level_number != 2:
        sprite_set_index = 0
    elif selected_game == int(GAME_LIST["Super Mario Bros. 3"]) and level_number == 2:
        sprite_set_index = 1

    frames = [
        sprite_get_frame(selected_game, time_box, x_pos, y_pos, sprite_set_index)
        for x_pos in range(begin_x, end_x, step)
    ]

    return frames

def sprite_get_frame(selected_game, time_box, x_pos, y_pos, sprite_set_index):
    """Gets a single sprite animation frame

    Args:
        selected_game: Integer corresponding to the selected game
        time_box: A background image to display under the sprite animation frames
        x_pos: Integer representing the X position to render the sprite
        y_pos: Integer representing the Y position to render the sprite
        sprite_set_index: TBD

    Returns:
        A single sprite animation frame
    """
    frame_index = x_pos // GAME_CONFIGS[selected_game]["SPRITE_MOVE_SPEED"]
    sprite_frame_index = (frame_index // GAME_CONFIGS[selected_game]["SPRITE_FRAMES_PER_FRAME"]) % len(GAME_CONFIGS[selected_game]["SPRITE_SETS"][sprite_set_index])
    sprite_image = GAME_CONFIGS[selected_game]["SPRITE_SETS"][sprite_set_index][sprite_frame_index]

    return render.Stack(
        children = [
            time_box,
            render.Padding(
                pad = (x_pos, y_pos, 0, 0),
                child =
                    render.Row(
                        expanded = True,
                        children = [
                            render.Image(base64.decode(sprite_image)),
                        ],
                    ),
            ),
        ],
    )

def get_schema():
    speed_options = [
        schema.Option(display = key, value = value)
        for key, value in SPEED_LIST.items()
    ]

    game_options = [
        schema.Option(display = key, value = value)
        for key, value in GAME_LIST.items()
    ]

    return schema.Schema(
        version = "1",
        fields = [
            schema.Dropdown(
                id = "speed",
                name = "Speed",
                desc = "Change the speed of the animation.",
                icon = "gear",
                default = DEFAULT_SPEED,
                options = speed_options,
            ),
            schema.Dropdown(
                id = "game",
                name = "Game",
                desc = "Change the game displayed",
                icon = "gear",
                default = DEFAULT_GAME,
                options = game_options,
            ),
            schema.Location(
                id = "location",
                name = "Location",
                desc = "Location defining time to display and daytime/nighttime colors",
                icon = "locationDot",
            ),
            schema.Toggle(
                id = "is_24_hour_format",
                name = "24 hour format",
                icon = "clock",
                desc = "Display the time in 24 hour format.",
                default = DEFAULT_IS_24_HOUR_FORMAT,
            ),
            schema.Toggle(
                id = "has_leading_zero",
                name = "Add leading zero",
                icon = "creativeCommonsZero",
                desc = "Ensure the clock always displays with a leading zero.",
                default = DEFAULT_HAS_LEADING_ZERO,
            ),
        ],
    )
