"""
Applet: Dothraki WotD
Summary: Dothraki word of the day
Description: Display a random Dothraki word of the day.
Author: tavdog
"""

load("hash.star", "hash")
load("math.star", "math")
load("render.star", "render")
load("time.star", "time")

# regex to convert tsv to array
# ^([^\t]*)\t(.*$)
# ["$1","$2"],

word_array = [
    ["accharat", "to convince"],
    ["acchinat", "to bend"],
    ["ach", "hip"],
    ["achacchra", "stinky"],
    ["achrakh", "odor, smell"],
    ["achralat", "to smell"],
    ["adakhat", "to eat"],
    ["addisat", "to simplify, to translate, to interpret"],
    ["addiwelat", "to moisten"],
    ["addo", "center, pupil"],
    ["addrivat", "to kill"],
    ["ador", "chair"],
    ["adra", "turtle"],
    ["aena", "morning"],
    ["afazh", "hot, cooked, roasted"],
    ["afazhi", "warm"],
    ["affashilat", "to calm a horse"],
    ["affazhi", "kiln"],
    ["affiezolat", "to twine, to braid"],
    ["affin", "when"],
    ["affisat", "to clean, to wash"],
    ["aggendat", "to tear, to rip, to rend"],
    ["aggi", "catfish"],
    ["aggroqelat", "to scramble, to mix up"],
    ["ahesh", "snow"],
    ["aheshke", "winter"],
    ["ahhajat", "to strengthen"],
    ["ahhalahat", "to pollinate"],
    ["ahhaqat", "to frustrate"],
    ["ahhaqe", "frustrated"],
    ["ahhasakh", "whetstone"],
    ["ahhasat", "to sharpen"],
    ["ajjalan", "night"],
    ["ajjilat", "to correct"],
    ["ajjonat", "to seal, to close off"],
    ["ajjone", "seal, cover, cork"],
    ["ajjorat", "to carve, to plan, to plot"],
    ["akat", "two"],
    ["akka", "also"],
    ["akkate", "both"],
    ["akkelenak", "leader, teacher, instructor"],
    ["akkelenat", "to put in order"],
    ["akkhezhat", "to displease"],
    ["akkimat", "to originate"],
    ["akkogat", "to damage, to scratch, to dent"],
    ["ale", "more, additional"],
    ["alegra", "duck"],
    ["alikh", "surplus, extra"],
    ["allailalat", "to calm, to pacify"],
    ["allaine", "orderly, appropriate"],
    ["alle", "further"],
    ["alleilat", "to lead astray"],
    ["ammasat", "to decorate"],
    ["ammasay", "ornate, decorative"],
    ["ammemak", "musician"],
    ["ammemat", "to play an instrument"],
    ["anat", "to jog"],
    ["anha", "I"],
    ["annese", "announcement, proclamation"],
    ["ao", "deep, dark"],
    ["aqqersat", "to intimidate"],
    ["arakh", "curved Dothraki sword"],
    ["aranat", "to drop"],
    ["aranikh", "topic, theme, subject"],
    ["aranne", "neglected, old, unused, careless"],
    ["ares", "hidden"],
    ["aresak", "coward"],
    ["aresat", "to hide"],
    ["argat", "to push"],
    ["arranat", "to shame, to browbeat"],
    ["arricholat", "to boil"],
    ["arrissat", "to fix, to repair"],
    ["arrogorat", "to scar"],
    ["arrokh", "frightening, fearsome"],
    ["arrokhat", "to frighten"],
    ["arthasat", "to fall"],
    ["asavva", "sky"],
    ["asavvadil", "rainbow"],
    ["ase", "word, command"],
    ["asfa", "berry"],
    ["asfareaven", "blueberry"],
    ["asfavirzeth", "cranberry"],
    ["ashefa", "river"],
    ["ashefash", "stream, creek"],
    ["asqoyi", "promise, oath"],
    ["assamvat", "to break"],
    ["asserisat", "to free, to liberate"],
    ["asshekh", "day, today"],
    ["asshekhqoyi", "birthday"],
    ["asshimat", "to tame"],
    ["assikhqoyi", "omen"],
    ["assikhqoyisir", "prophecy"],
    ["assilak", "conqueror"],
    ["assilat", "to signal, to sign, to conquer, to defeat"],
    ["assokh", "instruction, guideline, order, message"],
    ["assokhosor", "law"],
    ["assomat", "to remove"],
    ["astat", "to say, to tell"],
    ["astat asqoy", "to give one's word"],
    ["asti", "joke"],
    ["astokh", "speech"],
    ["astolat", "to speak"],
    ["astosor", "story, tale"],
    ["at", "one"],
    ["ath", "dry"],
    ["athachizar", "balance"],
    ["athahhaqar", "frustration"],
    ["athchakar", "silence"],
    ["athchomar", "respect"],
    ["athchomofar", "ritual, ceremony"],
    ["athdavrazar", "goodness, usefulness"],
    ["athdogar", "suffering"],
    ["athdrivar", "death"],
    ["athemesizar", "pregnant"],
    ["athevizar", "agility"],
    ["athfakizar", "humiliation, shame"],
    ["athfozar", "old age"],
    ["athgarvozar", "hunger"],
    ["athhajar", "strength"],
    ["athhoezar", "praise"],
    ["athjahakar", "pride, prowess"],
    ["athjilar", "truth"],
    ["athkemar", "marriage"],
    ["athkemizar", "allegiance, alliance"],
    ["athlainar", "beauty"],
    ["athlayafar", "happiness"],
    ["athlishtar", "patience"],
    ["athloftar", "grief"],
    ["athmaegizar", "witchcraft"],
    ["athmovezar", "magic"],
    ["athnakhar", "event, occasion"],
    ["athnithar", "pain"],
    ["athohazhar", "humidity, weight, heaviness"],
    ["athqemmozar", "cloak"],
    ["athrhanar", "mercy"],
    ["athrokhar", "fear"],
    ["athsanar", "amount, quantity"],
    ["athsandizar", "safety, security"],
    ["athserisar", "freedom"],
    ["athsharar", "health, well being"],
    ["athvervenar", "violence"],
    ["athvilajerar", "war"],
    ["athvillar", "wisdom"],
    ["athvoqorar", "rhythm, regularity, consistency"],
    ["athyallar", "childhood"],
    ["athyolar", "birth"],
    ["athzajar", "refusal"],
    ["athzalar", "hope, desire"],
    ["athzheanazar", "beauty"],
    ["athzhilar", "love"],
    ["athzhowakar", "danger"],
    ["atte", "first"],
    ["atthar", "responsibility, duty"],
    ["atthasat", "to disgrace"],
    ["atthirar", "life"],
    ["atthirarido", "dream"],
    ["attihat", "to show, to demonstrate"],
    ["atven", "alone, sole"],
    ["ave", "father"],
    ["avvemolat", "to kneel"],
    ["avvos", "never"],
    ["avvov", "armed"],
    ["awazak", "screamer, warrior"],
    ["awazat", "to scream"],
    ["awazof", "warcry, battlecry"],
    ["awessiya", "marinade"],
    ["ayena", "bell"],
    ["ayolat", "to wait"],
    ["ayyathat", "to raise, to toast, to celebrate"],
    ["ayyey", "always"],
    ["ayyozat", "to dilute, to weaken, to compromise"],
    ["az", "blade"],
    ["azhasavva", "blessing"],
    ["azhat", "to give"],
    ["azho", "gift"],
    ["azzhonathat", "to expose, to uncover, to bare, to unleash"],
    ["azzisat", "to injure, to hurt"],
    ["azzohat", "to lower"],
    ["chada", "squirrel"],
    ["chaf", "wind, knuckle, bump"],
    ["chafak", "sellsword, mercenary, assassin"],
    ["chafasar", "weather"],
    ["chafikh", "wave"],
    ["chafka", "autumn, fall"],
    ["chak", "silent"],
    ["chakat", "twenty"],
    ["chal", "bean"],
    ["chandra", "sapphire"],
    ["chandri", "blue of eye"],
    ["charat", "to hear"],
    ["chare", "ear"],
    ["charolat", "to listen"],
    ["chasi", "bait"],
    ["chasilat", "to set a trap"],
    ["chathi", "sheath"],
    ["chay", "cinnamon"],
    ["check", "well"],
    ["chelsian", "locust"],
    ["chemve", "shore, beach"],
    ["chemveser", "shoreline"],
    ["cheno", "liver"],
    ["chetirat", "to canter"],
    ["chifti", "cricket"],
    ["chiftik", "weakling"],
    ["chiftiven", "noisy, annoying"],
    ["chil", "prostrate, supine"],
    ["chili", "bed"],
    ["chilolat", "to lie down"],
    ["chin", "bent, creased, folded"],
    ["chiori", "woman"],
    ["chitat", "to shiver"],
    ["chith", "boring, tedious, dull"],
    ["chithe", "dull affair, waste of time"],
    ["chiva", "horn"],
    ["choak", "bitter"],
    ["chofkalven", "rough, unruly, unmanageable"],
    ["chomak", "one who is respectful"],
    ["chomokh", "honor"],
    ["chomolat", "to do honor"],
    ["chonge", "hard, solid, durable"],
    ["choqak", "coward"],
    ["choqat", "to flee"],
    ["chorkat", "to roll"],
    ["chosh", "fresh"],
    ["chot", "beet"],
    ["daeni", "leaf, petal, blade of grass"],
    ["dahaan", "green"],
    ["daki", "pomegranate"],
    ["dakikh", "pomegranate seed"],
    ["dalen", "one thousand"],
    ["dalfe", "cow"],
    ["dalfi", "calf"],
    ["dan", "gem, crystal, ford"],
    ["dan havazhi", "pearl"],
    ["darif", "saddle"],
    ["darin", "injured, lame, limp"],
    ["davra", "useful, good"],
    ["davraso", "worthy, valuable"],
    ["dech", "cheek"],
    ["deffa", "bush, shrub"],
    ["dei", "shallow, light"],
    ["dev", "smart, quick-witted, intuitive"],
    ["devesh", "fog"],
    ["devolat", "to intuit"],
    ["diaf", "skull"],
    ["dik", "fast, swift, quick"],
    ["dil", "shiny, sparkly"],
    ["dilat", "to shine"],
    ["dililat", "to sparkle, to shimmer"],
    ["dimi", "whisker"],
    ["dinat", "to pass"],
    ["dirgat", "to think"],
    ["dirge", "thought, idea"],
    ["dirke", "well (for water)"],
    ["dirshe", "fan"],
    ["dis", "simple, plain, obvious"],
    ["dishah", "tree bark"],
    ["dishahash", "cockroach"],
    ["disi", "easy, natural, comfortable"],
    ["disse", "only"],
    ["diwe", "wet"],
    ["dogat", "to suffer"],
    ["doggeya", "symptom"],
    ["donat", "to shout, to yell"],
    ["dorvi", "goat"],
    ["dorvof", "ibex"],
    ["dosh", "council"],
    ["dosh khaleen", "council of female Dothraki elders"],
    ["dothrak", "rider, Dothraki"],
    ["dothrakh", "ride, pursuit, endeavor"],
    ["dothrakhqoyi", "bloodrider"],
    ["dothralat", "to ride"],
    ["dothrashki", "hour"],
    ["dozgat", "to scavenge"],
    ["dozgo", "enemy"],
    ["draf", "almond"],
    ["dranelat", "to cultivate, to foster, to nurture"],
    ["dranelat flasikh", "to update"],
    ["drekat", "to spill"],
    ["drivolat", "to die"],
    ["drogat", "to drive an animal or herd"],
    ["drogikh", "herd"],
    ["drozhak", "killer"],
    ["echomosalat", "to dishonor"],
    ["edavrasa", "useless, bad"],
    ["efat", "to squeeze"],
    ["efe", "shackle, manacle"],
    ["efenalat", "to detach, to remove"],
    ["efesalat", "to itch, to uproot"],
    ["effesi", "garnet"],
    ["efichisalat", "to disagree"],
    ["ehisokh", "punishment, reprimand"],
    ["ehisolat", "to earn"],
    ["eja", "cliff"],
    ["ejakh", "river bank"],
    ["ekh", "time, instance, turn"],
    ["ekhogaralat", "to undress"],
    ["elain", "seed"],
    ["elat", "to go"],
    ["elat osoon", "to err, to make a mistake"],
    ["eleisosakh", "landmark"],
    ["elge", "sandal"],
    ["elik", "tall"],
    ["ellat", "to forget"],
    ["elme", "shoulder"],
    ["elta", "ox"],
    ["elzat", "to answer, to respond, to reply"],
    ["emat", "to smile"],
    ["eme", "smile"],
    ["emmat", "to amuse"],
    ["emrakh", "entrance, gateway, archway, opportunity"],
    ["emralat", "to enter"],
    ["emrasolat", "to invade, to ransack"],
    ["enich", "inner thigh"],
    ["enossho", "mule"],
    ["enta", "infant, baby"],
    ["erin", "good, kind"],
    ["erlo", "crow"],
    ["ershe", "old-fashioned, worn out, old"],
    ["es", "smooth"],
    ["esajalat", "to dismount"],
    ["esajjonalat", "to unseal, to uncork, to open"],
    ["esemrasakh", "exit"],
    ["eshat", "to get up"],
    ["eshina", "fish"],
    ["esina", "different"],
    ["esinasolat", "to change"],
    ["esittesa", "worthless"],
    ["essakh", "counterattack"],
    ["essalat", "to return, to come back"],
    ["essat", "to improve, to polish, to smooth"],
    ["essheya", "ceiling, roof"],
    ["essinalat", "to alter, to change, to cause to change"],
    ["etta", "ant"],
    ["etthat", "to coerce, to force"],
    ["evat", "to start"],
    ["eve", "tail"],
    ["eveth", "water"],
    ["evethiz", "salt water"],
    ["evi", "agile"],
    ["evo", "beginning, inception"],
    ["ewe", "olive"],
    ["eyel", "rain"],
    ["eyeli", "spotted"],
    ["eyelikh", "mud"],
    ["eyelke", "spring (the season)"],
    ["ezat", "to find, to discover"],
    ["ezhir", "dance"],
    ["ezhirat", "to dance, to control, to manipulate"],
    ["ezok", "student"],
    ["ezolat", "to learn"],
    ["ezzokh", "lesson"],
    ["ezzolat", "to teach"],
    ["fachat", "to nod, to abide"],
    ["fadat", "to pat"],
    ["fadda", "helmet"],
    ["fak", "hood"],
    ["fakat", "to kick"],
    ["fakilat", "to humiliate, to shame"],
    ["fakkeya", "cloud cover"],
    ["fas", "cloud"],
    ["fasi", "mist"],
    ["fasolat", "to bake"],
    ["fasqoyi", "fate, destiny"],
    ["fasvenat", "to obscure, to cover, to block"],
    ["fatat", "to slap"],
    ["fati", "insult"],
    ["fatilat", "to insult"],
    ["fatti", "kale"],
    ["fazikh", "bronze"],
    ["fazzhori", "emotion"],
    ["fej", "hate, hatred"],
    ["fejat", "to hate"],
    ["fekh", "seven"],
    ["felde", "wing"],
    ["feldekh", "feather"],
    ["fenat", "to attach, to affix"],
    ["ferri", "hemp"],
    ["fes", "itchy"],
    ["feshith", "tree"],
    ["feso", "carrot"],
    ["fesqwil", "hemlock"],
    ["feve", "thirsty"],
    ["fichat", "to take"],
    ["fichilat", "to accept, to agree"],
    ["ficholat", "to receive, to obtain, to get"],
    ["fiez", "rope"],
    ["figgo", "melon"],
    ["fih", "smoke"],
    ["fikh", "tusk"],
    ["filkat", "to crawl, to wriggle, to slither"],
    ["filki", "caterpillar"],
    ["fin", "who"],
    ["fini", "what"],
    ["finne", "where"],
    ["finsanneya", "how many"],
    ["fir", "round, circular"],
    ["fire", "circle"],
    ["firi", "ball"],
    ["firikh", "ring"],
    ["firikhnharen", "crown"],
    ["fis", "clean, pretty"],
    ["fish", "cold"],
    ["fishi", "cool"],
    ["fitte", "short"],
    ["flech", "dull"],
    ["foge", "hoof"],
    ["foloh", "horn (instrument)"],
    ["fonak", "hunter"],
    ["fonakasar", "hunting party"],
    ["fonat", "to hunt"],
    ["fonnoya", "advice, opinion"],
    ["fonolat", "to track, to seek, to search for"],
    ["fotha", "throat"],
    ["fothakh", "voice, call, cry"],
    ["fothasof", "gazelle"],
    ["foz", "old, elderly"],
    ["fozolat", "to grow old"],
    ["frakhat", "to touch"],
    ["frakholat", "to feel"],
    ["froj", "rough, coarse"],
    ["gachat", "to figure out, to solve"],
    ["gache", "place, environment"],
    ["gacheser", "territory"],
    ["gadim", "lung"],
    ["gaezo", "brother"],
    ["gale", "egg"],
    ["galekh", "egg yolk"],
    ["gamiz", "rice"],
    ["ganat", "to lean"],
    ["gango", "stomach"],
    ["gango awazat", "to feel anxious"],
    ["gangokh", "belly button"],
    ["ganikh", "post, rack"],
    ["gaoli", "intestines"],
    ["garfoth", "root"],
    ["garvo", "hungry"],
    ["garza", "paw"],
    ["gato", "radish"],
    ["gava", "monkey (borrowed from Yi Ti)"],
    ["gavat", "meat, content"],
    ["gech", "hole"],
    ["gechmen", "whole, sound, intact"],
    ["gechof", "pit"],
    ["geddat", "to flay"],
    ["geddikh", "skin"],
    ["gefat", "to sigh"],
    ["geffat", "to whisper"],
    ["geffegeffe", "gossipy, sinister, untrustworthy"],
    ["gehhiyakh", "tangle, knot"],
    ["gehi", "string, strand, gristle, vein, tendril, tentacle"],
    ["gehikh", "thread"],
    ["gende", "torn, ripped, tear, rip"],
    ["gendikh", "snack, treat"],
    ["gerat", "to lack"],
    ["ges", "made of stone"],
    ["gesisir", "hail"],
    ["geve", "mole"],
    ["gezri", "snake, serpent"],
    ["gezriven", "stealthy"],
    ["gidat", "to push"],
    ["gillo", "breeze"],
    ["gilloven", "breezy, mild"],
    ["gimi", "mouse"],
    ["givas", "table"],
    ["givasat", "to serve food"],
    ["givasolat", "to entertain, to host"],
    ["giz", "beet"],
    ["gizikh", "honey"],
    ["gizikhven", "sweet"],
    ["glas", "onion"],
    ["glen", "louse"],
    ["gloro", "medallion"],
    ["gochosor", "jaw"],
    ["gomma", "mouth"],
    ["gorat", "to charge"],
    ["gort", "thick, stout, muscular"],
    ["gosh", "certain"],
    ["gosi", "gopher"],
    ["graddakh", "filth"],
    ["gref", "flat, even, equal"],
    ["grefo", "wall"],
    ["grey", "cabbage"],
    ["groqe", "ugly"],
    ["ha nakhaan", "finally"],
    ["hachran", "lavender"],
    ["hadaen", "food"],
    ["hadaenikh", "energy"],
    ["haesh", "offspring"],
    ["haf", "quiet, soft"],
    ["hafikh", "nap"],
    ["hage", "tendon, sinew"],
    ["haj", "strong"],
    ["haje", "right"],
    ["hajmen", "weak, defenseless"],
    ["hake", "name"],
    ["hakeso", "famous, glorious, infamous"],
    ["halah", "flower, blossom"],
    ["halahikh", "pollen"],
    ["halaholat", "to bloom"],
    ["halahyazh", "spiceflower"],
    ["halelat", "to call out"],
    ["hanni", "rose water"],
    ["hanno", "rose"],
    ["haqe", "tired"],
    ["haqeqqe", "exhausted"],
    ["harelat", "to protect, to defend"],
    ["has", "sharp, capable, effective"],
    ["hatif", "face, front, in front of, before"],
    ["hatifido", "mask"],
    ["havat", "to jostle, to agitate, to disturb"],
    ["havazh", "sea, ocean"],
    ["havon", "bread (borrowed from High Valyrian)"],
    ["havzi", "cat"],
    ["havzish", "kitten"],
    ["havziven", "lazy, slothful"],
    ["hazh", "malleable"],
    ["heffe", "jar"],
    ["heffof", "jug"],
    ["hem", "fur"],
    ["heme", "furry"],
    ["hesk", "south, southern"],
    ["heth", "lip, edge, rim"],
    ["hethke", "tight, ready, prepared"],
    ["hezhah", "far, distant"],
    ["hezhahhe", "later"],
    ["hilelat", "to dig"],
    ["hilleya", "canyon, gorge, ravine, valley"],
    ["himat", "to flex, to grimace"],
    ["himo", "fist"],
    ["hlaka", "glove"],
    ["hlefo", "gelding"],
    ["hleta", "pill bug"],
    ["hletaven", "sensitive"],
    ["hlizif", "bear"],
    ["hlofa", "wrist, ankle"],
    ["hoelat", "to laud, to praise"],
    ["hoshilat", "to urge a horse on"],
    ["hoshor", "golden"],
    ["hoshori", "gold"],
    ["hoska", "snout, muzzle, mouth"],
    ["hoyalasar", "music"],
    ["hoyalat", "to sing, to bark"],
    ["hoyali", "song"],
    ["hrakkar", "lion"],
    ["hramven", "usual, ordinary"],
    ["hranna", "grass"],
    ["hraoli", "detritus"],
    ["hrazef", "horse"],
    ["hrazefolta", "camel"],
    ["hrelki", "mushroom"],
    ["iddekh", "greeting"],
    ["idiro", "owl"],
    ["ido", "wooden, fake"],
    ["idokh", "wood"],
    ["idolat", "to moan, to groan"],
    ["idrik", "guide, host"],
    ["idrilat", "to guide, to lead"],
    ["idrisofat", "to escort"],
    ["ifak", "walker (insult), foreigner, outsider"],
    ["ifat", "to walk"],
    ["iga", "bowl"],
    ["igge", "bucket"],
    ["iha", "oak tree"],
    ["ijelat", "to swallow"],
    ["ikh", "ash"],
    ["ikhqoran", "mug, cup, flagon, stein"],
    ["ikie", "husk, shell"],
    ["ildat", "to strike"],
    ["ilek", "flesh, skin"],
    ["ilme", "vegetable"],
    ["imesh", "young"],
    ["imo", "belt"],
    ["inavva", "sister"],
    ["inge", "loose, slack"],
    ["inglori", "medallion belt"],
    ["inte", "beetle"],
    ["iqofat", "to trip"],
    ["irge", "back, behind, after, thereafter"],
    ["irra", "trout"],
    ["irvosat", "to trot"],
    ["irvosof", "nag, hack (said of a horse)"],
    ["isat", "to deplete"],
    ["ise", "depleted"],
    ["ishish", "maybe, perhaps, so-called"],
    ["ishri", "violet of eye"],
    ["ishria", "amethyst"],
    ["itaso", "neutral, indifferent"],
    ["ithka", "straw"],
    ["ithka nhare", "blond, blonde"],
    ["ithkoil", "brittle, fragile"],
    ["ittelat", "to test, to prove, to doubt"],
    ["ivezh", "wild, feral"],
    ["ivezho", "wild animal, beast"],
    ["ivezhof", "fierce, vicious"],
    ["ivis", "melted"],
    ["ivisat", "to melt"],
    ["iz", "poisonous, venomous"],
    ["ize", "poison, venom"],
    ["izhvi", "womb"],
    ["izikh", "man made poison"],
    ["izven", "taboo, forbidden"],
    ["izzenat", "to forbid"],
    ["jadat", "to come"],
    ["jadilat", "to approach"],
    ["jadolat", "to arrive"],
    ["jadro", "vulture, buzzard"],
    ["jahak", "braid, lion mane, hairstyle"],
    ["jahakmen", "foreign"],
    ["jalan", "moon"],
    ["jalanqoyi", "lunar eclipse"],
    ["janet", "rug, carpet"],
    ["janha", "blanket"],
    ["janise", "niece"],
    ["jano", "wild dog"],
    ["jaqqa", "executioner"],
    ["jaqqat", "to execute"],
    ["jasat", "to laugh"],
    ["javrath", "reins, constraints, boundary"],
    ["jazat", "to block"],
    ["jedda", "pony"],
    ["jef", "club, cudgel"],
    ["jekhtat", "to bounce, to ricochet"],
    ["jela", "lemon"],
    ["jelaven", "sour"],
    ["jelli", "cheese"],
    ["jenin", "gorse"],
    ["jerak", "merchant"],
    ["jerat", "to trade"],
    ["jereser", "market"],
    ["jerilat", "to discuss"],
    ["jerriya", "discussion"],
    ["jervat", "to imprison, to capture"],
    ["jerve", "cage"],
    ["jesat", "to pull with one hand"],
    ["jesh", "ice"],
    ["jesho", "frozen"],
    ["jeshof", "glacier"],
    ["jeshven", "icy"],
    ["jieqi", "gooseberry"],
    ["jil", "correct, right, appropriate, proper"],
    ["jim", "west, western"],
    ["jin", "female goat"],
    ["jith", "fox"],
    ["jithmen", "pathetic, hapless, hopeless"],
    ["jiz", "chicken"],
    ["jolin", "cook, chef"],
    ["jolinat", "to cook"],
    ["jolino", "cooking pot"],
    ["joma", "salmon"],
    ["jon", "sealed, shut"],
    ["jor", "carved, worn, grooved"],
    ["jorok", "corn"],
    ["josat", "to thrust"],
    ["k'athsavari", "often"],
    ["k'athzalari", "whenever you're ready"],
    ["k'irgesi", "backwards"],
    ["kadat", "to wrangle an animal"],
    ["kade", "net"],
    ["kafat", "to smash, to mash, to squish"],
    ["kafe", "pestle"],
    ["kaffat", "to crush, to demolish"],
    ["kane", "lark"],
    ["karlinak", "quarter horse"],
    ["karlinat", "to gallop"],
    ["kartak", "draft horse, heavy horse"],
    ["kartat", "to pull with two hands, to fascinate, to intrigue"],
    ["kartay", "fascinating, alluring"],
    ["kartolat", "to yank"],
    ["kashat", "to last"],
    ["kashay", "remaining, left"],
    ["kashi", "time"],
    ["kathqoyi", "weighted net"],
    ["kazga", "black"],
    ["kazgash", "bruise"],
    ["kazi", "lily"],
    ["kekat", "to taunt"],
    ["kekolat", "to gloat"],
    ["kelen", "patterned, orderly"],
    ["keleni", "sensible, logical"],
    ["kelenikh", "pattern"],
    ["kem", "conjoined, married"],
    ["kemak", "spouse, wife, husband"],
    ["kemat", "to join, to marry"],
    ["kemik", "ally"],
    ["kemikhof", "corner"],
    ["kemilat", "to ally"],
    ["kemmeya", "wedding"],
    ["kemok", "bride, groom"],
    ["kemolat", "to get married"],
    ["ken", "one hundred"],
    ["kendra", "opal"],
    ["kerikh", "leather"],
    ["kesselat", "to carry with two hands"],
    ["kessesolat", "to lift with two hands"],
    ["khado", "body, extent, bulk"],
    ["khal", "leader of a band of Dothraki, king"],
    ["khalakka", "son of a khal, prince"],
    ["khalakki", "daughter of a khal, princess"],
    ["khalasar", "band of Dothraki, group, tribe"],
    ["khaleen", "female Dothraki elder"],
    ["khaleeni", "widow of a khal"],
    ["khaleesi", "wife of a khal, queen"],
    ["khaor", "waist"],
    ["khas", "escort, band of bodyguards"],
    ["khefat", "to sneeze"],
    ["kher", "hide (of an animal)"],
    ["kherreya", "glue"],
    ["khewo", "worm"],
    ["khezh", "sad"],
    ["khirat", "to hang"],
    ["khiro", "flag, banner, standard"],
    ["khirrat", "to dangle"],
    ["khizra", "marsh, swamp"],
    ["khogar", "clothes, garb, dress, suit"],
    ["khogarat", "to dress"],
    ["khogari", "cask, box, trunk"],
    ["khoyat", "to catch"],
    ["kifindirgi", "why"],
    ["kifinosi", "how"],
    ["kihatifi", "forward"],
    ["kim", "ancestor, original, initial"],
    ["kimikh", "date"],
    ["kimmeya", "artifact, relic"],
    ["kisha", "we"],
    ["ko", "second in command to a khal"],
    ["koala", "medicine"],
    ["koalat", "to heal"],
    ["koge", "flaw, blemish"],
    ["kogi", "pimple"],
    ["kogmen", "flawless, perfect"],
    ["kohol", "bow (weapon)"],
    ["koholak", "archer"],
    ["koholvroz", "crossbow"],
    ["kolver", "eagle"],
    ["kor", "branch, limb"],
    ["kordia", "walleye"],
    ["korikh", "stick"],
    ["kovarak", "visitor"],
    ["krazaaj", "mountain"],
    ["krista", "female relative, aunt"],
    ["kristasof", "grandmother"],
    ["krol", "flea, pest"],
    ["krolat", "to annoy, to pester"],
    ["krolven", "annoying"],
    ["laila", "calm, tranquil, peaceful, stationary"],
    ["lain", "beautiful, pretty, stylish, nice"],
    ["lajak", "fighter, warrior"],
    ["lajasar", "army"],
    ["lajat", "to fight"],
    ["lajilat", "to spar, to train, to play"],
    ["lajo", "fight"],
    ["lakhlalat", "to pant"],
    ["lakkhat", "to chew"],
    ["lame", "mare"],
    ["lamekh", "milk"],
    ["lamekh ohazho", "fermented mare's milk"],
    ["lanak", "messenger"],
    ["lanat ki karlinqoyi", "to gallop at a destructive pace"],
    ["lanat ki karlinqoyi", "to run, to make sense"],
    ["lanta", "scarf"],
    ["lantenharen", "headscarf"],
    ["laqat", "to cry, to weep"],
    ["lashfak", "stew"],
    ["lath", "awake"],
    ["latholat", "to wake up"],
    ["lavakh", "loud, intense"],
    ["layaf", "happy"],
    ["lazhqoyi", "feud, dispute"],
    ["ledakhat", "to embrace, to hug"],
    ["lefko", "staff, oar"],
    ["lei", "ghost"],
    ["lekh", "tongue, language"],
    ["lekhat", "to lick"],
    ["lekhilat", "to taste, to try"],
    ["lekhqora", "sign language"],
    ["lenta", "neck, tree trunk, stem"],
    ["lentakh", "collar"],
    ["lentash", "stump"],
    ["leqse", "rat, rodent"],
    ["leshitat", "to breathe"],
    ["leshiti", "second (time)"],
    ["leshitof", "minute"],
    ["leyshe", "hair brush"],
    ["leyshelat", "to brush"],
    ["liezh", "brown of eye"],
    ["liezha", "topaz"],
    ["lir", "tattoo"],
    ["lirat", "to tattoo, to write"],
    ["lisht", "patient"],
    ["lishtak", "judge"],
    ["liske", "veil"],
    ["livanat", "to carry with one hand"],
    ["livonant", "to pick up with one hand"],
    ["liwalat", "to tie together, to tie down, to complete, to finish"],
    ["liwasar", "series, collection"],
    ["liwash", "knot"],
    ["liwaso", "tied up"],
    ["lofi", "stretched, distended"],
    ["lofilat", "to stretch, to string a bow"],
    ["loftat", "to mourn, to grieve"],
    ["lojat", "to hit, to run"],
    ["lomi", "river otter"],
    ["lomma", "bath"],
    ["lommat", "to bathe"],
    ["lonat", "to drain"],
    ["loqam", "arrow"],
    ["lorat", "to wink"],
    ["lorrat", "to blink"],
    ["loshak", "protector, guardian, bodyguard"],
    ["loshat", "to transport, to contain, to carry via cart"],
    ["lost", "disappointed"],
    ["lostat", "to disappoint"],
    ["loy", "puddle, some"],
    ["loyayyo", "muddy"],
    ["madat", "to sew"],
    ["maegi", "witch"],
    ["mafo", "young goat, kid"],
    ["mafoven", "lean, thin"],
    ["mago", "lynx"],
    ["mahrazh", "man"],
    ["mai", "mother, mom"],
    ["maja", "portion, allotment"],
    ["majah", "palace of woven grass"],
    ["majat", "to separate"],
    ["majilat", "to share"],
    ["majisir", "meeting, gathering"],
    ["mallilat", "to bury"],
    ["manimven", "giddy, impatient, anxious, impetuous, impertinent"],
    ["manin", "colt"],
    ["marikh", "building"],
    ["marilat", "to build, to construct"],
    ["markat", "to pluck out, to pull out"],
    ["marriya", "tool"],
    ["mas", "riches, valuables, treasure, valuable"],
    ["mastein", "tornado"],
    ["mat", "ostrich"],
    ["mattelat", "to limp"],
    ["mawan", "quiver"],
    ["mawizzi", "rabbit, bunny"],
    ["me", "she, he, it"],
    ["mechi", "quail"],
    ["mek", "five"],
    ["mel", "cruel, wicked, sadistic, evil"],
    ["meli", "arbitrary, random"],
    ["melikh", "occurrence"],
    ["melisolat", "to occur, to happen"],
    ["mem", "noise, sound"],
    ["memak", "swan"],
    ["memat", "to make a noise, to make a sound"],
    ["memo", "musical instrument"],
    ["men", "empty"],
    ["menta", "shield"],
    ["meri", "row, line, furrow"],
    ["mes", "swollen"],
    ["mesi", "pregnant"],
    ["mesina", "soup, broth"],
    ["meso", "muscle"],
    ["mesolat", "to swell up"],
    ["mezhahe", "sexy"],
    ["mhar", "sore"],
    ["mhari", "headache"],
    ["mheggasar", "fuel"],
    ["mhotha", "barley grass"],
    ["mihe", "thorn"],
    ["mihesof", "dagger"],
    ["mil", "numb"],
    ["mithrat", "to rest"],
    ["moana", "emerald"],
    ["moani", "green of eye"],
    ["mori", "they"],
    ["moska", "pack, sack, trunk"],
    ["moskak", "pack animal"],
    ["moskat", "to load, to pack"],
    ["moskof", "cargo"],
    ["move", "handmade, magical"],
    ["movek", "magician, sorcerer, warlock"],
    ["movelat", "to make, to create"],
    ["movesolat", "to imagine, to suppose, to consider"],
    ["mredi", "garlic"],
    ["naffa", "lichen"],
    ["najah", "victorious, successful"],
    ["najahat", "to win"],
    ["nakhat", "to stop, to cease"],
    ["nakhomen", "endless, ceaseless, eternal"],
    ["naqis", "small, little"],
    ["nas", "beak"],
    ["nasa", "needle"],
    ["nasat", "to peck, to poke"],
    ["nata", "reindeer"],
    ["navvirzethay", "ashamed"],
    ["nayat", "girl"],
    ["neak", "long"],
    ["negwimven", "durable"],
    ["negwin", "rock, stone"],
    ["negwindil", "marble"],
    ["nerro", "foal"],
    ["nesat", "to know"],
    ["nesikh", "knowledge, information"],
    ["nesolat", "to learn"],
    ["nevak", "guest"],
    ["nevakh", "seat, place, rank, standing"],
    ["nevasolat", "to sit down"],
    ["nevvaya", "season"],
    ["nhare", "head of a human"],
    ["nhazh", "sticky, complicated, complex"],
    ["nhazhi", "sap"],
    ["nheshi", "falcon"],
    ["nhizo", "raven"],
    ["nhoqat", "to hammer"],
    ["nhoqo", "hammer, mallet"],
    ["nindi", "sausage"],
    ["ninthqoyi", "blood sausage"],
    ["niomvi", "elephant"],
    ["niqe", "stiff, rigid"],
    ["nir", "full"],
    ["nirrat", "to fill"],
    ["nith", "painful"],
    ["nitha", "injury"],
    ["nithi", "invigorating"],
    ["nithmen", "painless"],
    ["nivat", "to frown"],
    ["niyanqoy", "together"],
    ["nizh", "tough"],
    ["noah", "bull"],
    ["nofi", "rag, cloth"],
    ["nofilat", "to wipe"],
    ["nokitat", "to knock down, to run over"],
    ["nokittat", "to trample"],
    ["noreth", "hair"],
    ["norethqoyik", "redhead"],
    ["notat", "to turn"],
    ["nozhoven", "brown"],
    ["nris", "straight"],
    ["nroj", "thick, complex, difficult, hard"],
    ["odaya", "chest, sternum"],
    ["oeta", "yam"],
    ["ogak", "butcher"],
    ["ogat", "to slaughter, to butcher"],
    ["oggo", "head of an animal, source of a river"],
    ["ohara", "daughter"],
    ["oharat", "to collapse"],
    ["ohas", "ineffective"],
    ["ohazh", "heavy, humid"],
    ["ohazho", "fermented"],
    ["ohethke", "unprepared"],
    ["ohharat", "to destroy, to demolish, to raze"],
    ["oho", "still, motionless"],
    ["oiro", "animal fat"],
    ["oirokh", "grease"],
    ["ojil", "incorrect, improper, wrong, inappropriate"],
    ["okeo", "friend, companion"],
    ["okkak", "leader"],
    ["okkat", "to select, to choose, to prefer"],
    ["okre", "tent, ger"],
    ["oldat", "to rub, to concern, to bother"],
    ["oleth", "back of an animal"],
    ["olta", "hill"],
    ["ondelat", "to carry on one's back"],
    ["onqothat", "to walk (said of a horse)"],
    ["oqet", "ram"],
    ["oqetmen", "cowardly, unbecoming of a warrior"],
    ["oqooqo", "heartbeat"],
    ["oqoqoyi", "pulse"],
    ["ori", "eight"],
    ["orqa", "toad"],
    ["orvik", "whip"],
    ["orzevezhan", "horseshoe"],
    ["orzi", "shoe"],
    ["orzo", "trap"],
    ["os", "path, road, trail"],
    ["oshrat", "to slam into"],
    ["osithkoil", "indestructible, invincible"],
    ["osk", "prior, previous, last"],
    ["oskat", "to precede"],
    ["oskikh", "yesterday"],
    ["oskimikh", "custom"],
    ["osoleth", "bridge"],
    ["ostat", "to bite"],
    ["oste", "angry, enraged, furious"],
    ["ostejano", "cramp"],
    ["ostirge", "plan, plot, strategy"],
    ["ottat", "to anger"],
    ["ovah", "wide, fat"],
    ["ovethat", "to fly"],
    ["ovray", "available, ready"],
    ["ovvethat", "to shoot, to fire (e.g. an arrow)"],
    ["ovvethikh", "target, goal, objective"],
    ["oyof", "clay, made of clay"],
    ["oyoffeya", "mortar, cement"],
    ["ozo", "body of an animal"],
    ["ozzir", "ruby"],
    ["qacha", "firefly"],
    ["qachat", "to display"],
    ["qaeya", "light weight, arid"],
    ["qafat", "to ask"],
    ["qafe", "question"],
    ["qaffat", "to demand"],
    ["qaffikh", "demand"],
    ["qamat", "to wail"],
    ["qawe", "rusty"],
    ["qawikh", "rust"],
    ["qayelat", "to float on the surface of water"],
    ["qazat", "nine"],
    ["qazer", "apple"],
    ["qefi", "cave"],
    ["qemmemmo", "strange, bizarre, weird"],
    ["qemmo", "cover"],
    ["qemmolat", "to cover"],
    ["qemmotihan", "eyelid"],
    ["qers", "sweaty"],
    ["qerso", "sweat"],
    ["qeshah", "sand"],
    ["qeshahikh", "glass"],
    ["qeso", "basket"],
    ["qevir", "forest, woods"],
    ["qifo", "pig, swine, hog, boar"],
    ["qile", "island"],
    ["qisi", "soon, near, close"],
    ["qith", "dye, ink"],
    ["qiya", "bleeding"],
    ["qizre", "silt"],
    ["qlaseh", "deer"],
    ["qoma", "mitten"],
    ["qona", "ivy"],
    ["qora", "hand, arm"],
    ["qoramen", "clumsy"],
    ["qorraya", "forearm"],
    ["qosar", "spider"],
    ["qosarikh", "spiderweb"],
    ["qosarven", "devious, duplicitous"],
    ["qosh", "moist"],
    ["qoth", "repetitive, continuous, constant, loyal"],
    ["qoy", "blood"],
    ["qwar", "carp"],
    ["qwil", "skunk"],
    ["qwizh", "contaminated, tainted"],
    ["rachel", "tiger"],
    ["rahsan", "bright"],
    ["rakh", "boy"],
    ["rakhven", "weak"],
    ["ram", "field, surface, area"],
    ["ramven", "undeveloped, natural, wild"],
    ["rayan", "summit, top, plateau"],
    ["razav", "sorrowful"],
    ["rea", "organ"],
    ["reagale", "kidney"],
    ["reaven", "purple"],
    ["redda", "thin, sleek"],
    ["reddi", "skinny"],
    ["remekat", "to sleep"],
    ["remekolat", "to fall asleep"],
    ["ren", "hollow"],
    ["reni", "armpit"],
    ["rhae", "foot, leg"],
    ["rhaek", "athlete"],
    ["rhaelat", "to step"],
    ["rhaemen", "clumsy, uncoordinated"],
    ["rhaesh", "land"],
    ["rhaesheser", "world, planet"],
    ["rhaggat", "cart"],
    ["rhal", "handle, grip"],
    ["rhan", "merciful"],
    ["rhela", "helpful"],
    ["rhelalat", "to help"],
    ["rhellaya", "help"],
    ["rhia", "eyebrow"],
    ["rhiko", "stirrup"],
    ["rhoa", "animal, beast"],
    ["rhogor", "scar, scarred"],
    ["rhogorreya", "stripe, layer, strip"],
    ["rhoj", "family member, kin"],
    ["rhojosor", "family"],
    ["ricchi", "boiling"],
    ["rich", "bubble, swelling"],
    ["rigwa", "raisin"],
    ["rikh", "rotten, bad, foul"],
    ["rikhikh", "mold"],
    ["rikholat", "to spoil, to rot"],
    ["rile", "thigh"],
    ["rina", "fawn"],
    ["rissat", "to cut, to slice"],
    ["rissisir", "razor grass"],
    ["riv", "nose, tip"],
    ["rivvat", "to sniff, to smell"],
    ["riz", "chest of an animal"],
    ["rizh", "son"],
    ["rizhisir", "lineage"],
    ["rochat", "to scrape"],
    ["rofolat", "to shrivel"],
    ["rohane", "mustache"],
    ["rokh", "afraid, fearful"],
    ["rokhat", "to fear"],
    ["saccheya", "part, category, division, section"],
    ["sachat", "to split, to halve"],
    ["sache", "half"],
    ["sachi", "half"],
    ["sadak", "drummer"],
    ["sado", "drum"],
    ["sadosor", "drum circle"],
    ["sai", "candle"],
    ["sajat", "to mount, to get on a horse"],
    ["sajo", "mount, steed"],
    ["sajolat", "to court, to date"],
    ["sale", "beaver"],
    ["salekh", "beaver dam"],
    ["sali", "claw"],
    ["samva", "broken"],
    ["samven", "numerous"],
    ["samvolat", "to break apart"],
    ["san", "heap, pile, stack"],
    ["sandi", "safe, secure"],
    ["sanneya", "number"],
    ["saqoya", "bloody"],
    ["saqwa", "herring"],
    ["sash", "young, new"],
    ["sathoma", "juicy"],
    ["sathomakh", "orange"],
    ["save", "again"],
    ["seffa", "river dolphin"],
    ["seffat", "to nudge"],
    ["sek", "yes"],
    ["sekke", "too, very"],
    ["sen", "three"],
    ["serak", "knight (borrowing from the Common Tongue)"],
    ["seris", "clear, free"],
    ["serja", "vest"],
    ["serjat", "to cover partially"],
    ["serji", "rib"],
    ["sewaf", "grape"],
    ["sewafikh", "wine"],
    ["shafka", "you (formal)"],
    ["shani", "economical, efficient"],
    ["shanjela", "lime"],
    ["shar", "well, healthy"],
    ["shekh", "sun"],
    ["shekhi", "torch"],
    ["shekhikh", "light"],
    ["shekhqoyi", "solar eclipse"],
    ["shierak", "star"],
    ["shierak qiya", "Red Comet"],
    ["shierakasar", "galaxy, constellation"],
    ["shierat", "to glide"],
    ["shigat", "to snore"],
    ["shilak", "busybody, gossip"],
    ["shilakikh", "gossip"],
    ["shilat", "to know a person, to be familiar with, to know how"],
    ["shillat", "to trust"],
    ["shilolat", "to meet, to become familiar with"],
    ["shim", "tame"],
    ["shimosh", "pet"],
    ["shinat", "to fizzle, to burn out"],
    ["shiqeth", "gray"],
    ["shiqethi", "iron"],
    ["shirane", "beard"],
    ["shiro", "scorpion"],
    ["sho", "smudge, mark, drop, spot"],
    ["shoga", "cream"],
    ["shogakh", "butter"],
    ["shokat", "to jump, to hurdle"],
    ["sholat", "to mark, to smudge"],
    ["shoqoyi", "proof, evidence"],
    ["shor", "gown, robe, dress"],
    ["shorhae", "footprint"],
    ["shoven", "tainted, stained"],
    ["shovenikh", "stain"],
    ["siera", "nephew"],
    ["sif", "shovel, spade"],
    ["sikhtelat", "to spit"],
    ["sil", "following, next"],
    ["silak", "follower, subject"],
    ["silat", "to flash, to gleam, to follow, to wander"],
    ["sililat", "to serve, to attend"],
    ["sille", "next"],
    ["silokh", "tomorrow"],
    ["simon", "male relative, uncle"],
    ["simonof", "grandfather"],
    ["simonokka", "grandson"],
    ["simonokki", "granddaughter"],
    ["sin", "side"],
    ["sindarin", "weak, inferior"],
    ["sindarine", "left, left-side"],
    ["sine", "team, band"],
    ["sinneya", "border"],
    ["sisi", "lightning"],
    ["sisiven", "specific, exact, precise"],
    ["sivorsa", "explosion"],
    ["siyalat", "to sparkle, to glitter, to shimmer"],
    ["soayso", "drunk"],
    ["solotti", "map (borrowing from High Valyrian)"],
    ["som", "zero, absent, missing"],
    ["sondra", "obsidian, dragon glass"],
    ["soqa", "fabric"],
    ["soqat", "to weave"],
    ["soqe", "woven"],
    ["soqikh", "cloth"],
    ["soqwi", "plum"],
    ["sorf", "dirty"],
    ["sorfo", "dirt, earth, soil"],
    ["sorfosor", "ground, earth"],
    ["sorohilat", "to halt a horse"],
    ["sovi", "pear"],
    ["tahar", "crafty, clever, cunning"],
    ["taharreya", "trick"],
    ["takka", "slime, muck, gunk, sludge"],
    ["tamoven", "loyal, dependable"],
    ["taoka", "metal, metallic"],
    ["taso", "silkmoth"],
    ["tasokhi", "silk, silken"],
    ["tat", "to do"],
    ["tavat", "to chop"],
    ["tavo", "axe, hatchet"],
    ["tawak", "metal, valid, real, genuine"],
    ["tawakof", "steel"],
    ["tefan", "potential, future"],
    ["tefani", "heir, candidate"],
    ["tefat", "to measure"],
    ["tefilat", "to appraise"],
    ["temme", "thunder"],
    ["thaccheya", "pincer"],
    ["thachat", "to pinch"],
    ["thade", "peninsula"],
    ["thagwa", "yogurt"],
    ["thash", "soft, fluffy"],
    ["thelis", "blue"],
    ["theya", "nipple"],
    ["theyaven", "pink"],
    ["thi", "ten"],
    ["thif", "narrow"],
    ["thikh", "chore, task"],
    ["thikhmithrin", "hobby"],
    ["thiqi", "tick"],
    ["thiqilat", "to burrow"],
    ["thirat", "to live"],
    ["thirat athdrivaride", "to have a nightmare"],
    ["thirat atthiraride", "to dream"],
    ["thiri", "alive"],
    ["thirolat", "to survive"],
    ["thodor", "cedar"],
    ["thoge", "chant"],
    ["thogek", "storyteller, author, historian, poet"],
    ["thogelat", "to chant"],
    ["thom", "juice"],
    ["thozhi", "bronze"],
    ["tif", "nut"],
    ["tih", "eye"],
    ["tihak", "scout"],
    ["tihat", "to see"],
    ["tihilat", "to look at, to glance"],
    ["tiholat", "to understand, to realize"],
    ["tim", "boot"],
    ["timvir", "book (borrowed from High Valyrian)"],
    ["tir", "finger, toe, digit"],
    ["tirat", "to point at, to indicate"],
    ["tirikh", "fingernail, toenail"],
    ["tisha", "sapling"],
    ["tisholat", "to sprout"],
    ["tith", "east, eastern"],
    ["tiv", "wax"],
    ["tivven", "waxy"],
    ["tofin", "masterful, skillful"],
    ["tofinneya", "skill, ability"],
    ["toggaya", "floor"],
    ["toki", "foolish, stupid"],
    ["tokik", "fool"],
    ["tolorro", "bone"],
    ["toqen", "indigo, indigo bush"],
    ["toqer", "fissure, crack, crevice"],
    ["tor", "four"],
    ["torga", "animal belly"],
    ["tovish", "bridle"],
    ["towan", "steppe"],
    ["tozara", "lake"],
    ["tozarash", "pond"],
    ["trish", "fern"],
    ["vado", "turnip, filly"],
    ["vaes", "city, realm, stationary"],
    ["vaesi", "clog, clot, concern"],
    ["vaesilat", "to clot, to clog"],
    ["vaf", "ewe"],
    ["vafi", "lamb"],
    ["vafikh", "wool"],
    ["valad", "horizon, peel, crust"],
    ["valsh", "north, northern"],
    ["vana", "goose"],
    ["vash", "stampede"],
    ["vash hrazefmen", "earthquake"],
    ["vathorikh", "dried fruit"],
    ["vaz", "storm"],
    ["vazzelatha", "sandstorm"],
    ["vedan", "surprising, unexpected"],
    ["veddera", "wheat"],
    ["vedderraya", "bran"],
    ["vekhat", "to exist"],
    ["vekhikh", "person, individual, thing"],
    ["velainerat", "to sow"],
    ["veltor", "yellow"],
    ["velzerat", "to stall, to procrastinate"],
    ["velzerikh", "excuse, reason"],
    ["vem", "elbow, knee"],
    ["vemerat", "to admire"],
    ["vemish", "heel"],
    ["ven", "same, identical"],
    ["veneser", "type, kind"],
    ["veni", "similar"],
    ["veno", "suitable"],
    ["ver", "wolf"],
    ["verak", "traveler"],
    ["verakasar", "caravan"],
    ["verat", "to travel"],
    ["vernat", "to lead a horse, to mentor"],
    ["vernilat", "to train a horse"],
    ["verqoyi", "direwolf"],
    ["verven", "violent"],
    ["veyan", "dark"],
    ["vezh", "stallion"],
    ["Vezhof", "the Great Stallion"],
    ["vezhven", "perfect, good, great"],
    ["vezhvenak", "hero, champion"],
    ["vichomer", "respectful"],
    ["vigererat", "to miss"],
    ["vigoferat", "to applaud"],
    ["vihoerat", "to worship"],
    ["vijazerat", "to protect"],
    ["vijazerolat", "to save, to rescue"],
    ["vik", "chin, made of tin"],
    ["viki", "tin"],
    ["vikovarerat", "to remain, to stay"],
    ["vilajero", "battle"],
    ["vilajerosh", "game"],
    ["vilanera", "race"],
    ["vilanerat", "to race"],
    ["vilaqerat", "to lament, to mourn"],
    ["ville", "experienced, wise"],
    ["vilojerat", "to beat"],
    ["vimajerat", "to filter, to strain"],
    ["vimajeri", "sieve, filter"],
    ["vimemerat", "to echo, to reverberate"],
    ["vimithrerat", "to camp"],
    ["vimithreri", "camp, encampment"],
    ["vindelat", "to stab"],
    ["vineserat", "to remember, to recall"],
    ["vinhoqerat", "to forge, to craft"],
    ["vinofirat", "to clean"],
    ["vinte", "meal"],
    ["viqaferat", "to beg, to plead"],
    ["virsalat", "to burn"],
    ["virzeth", "red"],
    ["vish", "forehead"],
    ["vishaferat", "to break a horse"],
    ["vishilerat", "to remember a person"],
    ["vitha", "flowing, fair, righteous"],
    ["vithalat", "to flow"],
    ["vitiherat", "to examine, to consider, to ponder"],
    ["vitihirat", "to watch, to observe, to witness"],
    ["vitteya", "feast, party"],
    ["vivorsero", "brushfire"],
    ["vizhad", "silver, silvery"],
    ["vizhadi", "silver"],
    ["vlaya", "poppy"],
    ["vlayakh", "milk of the poppy"],
    ["vlerat", "to pull with one's entire body"],
    ["vod", "dust"],
    ["vodven", "dusty"],
    ["vodven", "dusty"],
    ["vogla", "onyx"],
    ["vogli", "black/dark brown of eye"],
    ["voj", "human, person"],
    ["voje", "sentient"],
    ["vojjor", "statue, god, deity"],
    ["vojmen", "uninhabitable"],
    ["volderat", "to massage"],
    ["voqorat", "to pulsate"],
    ["vorsa", "fire"],
    ["vorsaska", "summer"],
    ["vorsqoyi", "funeral pyre"],
    ["vorthqoyi", "fang"],
    ["vorto", "tooth"],
    ["vos", "no"],
    ["vos ale", "no more, enough, that's enough"],
    ["vosso", "not really"],
    ["votta", "bat"],
    ["vov", "weapon"],
    ["vovosor", "weaponry"],
    ["vozzholat", "to roast"],
    ["vozzholosor", "feast"],
    ["vrelat", "to leap (said of animals)"],
    ["vricha", "lentil"],
    ["vroz", "slow"],
    ["yachi", "peach"],
    ["yalalli", "childish"],
    ["yalli", "child"],
    ["yanqolat", "to gather, to collect, to bring"],
    ["yanqosor", "tribe, collective"],
    ["yaqla", "adult horse"],
    ["yaqlak", "adult, parent"],
    ["yaqlakasar", "parents, parentage"],
    ["yarat", "to flinch"],
    ["yaroyaro", "cowardly, weak"],
    ["yash", "air"],
    ["yath", "up, upward, high"],
    ["yatholat", "to rise"],
    ["yazh", "spice, spiced"],
    ["yazh", "spice"],
    ["yazla", "diamond"],
    ["yechi", "young animal"],
    ["yeni", "failure, folly"],
    ["yer", "you (informal)"],
    ["yeri", "you (plural)"],
    ["yesi", "elderly woman"],
    ["Yesko", "Ghiscari (borrowed from Ghiscari)"],
    ["yetto", "frog"],
    ["yez", "rash, having a rash"],
    ["yez", "rash"],
    ["yof", "wheel"],
    ["yol", "born"],
    ["yolak", "native, local"],
    ["yom", "crossing"],
    ["yomat", "to cross"],
    ["yomme", "across"],
    ["yor", "one million"],
    ["yot", "fruit"],
    ["yothnhare", "human brain"],
    ["yotoggo", "animal brain"],
    ["yoz", "cloudy, opaque"],
    ["yozi", "confused, muddled"],
    ["zajat", "to refuse"],
    ["zalat", "to hope"],
    ["zan", "steady, stable, steadfast"],
    ["zande", "satchel, sack, bag"],
    ["zanissho", "shadow"],
    ["zao", "geyser"],
    ["zasqa", "white, unproven, untested, pale"],
    ["zawat", "bone marrow"],
    ["zelatha", "desert"],
    ["zemo", "hawk"],
    ["zerqolat", "to swim"],
    ["zhalia", "butterfly"],
    ["zhaliaf", "cocoon"],
    ["zhani", "spear"],
    ["zhaqe", "bass (fish)"],
    ["zhav", "lizard"],
    ["zhavvorsa", "dragon"],
    ["zheana", "beautiful"],
    ["zherakh", "walnut"],
    ["zhif", "salt"],
    ["zhifikh", "jerky"],
    ["zhifven", "salty"],
    ["zhikh", "sick, ill"],
    ["zhikhven", "sickly"],
    ["zhilak", "lover"],
    ["zhilat", "to love"],
    ["zhililat", "to like"],
    ["zhilli", "superficial, generic"],
    ["zhinda", "six"],
    ["zhogwin", "boulder"],
    ["zhokakkwa", "massive, huge"],
    ["zhokwa", "big, large, great"],
    ["zhonath", "nude, naked, unencumbered, outside"],
    ["zhor", "heart, pit, seed, nut"],
    ["zhorre", "own"],
    ["zhorrof", "fig"],
    ["zhowak", "dangerous"],
    ["zich", "powder"],
    ["zichome", "disrespectful"],
    ["zichomelat", "to disrespect"],
    ["zichven", "powdery"],
    ["zifichelat", "to steal"],
    ["ziganesolat", "to oppose, to defy"],
    ["zigere", "necessary"],
    ["zigerelat", "to need, to require"],
    ["zihakeselat", "to mistake"],
    ["zimemekh", "distraction, deception, ruse"],
    ["zinay", "leftover"],
    ["zir", "bird"],
    ["zirathe", "ragged, worn, bedraggled"],
    ["zireyeselat", "to disturb"],
    ["zirgloro", "peacock"],
    ["ziri", "chick"],
    ["ziroqosekh", "ache"],
    ["zirqoyi", "raptor, bird of prey"],
    ["zis", "hurt"],
    ["zisandise", "unsafe, insecure"],
    ["zisire", "blind"],
    ["ziso", "wound"],
    ["zitihoselat", "to misunderstand"],
    ["zivitiherelat", "to ignore"],
    ["ziyenelat", "to fail"],
    ["zoh", "low, lower"],
    ["zohhe", "down, downward"],
    ["zol", "tiny"],
    ["zoli", "teeny"],
    ["zolle", "some"],
    ["zoqwa", "kiss"],
    ["zoqwat", "to kiss"],
    ["zor", "growl, roar"],
    ["zorat", "to growl, to roar"],
    ["zoso", "dove, pigeon"],
]

def render_error():
    return render.Root(
        render.WrappedText("Something went wrong getting today's word!"),
    )

def main():
    print("Starting")

    date = str(time.now())[0:10]

    print(date)

    # do a weird hash thing to the date to get the randomish word
    word_index = abs(int(math.remainder(int(hash.md5(date), 16), len(word_array))))
    print(int(word_index))

    word = word_array[word_index][0]
    definition = word_array[word_index][1]

    return render.Root(
        child = render.Column(
            children = [
                render.Marquee(
                    child = render.Column(
                        children = [
                            render.WrappedText(
                                content = word,
                                color = "#00eeff",
                                font = "5x8",
                            ),
                            render.WrappedText(
                                content = definition,
                                font = "5x8",
                            ),
                        ],
                    ),
                    height = 25,
                    offset_start = 23,
                    scroll_direction = "vertical",
                ),
                render.Box(
                    height = 1,
                    color = "#fa0",
                ),
                render.Text(
                    content = "Dothraki WotD",
                    height = 6,
                    font = "CG-pixel-3x5-mono",
                ),
            ],
        ),
        delay = 140,
    )
