// Package apps provides a clean way for Tidbyt to be able to get a list of all
// community apps.
package apps

// Code generated by tools/generator. DO NOT EDIT.

import (
	"tidbyt.dev/community/apps/analogclock"
	"tidbyt.dev/community/apps/bgghotness"
	"tidbyt.dev/community/apps/bigclock"
	"tidbyt.dev/community/apps/binaryclock"
	"tidbyt.dev/community/apps/clockbyhenry"
	"tidbyt.dev/community/apps/dateprogress"
	"tidbyt.dev/community/apps/datetimeclock"
	"tidbyt.dev/community/apps/daynightmap"
	"tidbyt.dev/community/apps/digitalrain"
	"tidbyt.dev/community/apps/dvdlogo"
	"tidbyt.dev/community/apps/espnnews"
	"tidbyt.dev/community/apps/fuzzyclock"
	"tidbyt.dev/community/apps/golfhandicap"
	"tidbyt.dev/community/apps/googletraffic"
	"tidbyt.dev/community/apps/jokesjokeapi"
	"tidbyt.dev/community/apps/manifest"
	"tidbyt.dev/community/apps/mbta"
	"tidbyt.dev/community/apps/nationaltoday"
	"tidbyt.dev/community/apps/nightscout"
	"tidbyt.dev/community/apps/noaabuoy"
	"tidbyt.dev/community/apps/nyancat"
	"tidbyt.dev/community/apps/phaseofmoon"
	"tidbyt.dev/community/apps/pokedex"
	"tidbyt.dev/community/apps/sbbtimetable"
	"tidbyt.dev/community/apps/sportsstandings"
	"tidbyt.dev/community/apps/steam"
	"tidbyt.dev/community/apps/sunrisesunset"
	"tidbyt.dev/community/apps/theysaidso"
	"tidbyt.dev/community/apps/twitterfollows"
)

// GetManifests returns a list of all apps in the this repository. Add your applet
// below to include it in the Tidbyt Mobile app for all Tidbyt users.
func GetManifests() []manifest.Manifest {
	return []manifest.Manifest{
		analogclock.New(),
		bgghotness.New(),
		bigclock.New(),
		binaryclock.New(),
		clockbyhenry.New(),
		dateprogress.New(),
		datetimeclock.New(),
		daynightmap.New(),
		digitalrain.New(),
		dvdlogo.New(),
		espnnews.New(),
		fuzzyclock.New(),
		golfhandicap.New(),
		googletraffic.New(),
		jokesjokeapi.New(),
		mbta.New(),
		nationaltoday.New(),
		nightscout.New(),
		noaabuoy.New(),
		nyancat.New(),
		phaseofmoon.New(),
		pokedex.New(),
		sbbtimetable.New(),
		sportsstandings.New(),
		steam.New(),
		sunrisesunset.New(),
		theysaidso.New(),
		twitterfollows.New(),
	}
}
