"""
Applet: One Piece Bdays
Summary: Today's One Piece Birthday
Description: Lists all One Piece characters celebrating their birthday today.
Author: raymbartlett
"""

load("encoding/json.star", "json")
load("render.star", "render")
load("schema.star", "schema")
load("time.star", "time")

DEFAULT_LOCATION = """
{
	"lat": "40.6781784",
	"lng": "-73.9441579",
	"description": "Brooklyn, NY, USA",
	"locality": "Brooklyn",
	"place_id": "ChIJCSF8lBZEwokRhngABHRcdoI",
	"timezone": "America/New_York"
}
"""
HEADER_BACKGROUND = "#a90000"
HEADER_TEXT = "#ffffff"

birthdays = {
    "01-01": ["Portgas D. Ace", "Anjo", "Daz Bones", "Islewan"],
    "01-02": ["Peepley Lulu"],
    "01-03": ["Aisa", "Iceburg"],
    "01-04": ["Peterman", "Lassoo", "Ulti"],
    "01-05": ["Strawberry"],
    "01-06": ["Oimo", "Tilestone"],
    "01-07": ["Mozu"],
    "01-08": ["Emporio Ivankov", "Ivan X", "General Franky"],
    "01-09": ["Pickles", "Mountblutain"],
    "01-10": ["Otohime", "Eustass Kid"],
    "01-11": ["Itomimizu"],
    "01-12": ["Hiriluk"],
    "01-13": ["Ikaros Much"],
    "01-14": ["Sweet Pea"],
    "01-15": ["A.O."],
    "01-16": ["Boodle"],
    "01-17": ["Capone Bege"],
    "01-18": ["Splash", "Splatter"],
    "01-19": ["Spandine", "Kouzuki Toki"],
    "01-20": ["Kinderella"],
    "01-21": ["Miss Friday", "Antonio"],
    "01-22": ["Going Merry", "Merry", "Pez"],
    "01-23": [
        "Charlotte Nusstorte",
        "Charlotte Basskarte",
        "Charlotte Dosmarche",
        "Ginrummy",
        "Roxanne",
    ],
    "01-24": ["Gild Tesoro", "Ms. Monday", "Kairiken"],
    "01-25": ["Giolla"],
    "01-26": ["Nero", "Kuromarimo"],
    "01-27": ["Charlotte Chiffon", "Charlotte Lola"],
    "01-28": ["Mansherry"],
    "01-29": ["Kin’emon"],
    "01-30": ["Suleiman", "Domo-kun"],
    "01-31": ["Aladine", "Ipponmatsu", "An Zengaiina"],
    "02-01": ["Doma", "Brogy"],
    "02-02": ["Killer", "Ninjin", "Nefertari Vivi", "Elizabello II"],
    "02-03": ["Brownbeard", "Bizarre", "Fuza", "Sasaki"],
    "02-04": ["Gloriosa", "Haruta", "Fukaboshi", "Fujin"],
    "02-05": ["Vista", "Blamenco"],
    "02-06": ["Nico Olvia", "Nico Robin", "Blondie"],
    "02-07": ["Buchi"],
    "02-08": ["Onigumo", "Chiken", "Gonbe"],
    "02-09": ["Carne", "Genbo", "Bartholomew Kuma", "Wadatsumi"],
    "02-10": ["Mikazuki", "Page One"],
    "02-11": ["Charlotte Flampé"],
    "02-12": ["Little Oars Jr."],
    "02-13": ["Nefertari Cobra"],
    "02-14": ["Ms. Valentine", "Hyogoro"],
    "02-15": ["Big Mom", "Daisy"],
    "02-16": ["Bluejam"],
    "02-17": ["Clione", "Ukkari"],
    "02-18": ["Gambia", "Minolva", "Snowma-san", "Snow Queen"],
    "02-19": [
        "Bobby Funk",
        "Road",
        "Cocox",
        "Superhuman Domingos",
        "Henohenounchi",
    ],
    "02-20": ["Kumadori"],
    "02-21": ["Jigoro", "Charlotte Dragée", "Charlotte Dolce", "Pascia"],
    "02-22": ["Jerry", "Hamburg", "Oden"],
    "02-23": ["Makino"],
    "02-24": ["Enishida", "Mr. Beans"],
    "02-25": ["Tightrope Walking Funan Bros.", "Gerd"],
    "02-26": ["Raizou"],
    "02-27": ["Charlotte Joscarpone", "Charlotte Mascarpone"],
    "02-28": [
        "Woop Slap",
        "Charlotte Cracker",
        "Charlotte Custard",
        "Charlotte Angel",
        "Kazekage",
    ],
    "02-29": ["Pandaman", "Pandawoman"],
    "03-01": ["Mhinorinoceros"],
    "03-02": [
        "Vinsmoke Ichiji",
        "Vinsmoke Niji",
        "Vinsmoke Sanji",
        "Vinsmoke Yonji",
        "Sanjuan Wolf",
    ],
    "03-03": ["Galdino", "Hina", "O-Tama"],
    "03-04": ["Masira", "Minotaurs"],
    "03-05": ["Sadi", "Minokoala"],
    "03-06": ["Salome", "Charlotte Brûlée", "Jaguar D. Saul"],
    "03-07": ["Gyoru", "Minozebra"],
    "03-08": ["Zambai", "Samurai Butts"],
    "03-09": ["Shanks", "Dracule Mihawk", "Franky"],
    "03-10": ["Satori", "Hotori", "Kotori", "Sentomaru", "Nola"],
    "03-11": ["Spandam", "Palms"],
    "03-12": ["Stelly", "Patty", "Sarutobi"],
    "03-13": ["Lafitte"],
    "03-14": ["Alvida", "Charlotte Perospero", "Smoker"],
    "03-15": ["Who’s Who"],
    "03-16": ["Tom"],
    "03-17": ["Ideaman"],
    "03-18": ["Trebol"],
    "03-19": ["Atmos", "Scratchmen Apoo"],
    "03-20": ["Sabo", "Shiki"],
    "03-21": ["Lieutenant Spacey"],
    "03-22": ["Sapi"],
    "03-23": ["Charlotte Raisin", "Miss Catherine"],
    "03-24": ["Thatch"],
    "03-25": ["Ohm", "Thousand Sunny"],
    "03-26": ["Tsuru", "Mikio Itoo"],
    "03-27": ["Pinkbeard", "Shioyaki"],
    "03-28": ["Sarue"],
    "03-29": ["Catarina Devon", "St. Shalulia", "Fukurokuju"],
    "03-30": ["Manboshi", "Bas"],
    "03-31": ["And"],
    "04-01": ["Usopp", "Kashi", "Kerville"],
    "04-02": ["Jinbe", "Zeff"],
    "04-03": ["Brook", "Porchemi", "Monda"],
    "04-04": ["Shirahoshi", "Foxy", "Shishilian"],
    "04-05": ["Minister of the Right", "Yamakaji"],
    "04-06": ["Whitebeard", "Jean Bart", "Speed Jiru"],
    "04-07": ["Gin", "Shachi"],
    "04-08": ["Clover", "Buffalo", "Megalo", "Bourbon Jr."],
    "04-09": ["Caesar Clown", "Piiman", "Marguerite", "Mohmoo", "Yorki"],
    "04-10": ["Tamanegi", "Boss of the Forest", "Nora Gitsune", "Ashura Douji"],
    "04-11": ["Pekoms"],
    "04-12": ["Bakkin", "Cowboy"],
    "04-13": ["Morgan"],
    "04-14": ["Hody Jones"],
    "04-15": ["Fossa"],
    "04-16": ["Stronger"],
    "04-17": ["Charlotte Anana"],
    "04-18": ["Hyouzou"],
    "04-19": ["Sham"],
    "04-20": ["Blueno"],
    "04-21": ["Ucy", "Island Eater"],
    "04-22": ["Kuro"],
    "04-23": ["Kalifa", "Charlotte Mont-d’Or"],
    "04-24": ["Stussy", "Chome"],
    "04-25": ["Penguin"],
    "04-26": ["Chaka"],
    "04-27": ["Streusen"],
    "04-28": ["Funkfreed"],
    "04-29": ["Ms. Goldenweek"],
    "04-30": ["Viola"],
    "05-01": ["Kaido", "Capote", "Hikoichi"],
    "05-02": ["Cosette", "Coribou", "Monkey D. Garp"],
    "05-03": ["Arlong"],
    "05-04": ["Isshily", "Koushirou", "Cindry"],
    "05-05": ["Demaro Black", "Monkey D. Luffy", "G-5 Base"],
    "05-06": ["Enel"],
    "05-07": ["Maynard"],
    "05-08": ["Shakky", "Shoujou"],
    "05-09": ["Kong", "Sengoku"],
    "05-10": ["Heracles"],
    "05-11": ["Goldberg", "Poro"],
    "05-12": ["Vinsmoke Judge", "Daikoku"],
    "05-13": ["Koby", "Silvers Rayleigh"],
    "05-14": ["Tamago"],
    "05-15": ["Baby 5"],
    "05-16": ["Kolumbus", "Pudding Pudding"],
    "05-17": ["Mr. 13", "Hocker", "Poppy"],
    "05-18": ["Gorilla"],
    "05-19": ["Andre", "Candre", "John Giant", "Tenguyama Hitetsu"],
    "05-20": ["Conis"],
    "05-21": ["Gotti"],
    "05-22": ["Decalvan Brothers", "Lindbergh"],
    "05-23": ["Chew"],
    "05-24": ["Carrot"],
    "05-25": ["Big Pan"],
    "05-26": ["Kohza"],
    "05-27": ["Stansen", "Koze"],
    "05-28": ["Cat-car"],
    "05-29": ["Diamante"],
    "05-30": ["Kyuin"],
    "05-31": ["Lacuba"],
    "06-01": ["St. Charloss", "Moda"],
    "06-02": ["Chimney", "Rob Lucci", "Ronse"],
    "06-03": ["Mousse", "Dragon #13"],
    "06-04": ["Epoida", "Crocus", "Raijin"],
    "06-05": ["Jabra", "Sicily"],
    "06-06": ["Karma", "Momonga", "Sheepshead"],
    "06-07": ["Perona"],
    "06-08": ["Saldeath", "Lacroix"],
    "06-09": ["Surume", "Rockstar"],
    "06-10": ["Dalton", "Portgas D. Rouge"],
    "06-11": ["Shiliew"],
    "06-12": ["Señor Pink", "Disco"],
    "06-13": ["Ripper"],
    "06-14": ["Chabo", "Candy", "Kawamatsu"],
    "06-15": ["Belo Betty", "Roshio"],
    "06-16": ["Pedro"],
    "06-17": ["Toto", "Genzo", "Tamachibi"],
    "06-18": ["Rika"],
    "06-19": ["Mr. 4", "Rokkaku", "Tibany"],
    "06-20": ["Amadob"],
    "06-21": ["Ms. Father’s Day"],
    "06-22": ["Gyro"],
    "06-23": ["Orlumbus"],
    "06-24": ["Ryuuboshi"],
    "06-25": ["Charlotte Pudding"],
    "06-26": ["Zeus"],
    "06-27": ["Riku Dold III"],
    "06-28": ["St. Roswald", "Mocha"],
    "06-29": ["Fukuro", "Pankuuta Dakeyan"],
    "06-30": ["Elmy"],
    "07-01": ["Nako", "Batchee", "Mansion Guards", "Kabu"],
    "07-02": ["Minister of the Left"],
    "07-03": ["Nami", "Neptune", "Fish Nami"],
    "07-04": ["Caribou"],
    "07-05": ["Vergo"],
    "07-06": ["Namur", "Lucky Roo"],
    "07-07": ["Laki"],
    "07-08": ["Daruma", "Paulie"],
    "07-09": ["Vinsmoke Sora"],
    "07-10": ["Kamakiri", "Ramba"],
    "07-11": ["Pearl", "Blue Fan"],
    "07-12": ["Sarkies"],
    "07-13": ["King Baum", "Acrobatic Fuwas", "Queen"],
    "07-14": ["Morgans", "Bastille"],
    "07-15": ["Corazon"],
    "07-16": ["Seto", "Helmeppo"],
    "07-17": ["Hammond"],
    "07-18": ["Smiley", "Hoicael", "Michael", "Wire", "Nugire Yainu"],
    "07-19": ["Prometheus", "Yu"],
    "07-20": ["Ham Burger", "Chess", "Pansy", "Giovanni"],
    "07-21": ["Kanjuro"],
    "07-22": ["Charlotte Prim", "Charlotte Praline"],
    "07-23": ["Richie"],
    "07-24": ["Leo"],
    "07-25": ["Nojiko"],
    "07-26": ["Mr. 5"],
    "07-27": ["Thalassa Lucas", "Kikyo"],
    "07-28": ["Flapper", "Hustle"],
    "07-29": ["Kadar", "Panda Shark"],
    "07-30": ["Ms. Doublefinger"],
    "07-31": ["Sarie Nantokanette"],
    "08-01": ["Aphelandra", "Urouge", "Bishamon"],
    "08-02": ["Époni", "Yasopp"],
    "08-03": ["Inazuma", "Blackbeard", "Hanzo"],
    "08-04": ["Amazon", "Boss of the Earth", "Rebecca"],
    "08-05": ["Octopako", "Gaimon", "Vasco Shot"],
    "08-06": ["Gladius", "Gomorrah", "Sodom", "Blenheim"],
    "08-07": ["Kaku", "Bellamy"],
    "08-08": ["Buggy", "Hatchan", "Yazaemon"],
    "08-09": ["Hack", "Wapol", "Vegapunk"],
    "08-10": ["Fujitora", "Gedatsu", "Hattori"],
    "08-11": ["Duval", "Dellinger"],
    "08-12": ["Hajrudin"],
    "08-13": ["Don Sai", "Machvise"],
    "08-14": ["Giberson", "Jean Ango", "Bomba", "Pisaro"],
    "08-15": ["Dr. Tsukimi", "Bentham"],
    "08-16": ["Akainu"],
    "08-17": ["Matsuge", "Pagaya"],
    "08-18": ["Wiper"],
    "08-19": ["Motobaro"],
    "08-20": ["Boo"],
    "08-21": ["Pound", "Take", "Holdem"],
    "08-22": ["Vander Decken IX"],
    "08-23": ["Pell"],
    "08-24": ["Kaya", "Daigin"],
    "08-25": ["Corgi"],
    "08-26": ["Gyatz"],
    "08-27": ["Monet"],
    "08-28": ["Hannyabal"],
    "08-29": ["Farul", "Panda Shark"],
    "08-30": ["Curly Dadan"],
    "08-31": ["Cavendish"],
    "09-01": ["Kiwi", "Jewelry Bonney", "Delacuaji"],
    "09-02": ["Heppoko", "Peppoko", "Poppoko", "Boa Hancock"],
    "09-03": ["Brannew", "Boa Sandersonia", "Mcguy"],
    "09-04": ["Kumashi", "Wanze"],
    "09-05": ["Crocodile", "Boa Marigold"],
    "09-06": ["Gekko Moriah", "Squard", "Macro"],
    "09-07": ["Fullbody", "Motzel"],
    "09-08": ["Cabaji", "Rakuyo", "Kureha"],
    "09-09": ["Shyarly", "Basil Hawkins", "Manjaro", "O-Kiku"],
    "09-10": ["T-Bone", "Very Good"],
    "09-11": ["Mont Blanc Cricket", "Morley"],
    "09-12": ["Curiel"],
    "09-13": ["Hoe"],
    "09-14": ["Lord of the Coast"],
    "09-15": ["Spoil", "O-Tsuru"],
    "09-16": ["Laboon", "Rindo"],
    "09-17": ["Kuina"],
    "09-18": ["Devil Dias", "Karasu"],
    "09-19": ["Don Krieg"],
    "09-20": ["Shura"],
    "09-21": ["Aokiji", "Pappag", "Chocolat"],
    "09-22": ["Kyros"],
    "09-23": ["Umit", "Hanger", "Orochi"],
    "09-24": ["Suu", "Jean Goen", "Black Maria"],
    "09-25": ["Terracotta"],
    "09-26": ["Dagama", "Cosmos"],
    "09-27": ["Mr. 9"],
    "09-28": ["Jack", "Stalker"],
    "09-29": [
        "Charlotte Opera",
        "Charlotte Counter",
        "Charlotte Cadenza",
        "Charlotte Cabaletta",
        "Charlotte Gala",
        "Drug Peclo",
        "Pinky",
    ],
    "09-30": ["Avalo Pizarro"],
    "10-01": ["Comile", "Mohji"],
    "10-02": ["Dorry", "Tonjit"],
    "10-03": ["Yama"],
    "10-04": ["Oars", "Calgara", "Shandia Chief"],
    "10-05": ["Van Augur", "Kokoro", "Marco", "Monkey D. Dragon", "O-Toko"],
    "10-06": ["Tashigi", "Trafalgar D. Water Law", "Bartolomeo"],
    "10-07": ["Lao G", "Kouzuki Momonosuke"],
    "10-08": ["Doberman", "Pierre", "Hatcha"],
    "10-09": ["Dosun", "Magellan", "Mont Blanc Noland"],
    "10-10": ["Den", "Stomp", "Braham", "Ideo"],
    "10-11": ["Inuarashi"],
    "10-12": ["Charlotte Smoothie", "Charlotte Citron", "Charlotte Cinnamon"],
    "10-13": ["Izou"],
    "10-14": ["Haredas"],
    "10-15": ["Charlotte Compote", "Mornin", "Charlotte Yuen"],
    "10-16": ["Taroimo"],
    "10-17": ["Noble Croc", "Marin"],
    "10-18": ["Doc Q", "Jigoku Benten"],
    "10-19": [
        "Charlotte Galette",
        "Charlotte Poire",
        "Sea Bunny",
        "Charlotte Anglais",
    ],
    "10-20": ["Tyrannosaurus"],
    "10-21": ["Vito", "Sam"],
    "10-22": ["Sugar", "Drip"],
    "10-23": ["Donquixote Doflamingo", "Shinobu"],
    "10-24": ["X Drake"],
    "10-25": ["Kuroobi", "Koala"],
    "10-26": ["Belladonna", "Denjiro"],
    "10-27": ["Kagikko"],
    "10-28": ["Scarlet"],
    "10-29": ["Charlotte Snack", "Charlotte Bavarois", "Turco"],
    "10-30": ["Domino", "Magra"],
    "10-31": ["Sherrie", "Whitey Bay", "Monstar"],
    "11-01": ["Dalmatian", "Wanda"],
    "11-02": ["Marie", "Judy", "Koncelot"],
    "11-03": ["Camie", "Yamato"],
    "11-04": ["Kashigami"],
    "11-05": ["Fisher Tiger"],
    "11-06": ["Ryuuma"],
    "11-07": ["Holy", "Cocoa"],
    "11-08": ["Carue", "Shamba"],
    "11-09": ["Albion", "St. Jalmack", "Benn Beckman"],
    "11-10": ["Yosaku"],
    "11-11": ["Jozu", "Zeo", "Soro", "Roronoa Zoro"],
    "11-12": ["Johnny"],
    "11-13": ["Kingdew"],
    "11-14": ["Raideen", "Negikuma Maria", "Coffee Monkeys"],
    "11-15": ["Ririka"],
    "11-16": ["Porche"],
    "11-17": [
        "Charlotte Mobile",
        "Charlotte Marble",
        "Charlotte Myukuru",
        "Charlotte Maple",
        "Moodie",
    ],
    "11-18": ["Higuma"],
    "11-19": ["Brontosaurus", "Onimaru"],
    "11-20": ["Bepo"],
    "11-21": ["Mummy Mee", "Mr. 11"],
    "11-22": ["Shushu", "Nekomamushi"],
    "11-23": ["Ankoro", "Kizaru", "Kentauros"],
    "11-24": ["Ran"],
    "11-25": ["Charlotte Katakuri", "Charlotte Daifuku", "Charlotte Oven"],
    "11-26": ["Goro"],
    "11-27": ["Blue Gilly"],
    "11-28": ["Tank Lepanto"],
    "11-29": ["Agyo", "Cerberus", "Bacura"],
    "11-30": ["Vinsmoke Reiju"],
    "12-01": ["Heat", "Ipponume"],
    "12-02": [
        "Napoleon",
        "Kaneshiro",
        "Charlotte Newichi",
        "Charlotte Newji",
        "Charlotte Newsan",
        "Charlotte Newshi",
        "Charlotte Newgo",
        "Charlotte Nutmeg",
        "Charlotte Akimeg",
        "Charlotte Allmeg",
        "Charlotte Harumeg",
        "Charlotte Fuyumeg",
    ],
    "12-03": ["Bell-mère"],
    "12-04": ["Jorl"],
    "12-05": ["Indigo"],
    "12-06": ["Igaram"],
    "12-07": ["Ikkaku", "Yuda Snakes"],
    "12-08": ["Jarl", "Maskeredomo Bird"],
    "12-09": ["Tacos", "Packy", "Kelly Funk"],
    "12-10": [
        "Edward Weevil",
        "Charlotte Mondée",
        "Charlotte Amande",
        "Charlotte Hachée",
        "Charlotte Effilée",
    ],
    "12-11": ["The Yeti Cool Brothers", "Mr. Shimizu", "Speed"],
    "12-12": ["Don Chinjao", "Nezumi", "King"],
    "12-13": ["St. Mjosgard", "Faust"],
    "12-14": ["Pica"],
    "12-15": ["Charlotte Noisette", "Nerine"],
    "12-16": [
        "Inuppe",
        "Charlotte Moscato",
        "Charlotte Mash",
        "Charlotte Cornstarch",
    ],
    "12-17": ["Banchina", "Yuki"],
    "12-18": ["Zunisha", "Byron"],
    "12-19": ["Hogback", "Dogra"],
    "12-20": ["Charlotte Mozart", "Charlotte Marnier", "Louis Arnote"],
    "12-21": ["Mother Carmel"],
    "12-22": ["Gan Fall", "Miyagi"],
    "12-23": ["Kouzuki Hiyori"],
    "12-24": ["Tony Tony Chopper"],
    "12-25": ["Jesus Burgess", "Ms. Merry Christmas"],
    "12-26": ["Charlotte Broyé", "Mashikaku"],
    "12-27": ["Lines", "Akumai"],
    "12-28": ["Jango"],
    "12-29": ["Du Feld"],
    "12-30": ["Absalom"],
    "12-31": ["Gol D. Roger"],
}

def main(config):
    location = config.get("location") or DEFAULT_LOCATION
    loc = json.decode(location)
    timezone = loc["timezone"]
    now_date = time.now().in_location(timezone).format("01-02")

    characters = ",\n".join(birthdays[str(now_date)])

    header_text = ""
    marquee_alignment = ""
    if "," in characters:
        header_text = "Birthdays Of:"
        marquee_alignment = "left"
    else:
        header_text = "Birthday Of:"
        marquee_alignment = "center"

    return render.Root(
        delay = 150,
        child = render.Column(
            cross_align = "start",
            children = [
                render.Box(
                    color = HEADER_BACKGROUND,
                    height = 9,
                    child = render.Text(
                        content = header_text,
                        font = "tb-8",
                        color = HEADER_TEXT,
                    ),
                ),
                render.Box(
                    height = 23,
                    child = render.Marquee(
                        height = 23,
                        child = render.WrappedText(
                            content = characters,
                            width = 64,
                            align = marquee_alignment,
                        ),
                        scroll_direction = "vertical",
                    ),
                ),
            ],
        ),
    )

def get_schema():
    return schema.Schema(
        version = "1",
        fields = [
            schema.Location(
                id = "location",
                name = "Location",
                desc = "Location for which to set time zone.",
                icon = "locationDot",
            ),
        ],
    )
