"""
Applet: National Rail
Summary: Live UK train departures
Description: Realtime departure board information from National Rail Enquiries.
Author: dinosaursrarr
"""

load("cache.star", "cache")
load("encoding/json.star", "json")
load("http.star", "http")
load("render.star", "render")
load("schema.star", "schema")
load("secret.star", "secret")
load("xpath.star", "xpath")

# Used to query Darwin to get live train information.
# Allows 5000 requests per hour (~1.38 qps) for free. Can buy more if needed.
ENCRYPTED_DARWIN_APP_KEY = "AV6+xWcEpjb3YSvq0m3DedNFUrniZqd3qLkIUYz5+HhnX5/bJa681u67XiPHyzH0uBBMcNXh7LJGYtRIcJLKAwWByZ3VOL0VP5jRhX4KY4aq1/sMwKr7X+VokgXMYE2Ci6gqAGdd9xWPejcnVa9F3lIpwRIutikv0TVmY0PJXCqQejyYiEHwozEl"
DARWIN_SOAP_URL = "https://lite.realtime.nationalrail.co.uk/OpenLDBWS/ldb9.asmx"

# Filters for trains that call at a given station, if selected. This is an excerpt
# to be added into a request XML.
DEPARTURES_FILTER = """
         <ldb:filterCrs>%s</ldb:filterCrs>
         <ldb:filterType>to</ldb:filterType>
"""

# Basic request. I know with SOAP you're meant to generate code based on a description
# file, but it's hideous and there don't seem to be any solutions for starlark, and the
# options for golang are poor too. So, just hook this together because we're only ever
# asking for something simple.
DEPARTURES_REQUEST = """
<soap:Envelope
    xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
    xmlns:typ="http://thalesgroup.com/RTTI/2013-11-28/Token/types"
    xmlns:ldb="http://thalesgroup.com/RTTI/2016-02-16/ldb/">
   <soap:Header>
      <typ:AccessToken>
         <typ:TokenValue>%s</typ:TokenValue>
      </typ:AccessToken>
   </soap:Header>
   <soap:Body>
      <ldb:GetDepBoardWithDetailsRequest>
         <ldb:numRows>4</ldb:numRows>
         <ldb:crs>%s</ldb:crs>%s
      </ldb:GetDepBoardWithDetailsRequest>
   </soap:Body>
</soap:Envelope>
"""

EMPTY_DATA_IN_CACHE = ""
NO_DESTINATION = "-"
ORIGIN_STATION = "origin_station"
DESTINATION_STATION = "destination_station"
DISPLAY_MODE = "display_mode"
DISPLAY_DETAILED = "display_detailed"
DISPLAY_COMPACT = "display_compact"

BLUE = "#1c355e"
RED = "#d3212c"
GREEN = "#69b34c"
GRAY = "#999"
ORANGE = "#ffa500"
FONT = "tom-thumb"
INFO_TOGGLE_FRAMES = 50

STATIONS = {
    "ABW": "Abbey Wood",
    "ABE": "Aber",
    "ACY": "Abercynon",
    "ABA": "Aberdare",
    "ABD": "Aberdeen",
    "AUR": "Aberdour",
    "AVY": "Aberdovey",
    "ABH": "Abererch",
    "AGV": "Abergavenny",
    "AGL": "Abergele & Pensarn",
    "AYW": "Aberystwyth",
    "ACR": "Accrington",
    "AAT": "Achanalt",
    "ACN": "Achnasheen",
    "ACH": "Achnashellach",
    "ACK": "Acklington",
    "ACL": "Acle",
    "ACG": "Acocks Green",
    "ACB": "Acton Bridge (Cheshire)",
    "ACC": "Acton Central",
    "AML": "Acton Main Line",
    "ADD": "Adderley Park",
    "ADW": "Addiewell",
    "ASN": "Addlestone",
    "ADM": "Adisham",
    "ADC": "Adlington (Cheshire)",
    "ADL": "Adlington (Lancs)",
    "AWK": "Adwick",
    "AIG": "Aigburth",
    "ANS": "Ainsdale",
    "AIN": "Aintree",
    "AIR": "Airbles",
    "ADR": "Airdrie",
    "AYP": "Albany Park",
    "ALB": "Albrighton",
    "ALD": "Alderley Edge",
    "AMT": "Aldermaston",
    "AHT": "Aldershot",
    "AGT": "Aldrington",
    "AAP": "Alexandra Palace",
    "AXP": "Alexandra Parade",
    "ALX": "Alexandria",
    "ALF": "Alfreton",
    "ALW": "Allens West",
    "ALO": "Alloa",
    "ASS": "Alness",
    "ALM": "Alnmouth",
    "ALR": "Alresford (Essex)",
    "ASG": "Alsager",
    "ALN": "Althorne (Essex)",
    "ALP": "Althorpe",
    "ABC": "Altnabreac",
    "AON": "Alton",
    "ALT": "Altrincham",
    "ALV": "Alvechurch",
    "AMB": "Ambergate",
    "AMY": "Amberley",
    "AMR": "Amersham",
    "AMF": "Ammanford",
    "ANC": "Ancaster",
    "AND": "Anderston",
    "ADV": "Andover",
    "ANZ": "Anerley",
    "ANG": "Angmering",
    "ANN": "Annan",
    "ANL": "Anniesland",
    "AFV": "Ansdell & Fairhaven",
    "APY": "Apperley Bridge",
    "APP": "Appleby",
    "APD": "Appledore (Kent)",
    "APF": "Appleford",
    "APB": "Appley Bridge",
    "APS": "Apsley",
    "ARB": "Arbroath",
    "ARD": "Ardgay",
    "AUI": "Ardlui",
    "ADS": "Ardrossan Harbour",
    "ASB": "Ardrossan South Beach",
    "ADN": "Ardrossan Town",
    "ADK": "Ardwick",
    "AGS": "Argyle Street",
    "ARG": "Arisaig",
    "ARL": "Arlesey",
    "ARM": "Armadale (West Lothian)",
    "AWT": "Armathwaite",
    "ARN": "Arnside",
    "ARR": "Arram",
    "ART": "Arrochar & Tarbet",
    "ARU": "Arundel",
    "ACT": "Ascot (Berks)",
    "AUW": "Ascott-under-Wychwood",
    "ASH": "Ash",
    "AHV": "Ash Vale",
    "ABY": "Ashburys",
    "ASC": "Ashchurch for Tewkesbury",
    "ASF": "Ashfield",
    "AFS": "Ashford (Surrey)",
    "AFK": "Ashford International",
    "ASI": "Ashford International (Eurostar)",
    "ASY": "Ashley",
    "AHD": "Ashtead",
    "AHN": "Ashton-under-Lyne",
    "AHS": "Ashurst (Kent)",
    "ANF": "Ashurst New Forest",
    "AWM": "Ashwell & Morden",
    "ASK": "Askam",
    "ALK": "Aslockton",
    "ASP": "Aspatria",
    "APG": "Aspley Guise",
    "AST": "Aston",
    "ATH": "Atherstone",
    "ATN": "Atherton",
    "ATT": "Attadale",
    "ATB": "Attenborough",
    "ATL": "Attleborough",
    "AUK": "Auchinleck",
    "AUD": "Audley End",
    "AUG": "Aughton Park",
    "AVM": "Aviemore",
    "AVF": "Avoncliff",
    "AVN": "Avonmouth",
    "AXM": "Axminster",
    "AYS": "Aylesbury",
    "AVP": "Aylesbury Vale Parkway",
    "AYL": "Aylesford",
    "AYH": "Aylesham",
    "AYR": "Ayr",
    "BAC": "Bache",
    "BAJ": "Baglan",
    "BAG": "Bagshot",
    "BLD": "Baildon",
    "BIO": "Baillieston",
    "BAB": "Balcombe",
    "BDK": "Baldock",
    "BAL": "Balham",
    "BHC": "Balloch",
    "BSI": "Balmossie",
    "BMB": "Bamber Bridge",
    "BAM": "Bamford",
    "BNV": "Banavie",
    "BAN": "Banbury",
    "BNG": "Bangor (Gwynedd)",
    "BAH": "Bank Hall",
    "BAD": "Banstead",
    "BSS": "Barassie",
    "ZBB": "Barbican",
    "BLL": "Bardon Mill",
    "BAR": "Bare Lane",
    "BGI": "Bargeddie",
    "BGD": "Bargoed",
    "BKG": "Barking",
    "BRT": "Barlaston",
    "BMG": "Barming",
    "BRM": "Barmouth",
    "BNH": "Barnehurst",
    "BNS": "Barnes",
    "BNI": "Barnes Bridge",
    "BTB": "Barnetby",
    "BAA": "Barnham",
    "BNL": "Barnhill",
    "BNY": "Barnsley",
    "BNP": "Barnstaple",
    "BTG": "Barnt Green",
    "BRR": "Barrhead",
    "BRL": "Barrhill",
    "BAV": "Barrow Haven",
    "BIF": "Barrow-in-Furness",
    "BWS": "Barrow-Upon-Soar",
    "BRY": "Barry",
    "BYD": "Barry Docks",
    "BYI": "Barry Island",
    "BYL": "Barry Links",
    "BAU": "Barton-on-Humber",
    "BSO": "Basildon",
    "BSK": "Basingstoke",
    "BBL": "Bat & Ball",
    "BTH": "Bath Spa",
    "BHG": "Bathgate",
    "BTL": "Batley",
    "BTT": "Battersby",
    "BAK": "Battersea Park",
    "BAT": "Battle",
    "BLB": "Battlesbridge",
    "BAY": "Bayford",
    "BCF": "Beaconsfield",
    "BER": "Bearley",
    "BRN": "Bearsden",
    "BSD": "Bearsted",
    "BSL": "Beasdale",
    "BEU": "Beaulieu Road",
    "BEL": "Beauly",
    "BEB": "Bebington",
    "BCC": "Beccles",
    "BEC": "Beckenham Hill",
    "BKJ": "Beckenham Junction",
    "BDM": "Bedford",
    "BSJ": "Bedford St Johns",
    "BDH": "Bedhampton",
    "BMT": "Bedminster",
    "BEH": "Bedworth",
    "BDW": "Bedwyn",
    "BEE": "Beeston",
    "BKS": "Bekesbourne",
    "BLV": "Belle Vue",
    "BLG": "Bellgrove",
    "BGM": "Bellingham",
    "BLH": "Bellshill",
    "BLM": "Belmont",
    "BLP": "Belper",
    "BEG": "Beltring",
    "BVD": "Belvedere",
    "BEM": "Bempton",
    "BEY": "Ben Rhydding",
    "BEF": "Benfleet",
    "BEN": "Bentham",
    "BTY": "Bentley (Hants)",
    "BYK": "Bentley (South Yorks)",
    "BAS": "Bere Alston",
    "BFE": "Bere Ferrers",
    "BKM": "Berkhamsted",
    "BKW": "Berkswell",
    "BEP": "Bermuda Park",
    "BYA": "Berney Arms",
    "BBW": "Berry Brow",
    "BRS": "Berrylands",
    "BRK": "Berwick (Sussex)",
    "BWK": "Berwick-upon-Tweed",
    "BES": "Bescar Lane",
    "BSC": "Bescot Stadium",
    "BTO": "Betchworth",
    "BET": "Bethnal Green",
    "BYC": "Betws-y-Coed",
    "BEV": "Beverley",
    "BEX": "Bexhill",
    "BXY": "Bexley",
    "BXH": "Bexleyheath",
    "BCS": "Bicester North",
    "BIT": "Bicester Village",
    "BKL": "Bickley",
    "BID": "Bidston",
    "BIW": "Biggleswade",
    "BBK": "Bilbrook",
    "BIC": "Billericay",
    "BIL": "Billingham (Cleveland)",
    "BIG": "Billingshurst",
    "BIN": "Bingham",
    "BIY": "Bingley",
    "BCG": "Birchgrove",
    "BCH": "Birchington-on-sea",
    "BWD": "Birchwood",
    "BIK": "Birkbeck",
    "BDL": "Birkdale",
    "BKC": "Birkenhead Central",
    "BKQ": "Birkenhead Hamilton Square",
    "BKN": "Birkenhead North",
    "BKP": "Birkenhead Park",
    "BHI": "Birmingham International",
    "BMO": "Birmingham Moor Street",
    "BHM": "Birmingham New Street",
    "BSW": "Birmingham Snow Hill",
    "BIA": "Bishop Auckland",
    "BBG": "Bishopbriggs",
    "BIS": "Bishops Stortford",
    "BIP": "Bishopstone (Sussex)",
    "BPT": "Bishopton (Strathclyde)",
    "BTE": "Bitterne",
    "BBN": "Blackburn",
    "BKH": "Blackheath",
    "BHO": "Blackhorse Road",
    "BPN": "Blackpool North",
    "BPB": "Blackpool Pleasure Beach",
    "BPS": "Blackpool South",
    "BKR": "Blackridge",
    "BLK": "Blackrod",
    "BAW": "Blackwater",
    "BFF": "Blaenau Ffestiniog",
    "BLA": "Blair Atholl",
    "BAI": "Blairhill",
    "BKT": "Blake Street",
    "BKD": "Blakedown",
    "BLT": "Blantyre",
    "BLO": "Blaydon",
    "BSB": "Bleasby",
    "BLY": "Bletchley",
    "BLX": "Bloxwich",
    "BWN": "Bloxwich North",
    "BLN": "Blundellsands & Crosby",
    "BYB": "Blythe Bridge",
    "BOD": "Bodmin Parkway",
    "BOR": "Bodorgan",
    "BOG": "Bognor Regis",
    "BGS": "Bogston",
    "BON": "Bolton",
    "BTD": "Bolton-Upon-Dearne",
    "BKA": "Bookham",
    "BOC": "Bootle (Cumbria)",
    "BNW": "Bootle New Strand",
    "BOT": "Bootle Oriel Road",
    "BBS": "Bordesley",
    "BRG": "Borough Green & Wrotham",
    "BRH": "Borth",
    "BOH": "Bosham",
    "BSN": "Boston",
    "BOE": "Botley",
    "BTF": "Bottesford",
    "BNE": "Bourne End",
    "BMH": "Bournemouth",
    "BRV": "Bournville",
    "BWB": "Bow Brickhill",
    "BOP": "Bowes Park",
    "BWG": "Bowling",
    "BXW": "Box Hill & Westhumble",
    "BCE": "Bracknell",
    "BDQ": "Bradford Forster Square",
    "BDI": "Bradford Interchange",
    "BOA": "Bradford-on-Avon",
    "BDN": "Brading",
    "BTR": "Braintree",
    "BTP": "Braintree Freeport",
    "BML": "Bramhall",
    "BMY": "Bramley (Hants)",
    "BLE": "Bramley (W Yorks)",
    "BMP": "Brampton (Cumbria)",
    "BRP": "Brampton (Suffolk)",
    "BCN": "Branchton",
    "BND": "Brandon",
    "BSM": "Branksome",
    "BYS": "Braystones (Cumbria)",
    "BDY": "Bredbury",
    "BRC": "Breich",
    "BFD": "Brentford",
    "BRE": "Brentwood",
    "BWO": "Bricket Wood",
    "BEA": "Bridge of Allan",
    "BRO": "Bridge of Orchy",
    "BGN": "Bridgend",
    "BDG": "Bridgeton",
    "BWT": "Bridgwater",
    "BDT": "Bridlington",
    "BRF": "Brierfield",
    "BGG": "Brigg",
    "BGH": "Brighouse",
    "BTN": "Brighton (East Sussex)",
    "BMD": "Brimsdown",
    "BNT": "Brinnington",
    "BPW": "Bristol Parkway",
    "BRI": "Bristol Temple Meads",
    "BHD": "Brithdir",
    "BNF": "Briton Ferry",
    "BRX": "Brixton",
    "BGE": "Broad Green",
    "BDB": "Broadbottom",
    "BSR": "Broadstairs",
    "BCU": "Brockenhurst",
    "BHS": "Brockholes",
    "BCY": "Brockley",
    "BOM": "Bromborough",
    "BMR": "Bromborough Rake",
    "BMC": "Bromley Cross (Lancs)",
    "BMN": "Bromley North",
    "BMS": "Bromley South",
    "BMV": "Bromsgrove",
    "BSY": "Brondesbury",
    "BSP": "Brondesbury Park",
    "BPK": "Brookmans Park",
    "BKO": "Brookwood",
    "BME": "Broome",
    "BMF": "Broomfleet",
    "BRA": "Brora",
    "BUH": "Brough",
    "BYF": "Broughty Ferry",
    "BXB": "Broxbourne",
    "BCV": "Bruce Grove",
    "BDA": "Brundall",
    "BGA": "Brundall Gardens",
    "BSU": "Brunstane",
    "BRW": "Brunswick",
    "BRU": "Bruton",
    "BYN": "Bryn",
    "BUC": "Buckenham (Norfolk)",
    "BCK": "Buckley",
    "BUK": "Bucknell",
    "BSV": "Buckshaw Parkway",
    "BGL": "Bugle",
    "BHR": "Builth Road",
    "BLW": "Bulwell",
    "BUE": "Bures",
    "BUG": "Burgess Hill",
    "BUY": "Burley Park",
    "BUW": "Burley-in-Wharfedale",
    "BNA": "Burnage",
    "BUD": "Burneside (Cumbria)",
    "BNM": "Burnham (Bucks)",
    "BUU": "Burnham-on-Crouch",
    "BUB": "Burnley Barracks",
    "BNC": "Burnley Central",
    "BYM": "Burnley Manchester Road",
    "BUI": "Burnside (Strathclyde)",
    "BTS": "Burntisland",
    "BCB": "Burscough Bridge",
    "BCJ": "Burscough Junction",
    "BUO": "Bursledon",
    "BUJ": "Burton Joyce",
    "BUT": "Burton-on-Trent",
    "BSE": "Bury St Edmunds",
    "BUS": "Busby",
    "BHK": "Bush Hill Park",
    "BSH": "Bushey",
    "BUL": "Butlers Lane",
    "BXD": "Buxted",
    "BUX": "Buxton",
    "BFN": "Byfleet & New Haw",
    "BYE": "Bynea",
    "CAD": "Cadoxton",
    "CGW": "Caergwrle",
    "CPH": "Caerphilly",
    "CWS": "Caersws",
    "CAC": "Caldercruix",
    "CDT": "Caldicot",
    "CIR": "Caledonian Rd & Barnsbury",
    "CSK": "Calstock",
    "CDU": "Cam & Dursley",
    "CAM": "Camberley",
    "CBN": "Camborne",
    "CBG": "Cambridge",
    "CBH": "Cambridge Heath",
    "CMB": "Cambridge North",
    "CBL": "Cambuslang",
    "CMD": "Camden Road",
    "CMO": "Camelon",
    "ZCW": "Canada Water",
    "CNL": "Canley",
    "CAO": "Cannock",
    "CNN": "Canonbury",
    "CBE": "Canterbury East",
    "CBW": "Canterbury West",
    "CNY": "Cantley",
    "CPU": "Capenhurst",
    "CBB": "Carbis Bay",
    "CDD": "Cardenden",
    "CDB": "Cardiff Bay",
    "CDF": "Cardiff Central",
    "CDQ": "Cardiff Queen Street",
    "CDO": "Cardonald",
    "CDR": "Cardross",
    "CRF": "Carfin",
    "CAK": "Cark & Cartmel",
    "CAR": "Carlisle",
    "CTO": "Carlton",
    "CLU": "Carluke",
    "CMN": "Carmarthen",
    "CML": "Carmyle",
    "CNF": "Carnforth",
    "CAN": "Carnoustie",
    "CAY": "Carntyne",
    "CPK": "Carpenders Park",
    "CAG": "Carrbridge",
    "CSH": "Carshalton",
    "CSB": "Carshalton Beeches",
    "CRS": "Carstairs",
    "CDY": "Cartsdyke",
    "CBP": "Castle Bar Park",
    "CLC": "Castle Cary",
    "CFD": "Castleford",
    "CAS": "Castleton (Manchester)",
    "CSM": "Castleton Moor",
    "CAT": "Caterham",
    "CTF": "Catford",
    "CFB": "Catford Bridge",
    "CYS": "Cathays",
    "CCT": "Cathcart",
    "CTL": "Cattal",
    "CAU": "Causeland",
    "CYB": "Cefn-y-Bedd",
    "CTH": "Chadwell Heath",
    "CFH": "Chafford Hundred Lakeside",
    "CFO": "Chalfont & Latimer",
    "CHW": "Chalkwell",
    "CFR": "Chandlers Ford",
    "CEF": "Chapel-en-le-Frith",
    "CPN": "Chapelton (Devon)",
    "CLN": "Chapeltown (South Yorks)",
    "CWC": "Chappel & Wakes Colne",
    "CHG": "Charing (Kent)",
    "CHC": "Charing Cross (Glasgow)",
    "CBY": "Charlbury",
    "CTN": "Charlton",
    "CRT": "Chartham",
    "CSR": "Chassen Road",
    "CTE": "Chatelherault",
    "CTM": "Chatham",
    "CHT": "Chathill",
    "CHU": "Cheadle Hulme",
    "CHE": "Cheam",
    "CED": "Cheddington",
    "CEL": "Chelford (Cheshire)",
    "CHM": "Chelmsford",
    "CLD": "Chelsfield",
    "CNM": "Cheltenham Spa",
    "CPW": "Chepstow",
    "CYT": "Cherry Tree",
    "CHY": "Chertsey",
    "CHN": "Cheshunt",
    "CSN": "Chessington North",
    "CSS": "Chessington South",
    "CTR": "Chester",
    "CRD": "Chester Road",
    "CHD": "Chesterfield",
    "CLS": "Chester-le-Street",
    "CSW": "Chestfield & Swalecliffe",
    "CNO": "Chetnole",
    "CCH": "Chichester",
    "CIL": "Chilham",
    "CHL": "Chilworth",
    "CHI": "Chingford",
    "CLY": "Chinley",
    "CPM": "Chippenham",
    "CHP": "Chipstead",
    "CRK": "Chirk",
    "CIT": "Chislehurst",
    "CHK": "Chiswick",
    "CHO": "Cholsey",
    "CRL": "Chorley",
    "CLW": "Chorleywood",
    "CHR": "Christchurch",
    "CHH": "Christs Hospital",
    "CTW": "Church & Oswaldtwistle",
    "CHF": "Church Fenton",
    "CTT": "Church Stretton",
    "CIM": "Cilmeri",
    "CTK": "City Thameslink",
    "CLT": "Clacton-on-Sea",
    "CLA": "Clandon",
    "CPY": "Clapham (North Yorkshire)",
    "CLP": "Clapham High Street",
    "CLJ": "Clapham Junction",
    "CPT": "Clapton",
    "CLR": "Clarbeston Road",
    "CKS": "Clarkston",
    "CLV": "Claverdon",
    "CLG": "Claygate",
    "CLE": "Cleethorpes",
    "CEA": "Cleland",
    "CLI": "Clifton (Manchester)",
    "CFN": "Clifton Down",
    "CLH": "Clitheroe",
    "CLK": "Clock House",
    "CUW": "Clunderwen",
    "CYK": "Clydebank",
    "CBC": "Coatbridge Central",
    "CBS": "Coatbridge Sunnyside",
    "COA": "Coatdyke",
    "CSD": "Cobham & Stoke d'Abernon",
    "CSL": "Codsall",
    "CGN": "Cogan",
    "COL": "Colchester",
    "CET": "Colchester Town",
    "CEH": "Coleshill Parkway",
    "CLM": "Collingham",
    "CLL": "Collington",
    "CNE": "Colne",
    "CWL": "Colwall",
    "CWB": "Colwyn Bay",
    "CME": "Combe (Oxon)",
    "COM": "Commondale",
    "CNG": "Congleton",
    "CNS": "Conisbrough",
    "CON": "Connel Ferry",
    "CBD": "Conon Bridge",
    "CEY": "Cononley",
    "CNP": "Conway Park",
    "CNW": "Conwy",
    "COB": "Cooden Beach",
    "COO": "Cookham",
    "CBR": "Cooksbridge",
    "COE": "Coombe Junction Halt",
    "COP": "Copplestone",
    "CRB": "Corbridge",
    "COR": "Corby",
    "CFC": "Corfe Castle",
    "CKH": "Corkerhill",
    "CKL": "Corkickle",
    "CPA": "Corpach",
    "CRR": "Corrour",
    "COY": "Coryton",
    "CSY": "Coseley",
    "COS": "Cosford",
    "CSA": "Cosham",
    "CGM": "Cottingham",
    "COT": "Cottingley",
    "CDS": "Coulsdon South",
    "CDN": "Coulsdon Town",
    "COV": "Coventry",
    "CAA": "Coventry Arena",
    "CWN": "Cowden (Kent)",
    "COW": "Cowdenbeath",
    "CRA": "Cradley Heath",
    "CGD": "Craigendoran",
    "CRM": "Cramlington",
    "CBK": "Cranbrook (Devon)",
    "CRV": "Craven Arms",
    "CRW": "Crawley",
    "CRY": "Crayford",
    "CDI": "Crediton",
    "CES": "Cressing (Essex)",
    "CSG": "Cressington",
    "CWD": "Creswell",
    "CRE": "Crewe",
    "CKN": "Crewkerne",
    "CWH": "Crews Hill",
    "CNR": "Crianlarich",
    "CCC": "Criccieth",
    "CRI": "Cricklewood",
    "CFF": "Croftfoot",
    "CFT": "Crofton Park",
    "CMR": "Cromer",
    "CMF": "Cromford",
    "CKT": "Crookston",
    "CRG": "Cross Gates",
    "CFL": "Crossflatts",
    "COI": "Crosshill",
    "CKY": "Crosskeys",
    "CMY": "Crossmyloof",
    "CSO": "Croston",
    "CRH": "Crouch Hill",
    "COH": "Crowborough",
    "CWU": "Crowhurst",
    "CWE": "Crowle",
    "CRN": "Crowthorne",
    "CRO": "Croy",
    "CYP": "Crystal Palace",
    "CUD": "Cuddington",
    "CUF": "Cuffley",
    "CUM": "Culham",
    "CUA": "Culrain",
    "CUB": "Cumbernauld",
    "CUP": "Cupar",
    "CUH": "Curriehill",
    "CUX": "Cuxton",
    "CMH": "Cwmbach",
    "CWM": "Cwmbran",
    "CYN": "Cynghordy",
    "DDK": "Dagenham Dock",
    "DSY": "Daisy Hill",
    "DAG": "Dalgety Bay",
    "DAL": "Dalmally",
    "DAK": "Dalmarnock",
    "DAM": "Dalmeny",
    "DMR": "Dalmuir",
    "DLR": "Dalreoch",
    "DLY": "Dalry",
    "DLS": "Dalston (Cumbria)",
    "DLJ": "Dalston Junction",
    "DLK": "Dalston Kingsland",
    "DLT": "Dalton (Cumbria)",
    "DLW": "Dalwhinnie",
    "DNY": "Danby",
    "DCT": "Danescourt",
    "DZY": "Danzey",
    "DAR": "Darlington",
    "DAN": "Darnall",
    "DSM": "Darsham",
    "DFD": "Dartford",
    "DRT": "Darton",
    "DWN": "Darwen",
    "DAT": "Datchet",
    "DVN": "Davenport",
    "DWL": "Dawlish",
    "DWW": "Dawlish Warren",
    "DEA": "Deal",
    "DEN": "Dean (Wilts)",
    "DGT": "Deansgate",
    "DGY": "Deganwy",
    "DHN": "Deighton",
    "DLM": "Delamere",
    "DBD": "Denby Dale",
    "DNM": "Denham",
    "DGC": "Denham Golf Club",
    "DMK": "Denmark Hill",
    "DNT": "Dent",
    "DTN": "Denton",
    "DEP": "Deptford",
    "DBY": "Derby",
    "DBR": "Derby Road (Ipswich)",
    "DPT": "Devonport (Devon)",
    "DOC": "Devonport Dockyard",
    "DEW": "Dewsbury",
    "DID": "Didcot Parkway",
    "DIG": "Digby & Sowton",
    "DMH": "Dilton Marsh",
    "DMG": "Dinas (Rhondda)",
    "DNS": "Dinas Powys",
    "DGL": "Dingle Road",
    "DIN": "Dingwall",
    "DND": "Dinsdale",
    "DTG": "Dinting",
    "DSL": "Disley",
    "DIS": "Diss",
    "DOD": "Dodworth",
    "DOL": "Dolau",
    "DLH": "Doleham",
    "DLG": "Dolgarrog",
    "DWD": "Dolwyddelan",
    "DON": "Doncaster",
    "DCH": "Dorchester South",
    "DCW": "Dorchester West",
    "DOR": "Dore & Totley",
    "DKG": "Dorking (Main)",
    "DPD": "Dorking Deepdene",
    "DKT": "Dorking West",
    "DMS": "Dormans",
    "DDG": "Dorridge",
    "DVH": "Dove Holes",
    "DVP": "Dover Priory",
    "DVC": "Dovercourt",
    "DVY": "Dovey Junction",
    "DOW": "Downham Market",
    "DRG": "Drayton Green",
    "DYP": "Drayton Park",
    "DRM": "Drem",
    "DRF": "Driffield",
    "DRI": "Drigg",
    "DTW": "Droitwich Spa",
    "DRO": "Dronfield",
    "DMC": "Drumchapel",
    "DFR": "Drumfrochar",
    "DRU": "Drumgelloch",
    "DMY": "Drumry",
    "DFP": "Dublin Ferryport",
    "DPS": "Dublin Port - Stena",
    "DUD": "Duddeston",
    "DDP": "Dudley Port",
    "DFI": "Duffield",
    "DRN": "Duirinish",
    "DST": "Duke Street",
    "DUL": "Dullingham",
    "DBC": "Dumbarton Central",
    "DBE": "Dumbarton East",
    "DUM": "Dumbreck",
    "DMF": "Dumfries",
    "DMP": "Dumpton Park",
    "DUN": "Dunbar",
    "DBL": "Dunblane",
    "DCG": "Duncraig",
    "DEE": "Dundee",
    "DFL": "Dunfermline Queen Margaret",
    "DFE": "Dunfermline Town",
    "DKD": "Dunkeld & Birnam",
    "DNL": "Dunlop",
    "DNO": "Dunrobin Castle",
    "DOT": "Dunston",
    "DNG": "Dunton Green",
    "DHM": "Durham",
    "DUR": "Durrington-on-Sea",
    "DYC": "Dyce",
    "DYF": "Dyffryn Ardudwy",
    "EAG": "Eaglescliffe",
    "EAL": "Ealing Broadway",
    "ERL": "Earlestown",
    "EAR": "Earley",
    "EAD": "Earlsfield",
    "ELD": "Earlswood (Surrey)",
    "EWD": "Earlswood (West Midlands)",
    "ECR": "East Croydon",
    "EDY": "East Didsbury",
    "EDW": "East Dulwich",
    "EFL": "East Farleigh",
    "EGF": "East Garforth",
    "EGR": "East Grinstead",
    "EKL": "East Kilbride",
    "EML": "East Malling",
    "EMD": "East Midlands Parkway",
    "ETL": "East Tilbury",
    "EWR": "East Worthing",
    "EBN": "Eastbourne",
    "EBK": "Eastbrook",
    "EST": "Easterhouse",
    "ERA": "Eastham Rake",
    "ESL": "Eastleigh",
    "EGN": "Eastrington",
    "EBD": "Ebbsfleet International",
    "EBV": "Ebbw Vale Parkway",
    "EBB": "Ebbw Vale Town",
    "ECC": "Eccles (Manchester)",
    "ECS": "Eccles Road",
    "ECL": "Eccleston Park",
    "EDL": "Edale",
    "EDN": "Eden Park",
    "EBR": "Edenbridge",
    "EBT": "Edenbridge Town",
    "EDG": "Edge Hill",
    "EDB": "Edinburgh",
    "EGY": "Edinburgh Gateway",
    "EDP": "Edinburgh Park",
    "EDR": "Edmonton Green",
    "EFF": "Effingham Junction",
    "EGG": "Eggesford",
    "EGH": "Egham",
    "EGT": "Egton",
    "EPH": "Elephant & Castle",
    "ZEL": "Elephant & Castle (Underground)",
    "ELG": "Elgin",
    "ELP": "Ellesmere Port",
    "ELE": "Elmers End",
    "ESD": "Elmstead Woods",
    "ESW": "Elmswell",
    "ELR": "Elsecar",
    "ESM": "Elsenham (Essex)",
    "ELS": "Elstree & Borehamwood",
    "ELW": "Eltham",
    "ELO": "Elton & Orston",
    "ELY": "Ely",
    "EMP": "Emerson Park",
    "EMS": "Emsworth",
    "ECP": "Energlyn & Churchill Park",
    "ENC": "Enfield Chase",
    "ENL": "Enfield Lock",
    "ENF": "Enfield Town",
    "ENT": "Entwistle",
    "EPS": "Epsom (Surrey)",
    "EPD": "Epsom Downs",
    "ERD": "Erdington",
    "ERI": "Eridge",
    "ERH": "Erith",
    "ESH": "Esher",
    "EKB": "Eskbank",
    "EXR": "Essex Road",
    "ETC": "Etchingham",
    "EBA": "Euxton Balshaw Lane",
    "EVE": "Evesham",
    "EWE": "Ewell East",
    "EWW": "Ewell West",
    "EXC": "Exeter Central",
    "EXD": "Exeter St David's",
    "EXT": "Exeter St Thomas",
    "EXG": "Exhibition Centre (Glasgow)",
    "EXM": "Exmouth",
    "EXN": "Exton",
    "EYN": "Eynsford",
    "FRB": "Fairbourne",
    "FRF": "Fairfield",
    "FRL": "Fairlie",
    "FRW": "Fairwater",
    "FCN": "Falconwood",
    "FKG": "Falkirk Grahamston",
    "FKK": "Falkirk High",
    "FOC": "Falls of Cruachan",
    "FMR": "Falmer",
    "FAL": "Falmouth Docks",
    "FMT": "Falmouth Town",
    "FRM": "Fareham",
    "FNB": "Farnborough (Main)",
    "FNN": "Farnborough North",
    "FNC": "Farncombe",
    "FNH": "Farnham",
    "FNR": "Farningham Road",
    "FNW": "Farnworth",
    "ZFD": "Farringdon",
    "FLD": "Fauldhouse",
    "FAV": "Faversham",
    "FGT": "Faygate",
    "FAZ": "Fazakerley",
    "FRN": "Fearn",
    "FEA": "Featherstone",
    "FLX": "Felixstowe",
    "FEL": "Feltham",
    "FNT": "Feniton",
    "FEN": "Fenny Stratford",
    "FER": "Fernhill",
    "FRY": "Ferriby",
    "FYS": "Ferryside",
    "FFA": "Ffairfach",
    "FIL": "Filey",
    "FIT": "Filton Abbey Wood",
    "FNY": "Finchley Road & Frognal",
    "FPK": "Finsbury Park",
    "FIN": "Finstock",
    "FSB": "Fishbourne (Sussex)",
    "FSG": "Fishersgate",
    "FGW": "Fishguard & Goodwick",
    "FGH": "Fishguard Harbour",
    "FSK": "Fiskerton",
    "FZW": "Fitzwilliam",
    "FWY": "Five Ways",
    "FLE": "Fleet",
    "FLM": "Flimby",
    "FLN": "Flint",
    "FLT": "Flitwick",
    "FLI": "Flixton",
    "FLF": "Flowery Field",
    "FKC": "Folkestone Central",
    "FKW": "Folkestone West",
    "FOD": "Ford",
    "FOG": "Forest Gate",
    "FOH": "Forest Hill",
    "FBY": "Formby",
    "FOR": "Forres",
    "FRS": "Forsinard",
    "FTM": "Fort Matilda",
    "FTW": "Fort William",
    "FOK": "Four Oaks",
    "FOX": "Foxfield",
    "FXN": "Foxton",
    "FRT": "Frant",
    "FTN": "Fratton",
    "FRE": "Freshfield",
    "FFD": "Freshford",
    "FML": "Frimley",
    "FRI": "Frinton-on-Sea",
    "FZH": "Frizinghall",
    "FRD": "Frodsham",
    "FRO": "Frome",
    "FLW": "Fulwell",
    "FNV": "Furness Vale",
    "FZP": "Furze Platt",
    "GNB": "Gainsborough Central",
    "GBL": "Gainsborough Lea Road",
    "GAL": "Galashiels",
    "GCH": "Garelochhead",
    "GRF": "Garforth",
    "GGV": "Gargrave",
    "GAR": "Garrowhill",
    "GRS": "Garscadden",
    "GSD": "Garsdale",
    "GSN": "Garston (Hertfordshire)",
    "GSW": "Garswood",
    "GRH": "Gartcosh",
    "GMG": "Garth (Mid Glamorgan)",
    "GTH": "Garth (Powys)",
    "GVE": "Garve",
    "GST": "Gathurst",
    "GTY": "Gatley",
    "GTW": "Gatwick Airport",
    "GGJ": "Georgemas Junction",
    "GER": "Gerrards Cross",
    "GDP": "Gidea Park",
    "GFN": "Giffnock",
    "GIG": "Giggleswick",
    "GBD": "Gilberdyke",
    "GFF": "Gilfach Fargoed",
    "GIL": "Gillingham (Dorset)",
    "GLM": "Gillingham (Kent)",
    "GSC": "Gilshochill",
    "GIP": "Gipsy Hill",
    "GIR": "Girvan",
    "GLS": "Glaisdale",
    "GCW": "Glan Conwy",
    "GLC": "Glasgow Central",
    "GLQ": "Glasgow Queen Street",
    "GLH": "Glasshoughton",
    "GLZ": "Glazebrook",
    "GLE": "Gleneagles",
    "GLF": "Glenfinnan",
    "GLG": "Glengarnock",
    "GLT": "Glenrothes with Thornton",
    "GLO": "Glossop",
    "GCR": "Gloucester",
    "GLY": "Glynde",
    "GOB": "Gobowen",
    "GOD": "Godalming",
    "GDL": "Godley",
    "GDN": "Godstone",
    "GOE": "Goldthorpe",
    "GOF": "Golf Street",
    "GOL": "Golspie",
    "GOM": "Gomshall",
    "GMY": "Goodmayes",
    "GOO": "Goole",
    "GTR": "Goostrey",
    "GDH": "Gordon Hill",
    "GBG": "Gorebridge",
    "GOR": "Goring & Streatley",
    "GBS": "Goring-by-Sea",
    "GTO": "Gorton",
    "GPO": "Gospel Oak",
    "GRK": "Gourock",
    "GWN": "Gowerton",
    "GOX": "Goxhill",
    "GPK": "Grange Park",
    "GOS": "Grange-Over-Sands",
    "GTN": "Grangetown (Cardiff)",
    "GRA": "Grantham",
    "GRT": "Grateley",
    "GVH": "Gravelly Hill",
    "GRV": "Gravesend",
    "GRY": "Grays",
    "GTA": "Great Ayton",
    "GRB": "Great Bentley",
    "GRC": "Great Chesterford",
    "GCT": "Great Coates",
    "GMV": "Great Malvern",
    "GMN": "Great Missenden",
    "GYM": "Great Yarmouth",
    "GNL": "Green Lane",
    "GNR": "Green Road",
    "GBK": "Greenbank",
    "GRL": "Greenfaulds",
    "GNF": "Greenfield",
    "GFD": "Greenford",
    "GNH": "Greenhithe",
    "GKC": "Greenock Central",
    "GKW": "Greenock West",
    "GNW": "Greenwich",
    "GEA": "Gretna Green",
    "GMD": "Grimsby Docks",
    "GMB": "Grimsby Town",
    "GRN": "Grindleford",
    "GMT": "Grosmont",
    "GRP": "Grove Park",
    "GUI": "Guide Bridge",
    "GLD": "Guildford",
    "GSY": "Guiseley",
    "GUN": "Gunnersbury",
    "GSL": "Gunnislake",
    "GNT": "Gunton",
    "GWE": "Gwersyllt",
    "GYP": "Gypsy Lane",
    "HAB": "Habrough",
    "HCB": "Hackbridge",
    "HKC": "Hackney Central",
    "HAC": "Hackney Downs",
    "HKW": "Hackney Wick",
    "HDM": "Haddenham & Thame Parkway",
    "HAD": "Haddiscoe",
    "HDF": "Hadfield",
    "HDW": "Hadley Wood",
    "HGF": "Hag Fold",
    "HGG": "Haggerston",
    "HAG": "Hagley",
    "HMY": "Hairmyres",
    "HAL": "Hale (Manchester)",
    "HAS": "Halesworth",
    "HED": "Halewood",
    "HFX": "Halifax",
    "HLG": "Hall Green",
    "HLR": "Hall Road",
    "HAI": "Halling",
    "HID": "Hall-i'-th'-Wood",
    "HWH": "Haltwhistle",
    "HMT": "Ham Street",
    "HME": "Hamble",
    "HNC": "Hamilton Central",
    "HNW": "Hamilton West",
    "HMM": "Hammerton",
    "HMD": "Hampden Park (Sussex)",
    "HDH": "Hampstead Heath",
    "HMP": "Hampton (London)",
    "HMC": "Hampton Court",
    "HMW": "Hampton Wick",
    "HIA": "Hampton-in-Arden",
    "HSD": "Hamstead (Birmingham)",
    "HAM": "Hamworthy",
    "HND": "Hanborough",
    "HTH": "Handforth",
    "HAN": "Hanwell",
    "HPN": "Hapton",
    "HRL": "Harlech",
    "HDN": "Harlesden",
    "HRD": "Harling Road",
    "HLN": "Harlington (Beds)",
    "HWM": "Harlow Mill",
    "HWN": "Harlow Town",
    "HRO": "Harold Wood",
    "HPD": "Harpenden",
    "HRM": "Harrietsham",
    "HGY": "Harringay",
    "HRY": "Harringay Green Lanes",
    "HRR": "Harrington",
    "HGT": "Harrogate",
    "HRW": "Harrow & Wealdstone",
    "HOH": "Harrow-on-the-Hill",
    "HTF": "Hartford (Cheshire)",
    "HBY": "Hartlebury",
    "HPL": "Hartlepool",
    "HTW": "Hartwood",
    "HPQ": "Harwich International",
    "HWC": "Harwich Town",
    "HSL": "Haslemere",
    "HSK": "Hassocks",
    "HGS": "Hastings",
    "HTE": "Hatch End",
    "HFS": "Hatfield & Stainforth",
    "HAT": "Hatfield (Herts)",
    "HAP": "Hatfield Peverel",
    "HSG": "Hathersage",
    "HTY": "Hattersley",
    "HTN": "Hatton",
    "HAV": "Havant",
    "HVN": "Havenhouse",
    "HVF": "Haverfordwest",
    "HWD": "Hawarden",
    "HWB": "Hawarden Bridge",
    "HKH": "Hawkhead",
    "HDB": "Haydon Bridge",
    "HYR": "Haydons Road",
    "HAY": "Hayes & Harlington",
    "HYS": "Hayes (Kent)",
    "HYL": "Hayle",
    "HYM": "Haymarket",
    "HHE": "Haywards Heath",
    "HAZ": "Hazel Grove",
    "HCN": "Headcorn",
    "HDY": "Headingley",
    "HDL": "Headstone Lane",
    "HDG": "Heald Green",
    "HLI": "Healing",
    "HHL": "Heath High Level",
    "HLL": "Heath Low Level",
    "HAF": "Heathrow Airport Terminal 4",
    "HWV": "Heathrow Airport Terminal 5",
    "HXX": "Heathrow Airport Terminals 1, 2 and 3",
    "HTC": "Heaton Chapel",
    "HBD": "Hebden Bridge",
    "HEC": "Heckington",
    "HDE": "Hedge End",
    "HNF": "Hednesford",
    "HEI": "Heighington",
    "HLC": "Helensburgh Central",
    "HLU": "Helensburgh Upper",
    "HLD": "Hellifield",
    "HMS": "Helmsdale",
    "HSB": "Helsby",
    "HML": "Hemel Hempstead",
    "HEN": "Hendon",
    "HNG": "Hengoed",
    "HNL": "Henley-in-Arden",
    "HOT": "Henley-on-Thames",
    "HEL": "Hensall",
    "HFD": "Hereford",
    "HNB": "Herne Bay",
    "HNH": "Herne Hill",
    "HER": "Hersham",
    "HFE": "Hertford East",
    "HFN": "Hertford North",
    "HES": "Hessle",
    "HSW": "Heswall",
    "HEV": "Hever",
    "HEW": "Heworth",
    "HEX": "Hexham",
    "HYD": "Heyford",
    "HHB": "Heysham Port",
    "HIB": "High Brooms",
    "HST": "High Street (Glasgow)",
    "ZHS": "High Street Kensington Underground",
    "HWY": "High Wycombe",
    "HGM": "Higham (Kent)",
    "HIP": "Highams Park",
    "HIG": "Highbridge & Burnham",
    "HHY": "Highbury & Islington",
    "HTO": "Hightown",
    "HLB": "Hildenborough",
    "HLF": "Hillfoot",
    "HLE": "Hillington East",
    "HLW": "Hillington West",
    "HIL": "Hillside",
    "HLS": "Hilsea",
    "HYW": "Hinchley Wood",
    "HNK": "Hinckley (Leics)",
    "HIN": "Hindley",
    "HNA": "Hinton Admiral",
    "HIT": "Hitchin",
    "HGR": "Hither Green",
    "HOC": "Hockley",
    "HBN": "Hollingbourne",
    "HCH": "Holmes Chapel",
    "HLM": "Holmwood",
    "HOL": "Holton Heath",
    "HHD": "Holyhead",
    "HLY": "Holytown",
    "HMN": "Homerton",
    "HYB": "Honeybourne",
    "HON": "Honiton",
    "HOY": "Honley",
    "HPA": "Honor Oak Park",
    "HOK": "Hook",
    "HOO": "Hooton",
    "HOP": "Hope (Derbyshire)",
    "HPE": "Hope (Flintshire)",
    "HPT": "Hopton Heath",
    "HRE": "Horden",
    "HOR": "Horley",
    "HBP": "Hornbeam Park",
    "HRN": "Hornsey",
    "HRS": "Horsforth",
    "HRH": "Horsham",
    "HSY": "Horsley",
    "HIR": "Horton-in-Ribblesdale",
    "HWI": "Horwich Parkway",
    "HSC": "Hoscar",
    "HGN": "Hough Green",
    "HOU": "Hounslow",
    "HOV": "Hove",
    "HXM": "Hoveton & Wroxham",
    "HWW": "How Wood (Herts)",
    "HOW": "Howden",
    "HOZ": "Howwood (Renfrewshire)",
    "HOX": "Hoxton",
    "HYK": "Hoylake",
    "HBB": "Hubberts Bridge",
    "HKN": "Hucknall",
    "HUD": "Huddersfield",
    "HUL": "Hull",
    "HUP": "Humphrey Park",
    "HCT": "Huncoat",
    "HGD": "Hungerford",
    "HUB": "Hunmanby",
    "HUN": "Huntingdon",
    "HNT": "Huntly",
    "HNX": "Hunts Cross",
    "HUR": "Hurst Green",
    "HUT": "Hutton Cranswick",
    "HUY": "Huyton",
    "HYC": "Hyde Central",
    "HYT": "Hyde North",
    "HKM": "Hykeham",
    "HYN": "Hyndland",
    "HYH": "Hythe (Essex)",
    "IBM": "IBM Halt",
    "IFI": "Ifield",
    "IFD": "Ilford",
    "ILN": "Ilkeston",
    "ILK": "Ilkley",
    "IMW": "Imperial Wharf",
    "INE": "Ince & Elton",
    "INC": "Ince (Manchester)",
    "INT": "Ingatestone",
    "INS": "Insch",
    "IGD": "Invergordon",
    "ING": "Invergowrie",
    "INK": "Inverkeithing",
    "INP": "Inverkip",
    "INV": "Inverness",
    "INH": "Invershin",
    "INR": "Inverurie",
    "IPS": "Ipswich",
    "IRL": "Irlam",
    "IRV": "Irvine",
    "ISL": "Isleworth",
    "ISP": "Islip",
    "IVR": "Iver",
    "IVY": "Ivybridge",
    "JCH": "James Cook",
    "JEQ": "Jewellery Quarter",
    "JOH": "Johnston (Pembs)",
    "JHN": "Johnstone (Strathclyde)",
    "JOR": "Jordanhill",
    "KSL": "Kearsley (Manchester)",
    "KSN": "Kearsney (Kent)",
    "KEI": "Keighley",
    "KEH": "Keith",
    "KEL": "Kelvedon",
    "KVD": "Kelvindale",
    "KEM": "Kemble",
    "KMH": "Kempston Hardwick",
    "KMP": "Kempton Park Racecourse",
    "KMS": "Kemsing",
    "KML": "Kemsley",
    "KEN": "Kendal",
    "KNW": "Kenilworth",
    "KLY": "Kenley",
    "KNE": "Kennett",
    "KNS": "Kennishead",
    "KNL": "Kensal Green",
    "KNR": "Kensal Rise",
    "KPA": "Kensington Olympia",
    "KTH": "Kent House",
    "KTN": "Kentish Town",
    "KTW": "Kentish Town West",
    "KNT": "Kenton",
    "KBK": "Kents Bank",
    "KET": "Kettering",
    "KWB": "Kew Bridge",
    "KWG": "Kew Gardens",
    "KEY": "Keyham",
    "KYN": "Keynsham",
    "KDB": "Kidbrooke",
    "KID": "Kidderminster",
    "KDG": "Kidsgrove",
    "KWL": "Kidwelly",
    "KBN": "Kilburn High Road",
    "KLD": "Kildale",
    "KIL": "Kildonan",
    "KGT": "Kilgetty",
    "KMK": "Kilmarnock",
    "KLM": "Kilmaurs",
    "KPT": "Kilpatrick",
    "KWN": "Kilwinning",
    "KBC": "Kinbrace",
    "KGM": "Kingham",
    "KGH": "Kinghorn",
    "KGL": "Kings Langley",
    "KLN": "Kings Lynn",
    "KNN": "Kings Norton",
    "KGN": "Kings Nympton",
    "KGP": "Kings Park",
    "KGS": "Kings Sutton",
    "KGE": "Kingsknowe",
    "KNG": "Kingston",
    "KND": "Kingswood",
    "KIN": "Kingussie",
    "KIT": "Kintbury",
    "KBX": "Kirby Cross",
    "KKS": "Kirk Sandall",
    "KIR": "Kirkby (Merseyside)",
    "KSW": "Kirkby Stephen",
    "KKB": "Kirkby-in-Ashfield",
    "KBF": "Kirkby-in-Furness",
    "KDY": "Kirkcaldy",
    "KRK": "Kirkconnel",
    "KKD": "Kirkdale",
    "KKM": "Kirkham & Wesham",
    "KKH": "Kirkhill",
    "KKN": "Kirknewton",
    "KLF": "Kirkstall Forge",
    "KWD": "Kirkwood",
    "KTL": "Kirton Lindsey",
    "KIV": "Kiveton Bridge",
    "KVP": "Kiveton Park",
    "KNA": "Knaresborough",
    "KBW": "Knebworth",
    "KNI": "Knighton",
    "KCK": "Knockholt",
    "KNO": "Knottingley",
    "KNU": "Knucklas",
    "KNF": "Knutsford",
    "KYL": "Kyle of Lochalsh",
    "LDY": "Ladybank",
    "LAD": "Ladywell",
    "LAI": "Laindon",
    "LRG": "Lairg",
    "LKE": "Lake",
    "LAK": "Lakenheath",
    "LAM": "Lamphey",
    "LNK": "Lanark",
    "LAN": "Lancaster",
    "LAC": "Lancing",
    "LAW": "Landywood",
    "LGB": "Langbank",
    "LHO": "Langho",
    "LNY": "Langley (Berks)",
    "LGG": "Langley Green",
    "LGM": "Langley Mill",
    "LGS": "Langside",
    "LGW": "Langwathby",
    "LAG": "Langwith-Whaley Thorns",
    "LAP": "Lapford",
    "LPW": "Lapworth",
    "LBT": "Larbert",
    "LAR": "Largs",
    "LRH": "Larkhall",
    "LAU": "Laurencekirk",
    "LWH": "Lawrence Hill",
    "LAY": "Layton (Lancs)",
    "LZB": "Lazonby & Kirkoswald",
    "LEB": "Lea Bridge",
    "LEG": "Lea Green",
    "LEH": "Lea Hall",
    "LEA": "Leagrave",
    "LHM": "Lealholm",
    "LMS": "Leamington Spa",
    "LSW": "Leasowe",
    "LHD": "Leatherhead",
    "LED": "Ledbury",
    "LEE": "Lee (London)",
    "LDS": "Leeds",
    "LEI": "Leicester",
    "LIH": "Leigh (Kent)",
    "LES": "Leigh-on-Sea",
    "LBZ": "Leighton Buzzard",
    "LEL": "Lelant",
    "LTS": "Lelant Saltings",
    "LEN": "Lenham",
    "LNZ": "Lenzie",
    "LEO": "Leominster",
    "LET": "Letchworth Garden City",
    "LEU": "Leuchars (for St. Andrews)",
    "LVM": "Levenshulme",
    "LWS": "Lewes",
    "LEW": "Lewisham",
    "LEY": "Leyland",
    "LEM": "Leyton Midland Road",
    "LER": "Leytonstone High Road",
    "LIC": "Lichfield City",
    "LTV": "Lichfield Trent Valley",
    "LID": "Lidlington",
    "LHS": "Limehouse",
    "LCN": "Lincoln Central",
    "LFD": "Lingfield",
    "LGD": "Lingwood",
    "LIN": "Linlithgow",
    "LIP": "Liphook",
    "LSK": "Liskeard",
    "LIS": "Liss",
    "LVT": "Lisvane & Thornhill",
    "LTK": "Little Kimble",
    "LTT": "Little Sutton",
    "LTL": "Littleborough",
    "LIT": "Littlehampton",
    "LVN": "Littlehaven",
    "LTP": "Littleport",
    "LVC": "Liverpool Central",
    "LVJ": "Liverpool James Street",
    "LIV": "Liverpool Lime Street",
    "LPY": "Liverpool South Parkway",
    "LSN": "Livingston North",
    "LVG": "Livingston South",
    "LLA": "Llanaber",
    "LBR": "Llanbedr",
    "LLT": "Llanbister Road",
    "LNB": "Llanbradach",
    "LLN": "Llandaf",
    "LDN": "Llandanwg",
    "LLC": "Llandecwyn",
    "LLL": "Llandeilo",
    "LLV": "Llandovery",
    "LLO": "Llandrindod",
    "LLD": "Llandudno",
    "LLJ": "Llandudno Junction",
    "LLI": "Llandybie",
    "LLE": "Llanelli",
    "LLF": "Llanfairfechan",
    "LPG": "Llanfairpwll",
    "LLG": "Llangadog",
    "LLM": "Llangammarch",
    "LLH": "Llangennech",
    "LGO": "Llangynllo",
    "LLR": "Llanharan",
    "LTH": "Llanhilleth",
    "LLS": "Llanishen",
    "LWR": "Llanrwst",
    "LAS": "Llansamlet",
    "LWM": "Llantwit Major",
    "LNR": "Llanwrda",
    "LNW": "Llanwrtyd",
    "LLW": "Llwyngwril",
    "LLY": "Llwynypia",
    "LHA": "Loch Awe",
    "LHE": "Loch Eil Outward Bound",
    "LCL": "Lochailort",
    "LCS": "Locheilside",
    "LCG": "Lochgelly",
    "LCC": "Lochluichart",
    "LHW": "Lochwinnoch",
    "LOC": "Lockerbie",
    "LCK": "Lockwood",
    "BFR": "London Blackfriars",
    "LBG": "London Bridge",
    "CST": "London Cannon Street",
    "CHX": "London Charing Cross",
    "EUS": "London Euston",
    "FST": "London Fenchurch Street",
    "LOF": "London Fields",
    "KGX": "London Kings Cross",
    "LST": "London Liverpool Street",
    "MYB": "London Marylebone",
    "PAD": "London Paddington",
    "LRB": "London Road (Brighton)",
    "LRD": "London Road (Guildford)",
    "SPX": "London St Pancras (Intl)",
    "STP": "London St Pancras International",
    "VIC": "London Victoria",
    "WAT": "London Waterloo",
    "WAE": "London Waterloo East",
    "LBK": "Long Buckby",
    "LGE": "Long Eaton",
    "LPR": "Long Preston",
    "LGK": "Longbeck",
    "LOB": "Longbridge",
    "LNG": "Longcross",
    "LGF": "Longfield",
    "LND": "Longniddry",
    "LPT": "Longport",
    "LGN": "Longton",
    "LOO": "Looe",
    "LOT": "Lostock",
    "LTG": "Lostock Gralam",
    "LOH": "Lostock Hall",
    "LOS": "Lostwithiel",
    "LBO": "Loughborough",
    "LGJ": "Loughborough Junction",
    "LMR": "Low Moor",
    "LOW": "Lowdham",
    "LSY": "Lower Sydenham",
    "LWT": "Lowestoft",
    "LUD": "Ludlow",
    "LUT": "Luton",
    "LTN": "Luton Airport Parkway",
    "LUX": "Luxulyan",
    "LYD": "Lydney",
    "LYE": "Lye (West Midlands)",
    "LYP": "Lymington Pier",
    "LYT": "Lymington Town",
    "LYC": "Lympstone Commando",
    "LYM": "Lympstone Village",
    "LTM": "Lytham",
    "MAC": "Macclesfield",
    "MCN": "Machynlleth",
    "MST": "Maesteg",
    "MEW": "Maesteg (Ewenny Road)",
    "MAG": "Maghull",
    "MNS": "Maghull North",
    "MDN": "Maiden Newton",
    "MAI": "Maidenhead",
    "MDB": "Maidstone Barracks",
    "MDE": "Maidstone East",
    "MDW": "Maidstone West",
    "MAL": "Malden Manor",
    "MLG": "Mallaig",
    "MLT": "Malton",
    "MVL": "Malvern Link",
    "MIA": "Manchester Airport",
    "MCO": "Manchester Oxford Road",
    "MAN": "Manchester Piccadilly",
    "MUF": "Manchester United Football Ground",
    "MCV": "Manchester Victoria",
    "MNE": "Manea",
    "MNG": "Manningtree",
    "MNP": "Manor Park",
    "MNR": "Manor Road",
    "MRB": "Manorbier",
    "MAS": "Manors",
    "MFT": "Mansfield",
    "MSW": "Mansfield Woodhouse",
    "MCH": "March",
    "MRN": "Marden (Kent)",
    "MAR": "Margate",
    "MHR": "Market Harborough",
    "MKR": "Market Rasen",
    "MNC": "Markinch",
    "MKT": "Marks Tey",
    "MLW": "Marlow",
    "MPL": "Marple",
    "MSN": "Marsden (Yorks)",
    "MSK": "Marske",
    "MGN": "Marston Green",
    "MTM": "Martin Mill",
    "MAO": "Martins Heron",
    "MTO": "Marton",
    "MYH": "Maryhill",
    "MYL": "Maryland",
    "MRY": "Maryport",
    "MAT": "Matlock",
    "MTB": "Matlock Bath",
    "MAU": "Mauldeth Road",
    "MAX": "Maxwell Park",
    "MAY": "Maybole",
    "MZH": "Maze Hill",
    "MHS": "Meadowhall",
    "MEL": "Meldreth",
    "MKM": "Melksham",
    "MES": "Melton (Suffolk)",
    "MMO": "Melton Mowbray",
    "MEN": "Menheniot",
    "MNN": "Menston",
    "MEO": "Meols",
    "MEC": "Meols Cop",
    "MEP": "Meopham",
    "MRW": "Meridian Water",
    "MEY": "Merryton",
    "MHM": "Merstham",
    "MER": "Merthyr Tydfil",
    "MEV": "Merthyr Vale",
    "MGM": "Metheringham",
    "MCE": "MetroCentre",
    "MEX": "Mexborough",
    "MIC": "Micheldever",
    "MIK": "Micklefield",
    "MBR": "Middlesbrough",
    "MDL": "Middlewood",
    "MDG": "Midgham",
    "MLF": "Milford (Surrey)",
    "MFH": "Milford Haven",
    "MLH": "Mill Hill (Lancs)",
    "MIL": "Mill Hill Broadway",
    "MLB": "Millbrook (Beds)",
    "MBK": "Millbrook (Hants)",
    "MIN": "Milliken Park",
    "MLM": "Millom",
    "MIH": "Mills Hill (Manchester)",
    "MLN": "Milngavie",
    "MKC": "Milton Keynes Central",
    "MFF": "Minffordd",
    "MSR": "Minster",
    "MIR": "Mirfield",
    "MIS": "Mistley",
    "MTC": "Mitcham Eastfields",
    "MIJ": "Mitcham Junction",
    "MOB": "Mobberley",
    "MON": "Monifieth",
    "MRS": "Monks Risborough",
    "MTP": "Montpelier",
    "MTS": "Montrose",
    "MRF": "Moorfields",
    "MOG": "Moorgate",
    "MSD": "Moorside",
    "MRP": "Moorthorpe",
    "MRR": "Morar",
    "MRD": "Morchard Road",
    "MDS": "Morden South",
    "MCM": "Morecambe",
    "MTN": "Moreton (Dorset)",
    "MRT": "Moreton (Merseyside)",
    "MIM": "Moreton-in-Marsh",
    "MFA": "Morfa Mawddach",
    "MLY": "Morley",
    "MPT": "Morpeth",
    "MOR": "Mortimer",
    "MTL": "Mortlake",
    "MSS": "Moses Gate",
    "MOS": "Moss Side",
    "MSL": "Mossley (Manchester)",
    "MSH": "Mossley Hill",
    "MPK": "Mosspark",
    "MSO": "Moston",
    "MTH": "Motherwell",
    "MOT": "Motspur Park",
    "MTG": "Mottingham",
    "DBG": "Mottisfont & Dunbridge",
    "MLD": "Mouldsworth",
    "MCB": "Moulsecoomb",
    "MFL": "Mount Florida",
    "MTV": "Mount Vernon",
    "MTA": "Mountain Ash",
    "MOO": "Muir of Ord",
    "MUI": "Muirend",
    "MUB": "Musselburgh",
    "MYT": "Mytholmroyd",
    "NFN": "Nafferton",
    "NLS": "Nailsea & Backwell",
    "NRN": "Nairn",
    "NAN": "Nantwich",
    "NAR": "Narberth",
    "NBR": "Narborough",
    "NVR": "Navigation Road",
    "NTH": "Neath",
    "NMT": "Needham Market",
    "NEI": "Neilston",
    "NEL": "Nelson",
    "NES": "Neston",
    "NET": "Netherfield",
    "NRT": "Nethertown",
    "NTL": "Netley",
    "NBA": "New Barnet",
    "NBC": "New Beckenham",
    "NBN": "New Brighton",
    "NCE": "New Clee",
    "NWX": "New Cross",
    "NXG": "New Cross Gate",
    "NCK": "New Cumnock",
    "NEH": "New Eltham",
    "NHL": "New Holland",
    "NHE": "New Hythe",
    "NLN": "New Lane",
    "NEM": "New Malden",
    "NMC": "New Mills Central",
    "NMN": "New Mills Newtown",
    "NWM": "New Milton",
    "NPD": "New Pudsey",
    "NSG": "New Southgate",
    "NCT": "Newark Castle",
    "NNG": "Newark North Gate",
    "NBE": "Newbridge",
    "NBY": "Newbury",
    "NRC": "Newbury Racecourse",
    "NCL": "Newcastle",
    "NCO": "Newcourt",
    "NEW": "Newcraighall",
    "NVH": "Newhaven Harbour",
    "NVN": "Newhaven Town",
    "NGT": "Newington",
    "NMK": "Newmarket",
    "NWE": "Newport (Essex)",
    "NWP": "Newport (South Wales)",
    "NQY": "Newquay",
    "NSD": "Newstead",
    "NTN": "Newton (Lanark)",
    "NTA": "Newton Abbot",
    "NAY": "Newton Aycliffe",
    "NWN": "Newton for Hyde",
    "NTC": "Newton St Cyres",
    "NEG": "Newtongrange",
    "NLW": "Newton-le-Willows",
    "NWR": "Newtonmore",
    "NOA": "Newton-on-Ayr",
    "NWT": "Newtown (Powys)",
    "NNP": "Ninian Park",
    "NIT": "Nitshill",
    "NBT": "Norbiton",
    "NRB": "Norbury",
    "NSB": "Normans Bay",
    "NOR": "Normanton",
    "NBW": "North Berwick",
    "NCM": "North Camp",
    "NDL": "North Dulwich",
    "NFA": "North Fambridge",
    "NLR": "North Llanrwst",
    "NQU": "North Queensferry",
    "NRD": "North Road (Darlington)",
    "NSH": "North Sheen",
    "NWA": "North Walsham",
    "NWB": "North Wembley",
    "NTR": "Northallerton",
    "NMP": "Northampton",
    "NFD": "Northfield",
    "NFL": "Northfleet",
    "NLT": "Northolt Park",
    "NUM": "Northumberland Park",
    "NWI": "Northwich",
    "NRW": "Norwich",
    "NWD": "Norwood Junction",
    "NOT": "Nottingham",
    "NUN": "Nuneaton",
    "NHD": "Nunhead",
    "NNT": "Nunthorpe",
    "NUT": "Nutbourne",
    "NUF": "Nutfield",
    "OKN": "Oakengates",
    "OKM": "Oakham",
    "OKL": "Oakleigh Park",
    "OBN": "Oban",
    "OCK": "Ockendon",
    "OLY": "Ockley",
    "OKE": "Okehampton",
    "OHL": "Old Hill",
    "ORN": "Old Roan",
    "OLD": "Old Street",
    "OLF": "Oldfield Park",
    "OLT": "Olton",
    "ORE": "Ore",
    "OMS": "Ormskirk",
    "ORP": "Orpington",
    "ORR": "Orrell",
    "OPK": "Orrell Park",
    "OTF": "Otford",
    "OUN": "Oulton Broad North",
    "OUS": "Oulton Broad South",
    "OUT": "Outwood",
    "OVE": "Overpool",
    "OVR": "Overton",
    "OXN": "Oxenholme Lake District",
    "OXF": "Oxford",
    "OXP": "Oxford Parkway",
    "OXS": "Oxshott",
    "OXT": "Oxted",
    "PDW": "Paddock Wood",
    "PDG": "Padgate",
    "PGN": "Paignton",
    "PCN": "Paisley Canal",
    "PYG": "Paisley Gilmour Street",
    "PYJ": "Paisley St James",
    "PAL": "Palmers Green",
    "PAN": "Pangbourne",
    "PNL": "Pannal",
    "PTF": "Pantyffynnon",
    "PAR": "Par",
    "PBL": "Parbold",
    "PKT": "Park Street",
    "PKS": "Parkstone (Dorset)",
    "PSN": "Parson Street",
    "PTK": "Partick",
    "PRN": "Parton",
    "PWY": "Patchway",
    "PAT": "Patricroft",
    "PTT": "Patterton",
    "PEA": "Peartree",
    "PMR": "Peckham Rye",
    "PEG": "Pegswood",
    "PEM": "Pemberton",
    "PBY": "Pembrey & Burry Port",
    "PMB": "Pembroke",
    "PMD": "Pembroke Dock",
    "PNA": "Penally",
    "PEN": "Penarth",
    "PCD": "Pencoed",
    "PGM": "Pengam",
    "PNE": "Penge East",
    "PNW": "Penge West",
    "PHG": "Penhelig",
    "PNS": "Penistone",
    "PKG": "Penkridge",
    "PMW": "Penmaenmawr",
    "PNM": "Penmere",
    "PER": "Penrhiwceiber",
    "PRH": "Penrhyndeudraeth",
    "PNR": "Penrith (North Lakes)",
    "PYN": "Penryn (Cornwall)",
    "PES": "Pensarn (Gwynedd)",
    "PHR": "Penshurst",
    "PTB": "Pentre-Bach",
    "PNY": "Pen-y-Bont",
    "PNC": "Penychain",
    "PNF": "Penyffordd",
    "PNZ": "Penzance",
    "PRW": "Perranwell",
    "PRY": "Perry Barr",
    "PSH": "Pershore",
    "PTH": "Perth",
    "PBO": "Peterborough",
    "PTR": "Petersfield",
    "PET": "Petts Wood",
    "PEV": "Pevensey & Westham",
    "PEB": "Pevensey Bay",
    "PEW": "Pewsey",
    "PIL": "Pilning",
    "PIN": "Pinhoe",
    "PIT": "Pitlochry",
    "PSE": "Pitsea",
    "PLS": "Pleasington",
    "PLK": "Plockton",
    "PLC": "Pluckley",
    "PLM": "Plumley",
    "PMP": "Plumpton",
    "PLU": "Plumstead",
    "PLY": "Plymouth",
    "POK": "Pokesdown",
    "PLG": "Polegate",
    "PSW": "Polesworth",
    "PWE": "Pollokshaws East",
    "PWW": "Pollokshaws West",
    "PLE": "Pollokshields East",
    "PLW": "Pollokshields West",
    "PMT": "Polmont",
    "POL": "Polsloe Bridge",
    "PON": "Ponders End",
    "PTD": "Pontarddulais",
    "PFR": "Pontefract Baghill",
    "PFM": "Pontefract Monkhill",
    "POT": "Pontefract Tanshelf",
    "PLT": "Pontlottyn",
    "PYC": "Pontyclun",
    "PYP": "Pont-y-Pant",
    "PPL": "Pontypool & New Inn",
    "PPD": "Pontypridd",
    "POO": "Poole",
    "POP": "Poppleton",
    "PTG": "Port Glasgow",
    "PSL": "Port Sunlight",
    "PTA": "Port Talbot Parkway",
    "PTC": "Portchester",
    "POR": "Porth",
    "PTM": "Porthmadog",
    "PLN": "Portlethen",
    "PLD": "Portslade",
    "PMS": "Portsmouth & Southsea",
    "PMA": "Portsmouth Arms",
    "PMH": "Portsmouth Harbour",
    "PPK": "Possilpark & Parkhouse",
    "PBR": "Potters Bar",
    "PFY": "Poulton-le-Fylde",
    "PYT": "Poynton",
    "PRS": "Prees",
    "PSC": "Prescot",
    "PRT": "Prestatyn",
    "PRB": "Prestbury",
    "PRE": "Preston (Lancs)",
    "PRP": "Preston Park",
    "PST": "Prestonpans",
    "PRA": "Prestwick International Airport",
    "PTW": "Prestwick Town",
    "PTL": "Priesthill & Darnley",
    "PRR": "Princes Risborough",
    "PRL": "Prittlewell",
    "PRU": "Prudhoe",
    "PUL": "Pulborough",
    "PFL": "Purfleet",
    "PUR": "Purley",
    "PUO": "Purley Oaks",
    "PUT": "Putney",
    "PWL": "Pwllheli",
    "PYE": "Pye Corner",
    "PYL": "Pyle",
    "QYD": "Quakers Yard",
    "QBR": "Queenborough",
    "QPK": "Queens Park (Glasgow)",
    "QPW": "Queens Park (London)",
    "QRP": "Queens Road (Peckham)",
    "QRB": "Queenstown Road (Battersea)",
    "QUI": "Quintrell Downs",
    "RDF": "Radcliffe-on-Trent",
    "RDT": "Radlett",
    "RAD": "Radley",
    "RDR": "Radyr",
    "RNF": "Rainford",
    "RNM": "Rainham (Essex)",
    "RAI": "Rainham (Kent)",
    "RNH": "Rainhill",
    "RAM": "Ramsgate",
    "RGW": "Ramsgreave & Wilpshire",
    "RAN": "Rannoch",
    "RAU": "Rauceby",
    "RAV": "Ravenglass for Eskdale",
    "RVB": "Ravensbourne",
    "RVN": "Ravensthorpe",
    "RWC": "Rawcliffe",
    "RLG": "Rayleigh",
    "RAY": "Raynes Park",
    "RDG": "Reading",
    "RDW": "Reading West",
    "REC": "Rectory Road",
    "RDB": "Redbridge",
    "RBS": "Redcar British Steel",
    "RCC": "Redcar Central",
    "RCE": "Redcar East",
    "RDN": "Reddish North",
    "RDS": "Reddish South",
    "RDC": "Redditch",
    "RDH": "Redhill",
    "RDA": "Redland",
    "RED": "Redruth",
    "REE": "Reedham (Norfolk)",
    "RHM": "Reedham (Surrey)",
    "REI": "Reigate",
    "RTN": "Renton",
    "RET": "Retford",
    "RHI": "Rhiwbina",
    "RIA": "Rhoose Cardiff International Airport",
    "RHO": "Rhosneigr",
    "RHL": "Rhyl",
    "RHY": "Rhymney",
    "RHD": "Ribblehead",
    "RIL": "Rice Lane",
    "RMD": "Richmond (London)",
    "RIC": "Rickmansworth",
    "RDD": "Riddlesdown",
    "RID": "Ridgmont",
    "RDM": "Riding Mill",
    "RCA": "Risca & Pontymister",
    "RIS": "Rishton",
    "RBR": "Robertsbridge",
    "RRN": "Robroyston",
    "ROB": "Roby",
    "RCD": "Rochdale",
    "ROC": "Roche",
    "RTR": "Rochester",
    "RFD": "Rochford",
    "RFY": "Rock Ferry",
    "ROG": "Rogart",
    "ROR": "Rogerstone",
    "ROL": "Rolleston",
    "RMB": "Roman Bridge",
    "RMF": "Romford",
    "RML": "Romiley",
    "ROM": "Romsey",
    "ROO": "Roose",
    "RSG": "Rose Grove",
    "RSH": "Rose Hill Marple",
    "ROS": "Rosyth",
    "RMC": "Rotherham Central",
    "ROE": "Rotherhithe",
    "RNR": "Roughton Road",
    "RLN": "Rowlands Castle",
    "ROW": "Rowley Regis",
    "RYB": "Roy Bridge",
    "RYN": "Roydon",
    "RYS": "Royston",
    "RUA": "Ruabon",
    "RUF": "Rufford",
    "RUG": "Rugby",
    "RGT": "Rugeley Town",
    "RGL": "Rugeley Trent Valley",
    "RUN": "Runcorn",
    "RUE": "Runcorn East",
    "RKT": "Ruskington",
    "RUS": "Ruswarp",
    "RUT": "Rutherglen",
    "RYD": "Ryde Esplanade",
    "RYP": "Ryde Pier Head",
    "RYR": "Ryde St Johns Road",
    "RRB": "Ryder Brow",
    "RYE": "Rye (Sussex)",
    "RYH": "Rye House",
    "SFD": "Salford Central",
    "SLD": "Salford Crescent",
    "SAF": "Salfords (Surrey)",
    "SAH": "Salhouse",
    "SAL": "Salisbury",
    "SAE": "Saltaire",
    "STS": "Saltash",
    "SLB": "Saltburn",
    "SLT": "Saltcoats",
    "SAM": "Saltmarshe",
    "SLW": "Salwick",
    "SMC": "Sampford Courtenay",
    "SNA": "Sandal & Agbrigg",
    "SDB": "Sandbach",
    "SNR": "Sanderstead",
    "SDL": "Sandhills",
    "SND": "Sandhurst (Berks)",
    "SDG": "Sandling",
    "SAN": "Sandown",
    "SDP": "Sandplace",
    "SAD": "Sandwell & Dudley",
    "SDW": "Sandwich",
    "SDY": "Sandy",
    "SNK": "Sankey for Penketh",
    "SQH": "Sanquhar",
    "SRR": "Sarn",
    "SDF": "Saundersfoot",
    "SDR": "Saunderton",
    "SAW": "Sawbridgeworth",
    "SXY": "Saxilby",
    "SAX": "Saxmundham",
    "SCA": "Scarborough",
    "SCT": "Scotscalder",
    "SCH": "Scotstounhill",
    "SCU": "Scunthorpe",
    "SML": "Sea Mills",
    "SEF": "Seaford (Sussex)",
    "SFL": "Seaforth & Litherland",
    "SEA": "Seaham",
    "SEM": "Seamer",
    "SSC": "Seascale",
    "SEC": "Seaton Carew",
    "SRG": "Seer Green & Jordans",
    "SBY": "Selby",
    "SRS": "Selhurst",
    "SEL": "Sellafield",
    "SEG": "Selling",
    "SLY": "Selly Oak",
    "SET": "Settle",
    "SVK": "Seven Kings",
    "SVS": "Seven Sisters",
    "SEV": "Sevenoaks",
    "SVB": "Severn Beach",
    "STJ": "Severn Tunnel Junction",
    "SDE": "Shadwell",
    "SFR": "Shalford (Surrey)",
    "SHN": "Shanklin",
    "SFI": "Shawfair",
    "SHW": "Shawford",
    "SHL": "Shawlands",
    "SSS": "Sheerness-on-Sea",
    "SHF": "Sheffield",
    "SED": "Shelford (Cambs)",
    "SNF": "Shenfield",
    "SEN": "Shenstone",
    "SPB": "Shepherd's Bush",
    "SPH": "Shepherds Well",
    "SPY": "Shepley",
    "SHP": "Shepperton",
    "STH": "Shepreth",
    "SHE": "Sherborne",
    "SIE": "Sherburn-in-Elmet",
    "SHM": "Sheringham",
    "SLS": "Shettleston",
    "SDM": "Shieldmuir",
    "SFN": "Shifnal",
    "SHD": "Shildon",
    "SHI": "Shiplake",
    "SHY": "Shipley (Yorks)",
    "SPP": "Shippea Hill",
    "SIP": "Shipton",
    "SHB": "Shirebrook",
    "SHH": "Shirehampton",
    "SRO": "Shireoaks",
    "SRL": "Shirley",
    "SRY": "Shoeburyness",
    "SHO": "Sholing",
    "SDC": "Shoreditch High Street",
    "SEH": "Shoreham (Kent)",
    "SSE": "Shoreham-by-Sea",
    "SRT": "Shortlands",
    "SHT": "Shotton",
    "SHS": "Shotts",
    "SHR": "Shrewsbury",
    "SID": "Sidcup",
    "SIL": "Sileby",
    "SIC": "Silecroft",
    "SLK": "Silkstone Common",
    "SLV": "Silver Street",
    "SVR": "Silverdale",
    "SIN": "Singer",
    "SIT": "Sittingbourne",
    "SKG": "Skegness",
    "SKE": "Skewen",
    "SKI": "Skipton",
    "SGR": "Slade Green",
    "SWT": "Slaithwaite",
    "SLA": "Slateford",
    "SLR": "Sleaford",
    "SLH": "Sleights",
    "SLO": "Slough",
    "SMA": "Small Heath",
    "SAB": "Smallbrook Junction",
    "SGB": "Smethwick Galton Bridge",
    "SMR": "Smethwick Rolfe Street",
    "SMB": "Smithy Bridge",
    "SNI": "Snaith",
    "SDA": "Snodland",
    "SWO": "Snowdown",
    "SOR": "Sole Street",
    "SOL": "Solihull",
    "SYT": "Somerleyton",
    "SAT": "South Acton",
    "SBK": "South Bank",
    "SBM": "South Bermondsey",
    "SCY": "South Croydon",
    "SES": "South Elmsall",
    "SGN": "South Greenford",
    "SGL": "South Gyle",
    "SOH": "South Hampstead",
    "SOK": "South Kenton",
    "SMO": "South Merton",
    "SOM": "South Milford",
    "SRU": "South Ruislip",
    "STO": "South Tottenham",
    "SWS": "South Wigston",
    "SOF": "South Woodham Ferrers",
    "STL": "Southall",
    "SOA": "Southampton Airport Parkway",
    "SOU": "Southampton Central",
    "SOB": "Southbourne",
    "SBU": "Southbury",
    "SEE": "Southease",
    "SIA": "Southend Airport",
    "SOC": "Southend Central",
    "SOE": "Southend East",
    "SOV": "Southend Victoria",
    "SMN": "Southminster",
    "SOP": "Southport",
    "SWK": "Southwick",
    "SOW": "Sowerby Bridge",
    "SPA": "Spalding",
    "SBR": "Spean Bridge",
    "SPI": "Spital",
    "SPO": "Spondon",
    "SPN": "Spooner Row",
    "SRI": "Spring Road",
    "SPR": "Springburn",
    "SPF": "Springfield",
    "SQU": "Squires Gate",
    "SAA": "St Albans Abbey",
    "SAC": "St Albans City",
    "SAR": "St Andrews Road",
    "SAS": "St Annes-on-Sea",
    "SAU": "St Austell",
    "SBS": "St Bees",
    "SBF": "St Budeaux Ferry Road",
    "SBV": "St Budeaux Victoria Road",
    "SCR": "St Columb Road",
    "SDN": "St Denys",
    "SER": "St Erth",
    "SGM": "St Germans",
    "SNH": "St Helens Central",
    "SHJ": "St Helens Junction",
    "SIH": "St Helier (Surrey)",
    "SIV": "St Ives (Cornwall)",
    "SJP": "St James Park (Exeter)",
    "SJS": "St James Street (Walthamstow)",
    "SAJ": "St Johns (London)",
    "SKN": "St Keyne Wishing Well Halt",
    "SLQ": "St Leonards Warrior Square",
    "SMT": "St Margarets (Herts)",
    "SMG": "St Margarets (London)",
    "SMY": "St Mary Cray",
    "STM": "St Michaels",
    "SNO": "St Neots",
    "STA": "Stafford",
    "SNS": "Staines",
    "SLL": "Stallingborough",
    "SYB": "Stalybridge",
    "SMD": "Stamford (Lincs)",
    "SMH": "Stamford Hill",
    "SFO": "Stanford-le-Hope",
    "SNT": "Stanlow & Thornton",
    "SSD": "Stansted Airport",
    "SST": "Stansted Mountfitchet",
    "SPU": "Staplehurst",
    "SRD": "Stapleton Road",
    "SBE": "Starbeck",
    "SCS": "Starcross",
    "SVL": "Staveley (Cumbria)",
    "SCF": "Stechford",
    "SON": "Steeton & Silsden",
    "SPS": "Stepps",
    "SVG": "Stevenage",
    "STV": "Stevenston",
    "SWR": "Stewartby",
    "STT": "Stewarton",
    "STG": "Stirling",
    "SPT": "Stockport",
    "SKS": "Stocksfield",
    "SSM": "Stocksmoor",
    "STK": "Stockton",
    "SKM": "Stoke Mandeville",
    "SKW": "Stoke Newington",
    "SOT": "Stoke-on-Trent",
    "SNE": "Stone (Staffs)",
    "SCG": "Stone Crossing",
    "SBP": "Stonebridge Park",
    "SOG": "Stonegate",
    "STN": "Stonehaven",
    "SHU": "Stonehouse",
    "SNL": "Stoneleigh",
    "SBJ": "Stourbridge Junction",
    "SBT": "Stourbridge Town",
    "SOI": "Stow",
    "SMK": "Stowmarket",
    "STR": "Stranraer",
    "SRA": "Stratford (London)",
    "SFA": "Stratford International",
    "SAV": "Stratford-upon-Avon",
    "STY": "Stratford-upon-Avon Parkway",
    "STC": "Strathcarron",
    "STW": "Strawberry Hill",
    "STE": "Streatham (Greater London)",
    "SRC": "Streatham Common",
    "SRH": "Streatham Hill",
    "SHC": "Streethouse",
    "SRN": "Strines",
    "STF": "Stromeferry",
    "SOO": "Strood (Kent)",
    "STD": "Stroud (Gloucs)",
    "STU": "Sturry",
    "SYA": "Styal",
    "SUD": "Sudbury & Harrow Road",
    "SUY": "Sudbury (Suffolk)",
    "SDH": "Sudbury Hill Harrow",
    "SUG": "Sugar Loaf",
    "SUM": "Summerston",
    "SUU": "Sunbury",
    "SUN": "Sunderland",
    "SUP": "Sundridge Park",
    "SNG": "Sunningdale",
    "SNY": "Sunnymeads",
    "SUR": "Surbiton",
    "SQE": "Surrey Quays",
    "SUO": "Sutton (Surrey)",
    "SUT": "Sutton Coldfield",
    "SUC": "Sutton Common",
    "SPK": "Sutton Parkway",
    "SWL": "Swale",
    "SAY": "Swanley",
    "SWM": "Swanscombe",
    "SWA": "Swansea",
    "SNW": "Swanwick",
    "SWY": "Sway",
    "SWG": "Swaythling",
    "SWD": "Swinderby",
    "SWI": "Swindon (Wilts)",
    "SWE": "Swineshead",
    "SNN": "Swinton (Manchester)",
    "SWN": "Swinton (South Yorks)",
    "SYD": "Sydenham (London)",
    "SYH": "Sydenham Hill",
    "SYL": "Syon Lane",
    "SYS": "Syston",
    "TAC": "Tackley",
    "TAD": "Tadworth",
    "TAF": "Taffs Well",
    "TAI": "Tain",
    "TAL": "Talsarnau",
    "TLB": "Talybont",
    "TLC": "Tal-y-Cafn",
    "TAB": "Tame Bridge Parkway",
    "TAM": "Tamworth",
    "TAP": "Taplow",
    "TAT": "Tattenham Corner",
    "TAU": "Taunton",
    "TAY": "Taynuilt",
    "TED": "Teddington",
    "TEA": "Tees-side Airport",
    "TGM": "Teignmouth",
    "TFC": "Telford Central",
    "TMC": "Templecombe",
    "TEN": "Tenby",
    "TEY": "Teynham",
    "THD": "Thames Ditton",
    "THA": "Thatcham",
    "THH": "Thatto Heath",
    "THW": "The Hawthorns",
    "TLK": "The Lakes (Warks)",
    "THE": "Theale",
    "TEO": "Theobalds Grove",
    "TTF": "Thetford",
    "THI": "Thirsk",
    "TBY": "Thornaby",
    "TNN": "Thorne North",
    "TNS": "Thorne South",
    "THO": "Thornford",
    "THB": "Thornliebank",
    "TNA": "Thornton Abbey",
    "TTH": "Thornton Heath",
    "THT": "Thorntonhall",
    "TPB": "Thorpe Bay",
    "TPC": "Thorpe Culvert",
    "TLS": "Thorpe-le-Soken",
    "TBD": "Three Bridges",
    "TOK": "Three Oaks",
    "THU": "Thurgarton",
    "THC": "Thurnscoe",
    "THS": "Thurso",
    "TRS": "Thurston",
    "TIL": "Tilbury Town",
    "THL": "Tile Hill",
    "TLH": "Tilehurst",
    "TIP": "Tipton",
    "TIR": "Tir-Phil",
    "TIS": "Tisbury",
    "TVP": "Tiverton Parkway",
    "TOD": "Todmorden",
    "TOL": "Tolworth",
    "TPN": "Ton Pentre",
    "TON": "Tonbridge",
    "TDU": "Tondu",
    "TNF": "Tonfanau",
    "TNP": "Tonypandy",
    "TOO": "Tooting",
    "TOP": "Topsham",
    "TQY": "Torquay",
    "TRR": "Torre",
    "TOT": "Totnes",
    "TOM": "Tottenham Hale",
    "TTN": "Totton",
    "TWN": "Town Green",
    "TRA": "Trafford Park",
    "TRF": "Trefforest",
    "TRE": "Trefforest Estate",
    "TRH": "Trehafod",
    "TRB": "Treherbert",
    "TRY": "Treorchy",
    "TRM": "Trimley",
    "TRI": "Tring",
    "TRD": "Troed-y-rhiw",
    "TRN": "Troon",
    "TRO": "Trowbridge",
    "TRU": "Truro",
    "TUL": "Tulloch",
    "TUH": "Tulse Hill",
    "TBW": "Tunbridge Wells",
    "TUR": "Turkey Street",
    "TUT": "Tutbury & Hatton",
    "TWB": "Tweedbank",
    "TWI": "Twickenham",
    "TWY": "Twyford",
    "TYC": "Ty Croes",
    "TGS": "Ty Glas",
    "TYG": "Tygwyn",
    "TYL": "Tyndrum Lower",
    "TYS": "Tyseley",
    "TYW": "Tywyn",
    "UCK": "Uckfield",
    "UDD": "Uddingston",
    "ULC": "Ulceby",
    "ULL": "Ulleskelf",
    "ULV": "Ulverston",
    "UMB": "Umberleigh",
    "UNI": "University (Birmingham)",
    "UHA": "Uphall",
    "UPL": "Upholland",
    "UPM": "Upminster",
    "UPH": "Upper Halliford",
    "UHL": "Upper Holloway",
    "UTY": "Upper Tyndrum",
    "UWL": "Upper Warlingham",
    "UPT": "Upton (Merseyside)",
    "UPW": "Upwey",
    "URM": "Urmston",
    "UTT": "Uttoxeter",
    "VAL": "Valley",
    "VXH": "Vauxhall",
    "VIR": "Virginia Water",
    "WDO": "Waddon",
    "WAD": "Wadhurst",
    "WFL": "Wainfleet",
    "WKK": "Wakefield Kirkgate",
    "WKF": "Wakefield Westgate",
    "WKD": "Walkden",
    "WLG": "Wallasey Grove Road",
    "WLV": "Wallasey Village",
    "WLT": "Wallington",
    "WAF": "Wallyford",
    "WAM": "Walmer",
    "WSL": "Walsall",
    "WDN": "Walsden",
    "WLC": "Waltham Cross",
    "WHC": "Walthamstow Central",
    "WMW": "Walthamstow Queen's Road",
    "WAO": "Walton (Merseyside)",
    "WAL": "Walton-on-Thames",
    "WON": "Walton-on-the-Naze",
    "WAN": "Wanborough",
    "WSW": "Wandsworth Common",
    "WWR": "Wandsworth Road",
    "WNT": "Wandsworth Town",
    "WNP": "Wanstead Park",
    "WPE": "Wapping",
    "WBL": "Warblington",
    "WAR": "Ware (Herts)",
    "WRM": "Wareham (Dorset)",
    "WGV": "Wargrave",
    "WMN": "Warminster",
    "WNH": "Warnham",
    "WBQ": "Warrington Bank Quay",
    "WAC": "Warrington Central",
    "WAW": "Warrington West",
    "WRW": "Warwick",
    "WRP": "Warwick Parkway",
    "WTO": "Water Orton",
    "WBC": "Waterbeach",
    "WTR": "Wateringbury",
    "WLO": "Waterloo (Merseyside)",
    "WFH": "Watford High Street",
    "WFJ": "Watford Junction",
    "WFN": "Watford North",
    "WTG": "Watlington",
    "WAS": "Watton-at-Stone",
    "WNG": "Waun-Gron Park",
    "WAV": "Wavertree Technology Park",
    "WED": "Wedgwood",
    "WEE": "Weeley",
    "WET": "Weeton",
    "WMG": "Welham Green",
    "WLI": "Welling",
    "WEL": "Wellingborough",
    "WLN": "Wellington (Shropshire)",
    "WLP": "Welshpool",
    "WGC": "Welwyn Garden City",
    "WLW": "Welwyn North",
    "WEM": "Wem",
    "WMB": "Wembley Central",
    "WCX": "Wembley Stadium",
    "WMS": "Wemyss Bay",
    "WND": "Wendover",
    "WNN": "Wennington",
    "WSA": "West Allerton",
    "WBP": "West Brompton",
    "WBY": "West Byfleet",
    "WCL": "West Calder",
    "WCY": "West Croydon",
    "WDT": "West Drayton",
    "WDU": "West Dulwich",
    "WEA": "West Ealing",
    "WEH": "West Ham",
    "WHD": "West Hampstead",
    "WHP": "West Hampstead Thameslink",
    "WHR": "West Horndon",
    "WKB": "West Kilbride",
    "WKI": "West Kirby",
    "WMA": "West Malling",
    "WNW": "West Norwood",
    "WRU": "West Ruislip",
    "WRN": "West Runton",
    "WLD": "West St Leonards",
    "WSU": "West Sutton",
    "WWI": "West Wickham",
    "WWO": "West Worthing",
    "WSB": "Westbury (Wilts)",
    "WCF": "Westcliff",
    "WCB": "Westcombe Park",
    "WHA": "Westenhanger",
    "WTA": "Wester Hailes",
    "WFI": "Westerfield",
    "WES": "Westerton",
    "WGA": "Westgate-on-Sea",
    "WHG": "Westhoughton",
    "WNM": "Weston Milton",
    "WSM": "Weston-super-Mare",
    "WRL": "Wetheral",
    "WYB": "Weybridge",
    "WEY": "Weymouth",
    "WBR": "Whaley Bridge",
    "WHE": "Whalley (Lancs)",
    "WTS": "Whatstandwell",
    "WFF": "Whifflet",
    "WHM": "Whimple",
    "WNL": "Whinhill",
    "WHN": "Whiston",
    "WTB": "Whitby",
    "WHT": "Whitchurch (Cardiff)",
    "WCH": "Whitchurch (Hants)",
    "WTC": "Whitchurch (Shropshire)",
    "WHL": "White Hart Lane",
    "WNY": "White Notley",
    "ZLW": "Whitechapel",
    "WCR": "Whitecraigs",
    "WTH": "Whitehaven",
    "WTL": "Whitland",
    "WBD": "Whitley Bridge",
    "WTE": "Whitlocks End",
    "WHI": "Whitstable",
    "WLE": "Whittlesea",
    "WLF": "Whittlesford Parkway",
    "WTN": "Whitton (London)",
    "WWL": "Whitwell (Derbyshire)",
    "WHY": "Whyteleafe",
    "WHS": "Whyteleafe South",
    "WCK": "Wick",
    "WIC": "Wickford",
    "WCM": "Wickham Market",
    "WDD": "Widdrington",
    "WID": "Widnes",
    "WMR": "Widney Manor",
    "WGN": "Wigan North Western",
    "WGW": "Wigan Wallgate",
    "WGT": "Wigton",
    "WMI": "Wildmill",
    "WIJ": "Willesden Junction",
    "WLM": "Williamwood",
    "WIL": "Willington",
    "WMC": "Wilmcote",
    "WML": "Wilmslow",
    "WNE": "Wilnecote (Staffs)",
    "WIM": "Wimbledon",
    "WBO": "Wimbledon Chase",
    "WSE": "Winchelsea",
    "WIN": "Winchester",
    "WNF": "Winchfield",
    "WIH": "Winchmore Hill",
    "WDM": "Windermere",
    "WNC": "Windsor & Eton Central",
    "WNR": "Windsor & Eton Riverside",
    "WNS": "Winnersh",
    "WTI": "Winnersh Triangle",
    "WSF": "Winsford",
    "WSH": "Wishaw",
    "WTM": "Witham",
    "WTY": "Witley",
    "WTT": "Witton (West Midlands)",
    "WVF": "Wivelsfield",
    "WIV": "Wivenhoe",
    "WOB": "Woburn Sands",
    "WOK": "Woking",
    "WKM": "Wokingham",
    "WOH": "Woldingham",
    "WVH": "Wolverhampton",
    "WOL": "Wolverton",
    "WOM": "Wombwell",
    "WDE": "Wood End",
    "WST": "Wood Street",
    "WDB": "Woodbridge",
    "WGR": "Woodgrange Park",
    "WDL": "Woodhall",
    "WDH": "Woodhouse",
    "WDS": "Woodlesford",
    "WLY": "Woodley",
    "WME": "Woodmansterne",
    "WSR": "Woodsmoor",
    "WOO": "Wool",
    "WLS": "Woolston",
    "WWA": "Woolwich Arsenal",
    "WWD": "Woolwich Dockyard",
    "WWW": "Wootton Wawen",
    "WOF": "Worcester Foregate Street",
    "WCP": "Worcester Park",
    "WOS": "Worcester Shrub Hill",
    "WOP": "Worcestershire Parkway",
    "WKG": "Workington",
    "WRK": "Worksop",
    "WOR": "Worle",
    "WPL": "Worplesdon",
    "WRT": "Worstead",
    "WRH": "Worthing",
    "WRB": "Wrabness",
    "WRY": "Wraysbury",
    "WRE": "Wrenbury",
    "WRS": "Wressle",
    "WXC": "Wrexham Central",
    "WRX": "Wrexham General",
    "WYE": "Wye",
    "WYM": "Wylam",
    "WYL": "Wylde Green",
    "WMD": "Wymondham",
    "WYT": "Wythall",
    "YAL": "Yalding",
    "YRD": "Yardley Wood",
    "YRM": "Yarm",
    "YAE": "Yate",
    "YAT": "Yatton",
    "YEO": "Yeoford",
    "YVJ": "Yeovil Junction",
    "YVP": "Yeovil Pen Mill",
    "YET": "Yetminster",
    "YNW": "Ynyswen",
    "YOK": "Yoker",
    "YRK": "York",
    "YRT": "Yorton",
    "YSM": "Ystrad Mynach",
    "YSR": "Ystrad Rhondda",
}

def darwin_app_key():
    return secret.decrypt(ENCRYPTED_DARWIN_APP_KEY)

def fetch_departures(station, via):
    if len(via) > 0:
        filter = DEPARTURES_FILTER % via
    else:
        filter = ""

    app_key = darwin_app_key()
    if not app_key:
        return None
    request = DEPARTURES_REQUEST % (app_key, station, filter)

    cached = cache.get(request)
    if cached == EMPTY_DATA_IN_CACHE:
        return None
    if cached:
        return cached

    resp = http.post(
        url = DARWIN_SOAP_URL,
        body = request,
        headers = {
            "Content-Type": "application/soap+xml; charset=utf-8",
        },
    )
    if resp.status_code != 200:
        cache.set(request, EMPTY_DATA_IN_CACHE, ttl_seconds = 30)
        return None
    cache.set(request, resp.body(), ttl_seconds = 60)
    return resp.body()

def render_error(error):
    return render.Root(
        child = render.Column(
            main_align = "center",
            expanded = True,
            children = [
                render.WrappedText(
                    content = error,
                    width = 64,
                    align = "center",
                    color = ORANGE,
                ),
            ],
        ),
    )

def render_title(name):
    return render.Box(
        width = 64,
        height = 7,
        color = BLUE,
        child = render.Padding(
            pad = (1, 1, 1, 0),
            child = render.Marquee(
                width = 62,
                align = "center",
                child = render.WrappedText(
                    content = name,
                    height = 6,
                    align = "center",
                    font = FONT,
                ),
            ),
        ),
    )

def render_separator():
    return render.Box(height = 1)

def render_times(scheduled, expected):
    if expected == "On time":
        expected_colour = GREEN
    else:
        expected_colour = RED

    return render.Row(
        expanded = True,
        main_align = "space_between",
        children = [
            render.WrappedText(
                content = scheduled,
                width = 20,
                height = 6,
                font = FONT,
            ),
            render.WrappedText(
                align = "right",
                content = expected,
                width = 40,
                height = 6,
                font = FONT,
                color = expected_colour,
            ),
        ],
    )

def render_destination(destination):
    return render.WrappedText(
        content = destination,
        font = FONT,
        width = 62,
        height = 6,
        align = "left",
    )

def render_no_departures():
    return render.Column(
        expanded = True,
        main_align = "space_around",
        children = [
            render.WrappedText(
                content = "No departures",
                font = FONT,
                width = 62,
                height = 6,
                align = "center",
                color = GRAY,
            ),
        ],
    )

def render_detailed_train(scheduled, expected, operator, destination, length, platform, calling_at):
    messages = []
    if operator:
        messages.append("%s service" % operator)
    else:
        messages.append("Service")
    if destination:
        messages.append("to %s" % destination)
    if length:
        messages.append("with %s carriages" % length)
    if platform:
        messages.append("on platform %s" % platform)
    messages.append("calling at " + " and ".join(", ".join(calling_at).rsplit(", ", 1)))
    message = " ".join(messages)
    # message = "Platform %s to %s" % (platform, calling)

    return render.Box(
        width = 62,
        height = 12,
        child = render.Column(
            children = [
                render.Animation(
                    children = [render_times(scheduled, expected)] * INFO_TOGGLE_FRAMES +
                               [render_destination(destination)] * INFO_TOGGLE_FRAMES,
                ),
                render.Marquee(
                    width = 62,
                    height = 6,
                    child = render.Text(
                        content = message,
                        font = FONT,
                        color = GRAY,
                    ),
                ),
            ],
        ),
    )

def render_compact_train(scheduled, expected, destination):
    return render.Box(
        width = 62,
        height = 6,
        child = render.Animation(
            children = [render_times(scheduled, expected)] * INFO_TOGGLE_FRAMES +
                       [render_destination(destination)] * INFO_TOGGLE_FRAMES,
        ),
    )

def render_train(departures, index, display_mode):
    scheduled = departures.query("//lt5:trainServices/lt5:service[%s]/lt4:std" % index)
    expected = departures.query("//lt5:trainServices/lt5:service[%s]/lt4:etd" % index)
    destination_crs = departures.query("//lt5:trainServices/lt5:service[%s]/lt5:destination/lt4:location/lt4:crs" % index)
    destination = STATIONS[destination_crs]

    if display_mode == DISPLAY_DETAILED:
        platform = departures.query("//lt5:trainServices/lt5:service[%s]/lt4:platform" % index)
        operator = departures.query("//lt5:trainServices/lt5:service[%s]/lt4:operator" % index)
        length = departures.query("//lt5:trainServices/lt5:service[%s]/lt4:length" % index)
        calling_at = departures.query_all("//lt5:trainServices/lt5:service[%s]//lt4:callingPoint/lt4:locationName" % index)
        return render_detailed_train(scheduled, expected, operator, destination, length, platform, calling_at)

    if display_mode == DISPLAY_COMPACT:
        return render_compact_train(scheduled, expected, destination)

    fail("Invalid display mode: %s" % display_mode)

def main(config):
    origin_station = config.get(ORIGIN_STATION) or "KGX"

    destination_station = config.get(DESTINATION_STATION)
    if destination_station and destination_station != NO_DESTINATION:
        filter_station = destination_station
    else:
        filter_station = ""

    display_mode = config.get(DISPLAY_MODE) or DISPLAY_DETAILED
    if display_mode == DISPLAY_DETAILED:
        max_trains = 2
    elif display_mode == DISPLAY_COMPACT:
        max_trains = 4
    else:
        fail("Invalid display mode %s" % display_mode)

    resp = fetch_departures(origin_station, filter_station)
    if not resp:
        return render_error("Train times not available")
    departures = xpath.loads(resp)
    trains = departures.query_all("//lt5:trainServices/lt5:service")
    if len(trains) == 0:
        rendered_trains = [render_no_departures()]
    else:
        max_trains = min(max_trains, len(trains))
        rendered_trains = [render_train(departures, t + 1, display_mode) for t in range(max_trains)]

    return render.Root(
        child = render.Column(
            cross_align = "center",
            children = [
                render_title(STATIONS[origin_station]),
                render_separator(),
            ] + rendered_trains,
        ),
    )

def get_schema():
    no_destination_option = schema.Option(
        display = NO_DESTINATION,
        value = NO_DESTINATION,
    )
    station_options = [schema.Option(display = name, value = crs) for crs, name in STATIONS.items()]

    return schema.Schema(
        version = "1",
        fields = [
            schema.Dropdown(
                id = ORIGIN_STATION,
                name = "Origin",
                desc = "Station to look up departure times for",
                icon = "train",
                default = "KGX",
                options = station_options,
            ),
            schema.Dropdown(
                id = DESTINATION_STATION,
                name = "Destination",
                desc = "Only show trains going to this station (optional)",
                icon = "train",
                default = NO_DESTINATION,
                options = [no_destination_option] + station_options,
            ),
            schema.Dropdown(
                id = DISPLAY_MODE,
                name = "Display mode",
                desc = "Controls whether to show more trains or more details about each train",
                icon = "display",
                default = DISPLAY_DETAILED,
                options = [
                    schema.Option(
                        display = "Detailed",
                        value = DISPLAY_DETAILED,
                    ),
                    schema.Option(
                        display = "Compact",
                        value = DISPLAY_COMPACT,
                    ),
                ],
            ),
        ],
    )
