name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.TIDBYT_GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.TIDBYT_GITHUB_TOKEN }}
        with:
          path-to-document: https://github.com/tidbyt/community/blob/main/docs/CLA.md
          allowlist: tidbyt-bot,renovate-bot,renovate[bot]

          remote-organization-name: tidbyt
          remote-repository-name: cla-signatures
          branch: main
          path-to-signatures: signatures.json

          signed-commit-message: "$contributorName has signed the CLA in tidbyt/community#$pullRequestNo"
          lock-pullrequest-aftermerge: false
