name: Lock closed pull requests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.TIDBYT_GITHUB_TOKEN }}
          process-only: prs
          pr-inactive-days: '2'
